### ISSUE TITLE
Configurable packages in Linux

### ISSUE THREAD

**Issue by greg-hellings** [crosswire/xiphos#1014]
Currently, when building in Linux, both RPM and Deb packages are generated unconditionally. Make it selectable, or auto-detect to only generate the package for the current system.

**Comment by alerque** [comment]
I don't get any packages at all when I build on Linux. Are you sure you don't mean when you run some `make dist` or similar target? I get the idea and agree that's desirable, I just don't know what build command you're even running.

**Comment by greg-hellings** [comment]
`make package` will have it generate an RPM and Deb if you're building a Linux version or an NSIS .exe if you're building for Windows.

**Comment by greg-hellings** [comment]
This is a moot point. We aren't really targeting those builds, and anyone who wants to do just one can do it with "cpack -G RPM" or "cpack -G DEB"
