### ISSUE TITLE
HTTPS not working on website

### ISSUE THREAD

**Issue by alerque** [crosswire/xiphos#1022]
The xiphos.org doesn't have a valid HTTPS certificate. That should be amended (free and easy via Letsencrypt), and made the default.

(Is there a separate repo and/or issue tracker for the website?)

**Comment by DrMeers** [comment]
Fixed?

**Comment by alerque** [comment]
Yes! Great.

Is there a repo for the website somewhere? There is some outdated build info for example I could contribute a fix for.

**Comment by DrMeers** [comment]
No separate repo. Feel free to detail your content change here and I'll get it updated.

The website is super-old, and in need of a rebuild... it used to be very clever and automatically compile HTML manual pages from repo source, etc, but that was all built on the old SVN tech. I'd be happy to see it replaced by a modern out-of-the-box option so we can retire the custom one, if anyone has time or inclination...

**Comment by alerque** [comment]
Can I suggest kicking off an empty Git repository in this namespace so we can start discussing & hacking on it there? I would call it either xiphos.org or xiphos.github.io if there is any plan to host in using Github Pages (obviously the tech stack will be one of the first discussions to have!).

The most urgent thing I see on the legacy site is on the Download page under "Git access", the build instructions are obsolete. I would either nuke them entirely in favor of sending people off to this repo's README, or at least swap them out to this:

```bash
cd xiphos
cmake -S . -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DGTKHTML=ON
make -C build
sudo make -C build install
```

Honestly probably saying nothing at all there is best for now.

**Comment by karlkleinpaste** [comment]
i see simon made the basic version stamp updates around xiphos.org; thanx.

i just did a little work on the downloads page to get rid of the outdated instructions.

**Comment by DrMeers** [comment]
@alerque Yes I was considering porting a static version of the current site to GitHub Pages -- we really don't need the dynamic CMS/backend functionality. Happy for someone else to do so, I've been having trouble finding time to do so, but should get to it eventually

**Comment by DrMeers** [comment]
@karlkleinpaste the company that has been hosting xiphos.org is shutting down these outdated servers in the next couple of weeks, and I'm forced to move the site. It's running on Python 2 etc which is too old to drag-and-drop onto a new server, so it would take quite a few hours to port the dynamic site with admin/login functionality, etc. I propose just running a recursive-`wget` on the public facing site and making this available via [Github Pages](https://pages.github.com/) on xiphos.org . We don't make heavy use of the admin functionality nowadays anyway, and updates won't be overly difficult via raw HTML. Should we:

a) create a separate `xiphos.org` github project under `crosswire` for this, or
b) commit the pages to a `website` directory in the `xiphos` repository and point the Github Pages setting for the `xiphos` repository at this, or
c) set it up under my personal github account?

It would be nicer to rebuild the whole dynamic site or set it up using [Jeykll](https://docs.github.com/en/github-ae@latest/github/working-with-github-pages/about-github-pages-and-jekyll) or another static site generator, but I don't think I'll find the time for this in the next couple of weeks, so the static dump should get us by until someone has time and energy to do something more elaborate/elegant.

Commenting on this old closed ticket as there are some relevant comments above leading up to this.

**Comment by alerque** [comment]
My recommendation is a separate repository for the website, but it's not the end of the world if it gets stashed in a branch here. If getting a new repo spun up with the right permissions can't happen fast enough a branch here can always be promoted to it's own repository later when it can be.

**Comment by DrMeers** [comment]
Who has repository creation permissions to create a `crosswire/xiphos.org` repo and grant me push access?

**Comment by DrMeers** [comment]
In the absence of a response I've set this up under my personal repository for now, keen to migrate to a `crosswire` one as soon as possible so I'm not the single point of failure

**Comment by karlkleinpaste** [comment]
apologies, i didn't mean to ignore you. i'll get in touch over the weekend; USA is on a national holiday.

**Comment by karlkleinpaste** [comment]
good gracious. i'm looking at cutting back open xiphos issues, and here i find this from 4½ yrs ago. ow.

is there something i can do to take care of this? do you need me to create a place to clone content?

**Comment by DrMeers** [comment]
no urgency to do so, it's working fine from my personal account for now, it'd just be so that people other than me can access/update in future as/when required

**Comment by DrMeers** [comment]
though it might be a good idea so we can do it at the same time as updating the website with the latest release details @karlkleinpaste ?

**Comment by karlkleinpaste** [comment]
absolutely. as you've probably seen, i had to retract 4.3.0 for a 4.3.1 emergency fix update.

what do you need me to create? a new git repo under crosswire? how to name it?

**Comment by DrMeers** [comment]
it's currently residing in https://github.com/DrMeers/xiphos.org and published via these repo settings under "Pages":

<img width="762" alt="Image" src="https://github.com/user-attachments/assets/164627e4-c6f4-4c62-8740-39ab97bc5042" />

so we'd just need to set up a similar repository that I have push access to (and maybe admin access if you want me to configure the Pages settings) -- you could clone that one, or set up an empty one, I don't mind. I'll probably need to perform some DNS validation to grant authority to the new repository for `xiphos.org` once it's ready.

**Comment by karlkleinpaste** [comment]
ok, i've just created an empty crosswire/xiphos.org repo, and made you admin of it. i imagine you can `push --force` your current state into it.

what else is needed?

**Comment by DrMeers** [comment]
thanks @karlkleinpaste I've done that, and have updated links for 4.3.1 release which is now being served from the new repository. Anyone with access can make modifications to the source HTML and GitHub actions will automatically deploy the changes within a minute or so.
