### ISSUE TITLE
Consider removing/renaming win32/suse

### ISSUE THREAD

**Issue by greg-hellings** [crosswire/xiphos#1026]
The win32/suse directory seems mis-named and all-around unnecessary now. It seems to include shell scripts that were of use to building Xiphos and dependencies back when we were relying on the SuSE MinGW packages in the early days of their existence. We should get rid of them, now, if we can.

**Comment by domcorbex** [comment]
As you have stated before, beyond the win32/suse, a major clean-up is required in the win32 dir:
- move win32/fonts -> CPack/windows/fonts
- move win32/nsis/pixmaps -> CPack/windows/pixmaps
- move win32/nsis/include -> CPack/windows/include
- move CPack/windows/*.nsh -> CPack/windows/include
Then reflect the changes in:
- XiphosWindowsPkg.cmake
- Include changes in nsis_extra_install_commands.nsh.in
- Include changes in nsis_installer_mui_icon_code.nsh.in
We have to keep:
- win32/include 
- win32/winres/xiphos-winres.rc.in
I think we should move up all the stuff placed in the extra directory,  reflect changes in win32/CMakeLists.txt
and then delete:
- devenv dir
- devscripts dir
- patches dir
- suse dir
- files.txt

**Comment by domcorbex** [comment]
Fixed in d8c2af9
