### ISSUE TITLE
Module manager - Maintenance - Scan Obsolete

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#1028]
_A whimsical question…_

If perchance a module's **xyz.conf** contained the line 
`Obsoletes=XYZ`
could **Scan Obsolete** lead to potential "self-destruct" ?

**Comment by karlkleinpaste** [comment]
self-referential obsolescence is all that would occur: the module would be deleted.
not very interesting, and a stupid configuration to produce anyhow.
there's no fatal conflict in asking mod.mgr to delete oneself.

**Comment by alerque** [comment]
Except perhaps in a case were a bad actor hosting modules somewhere decides to use it as a mechanism to hijack users innocently trying to update and causes their module to be deleted instead. Given some of the modules than have been yanked in the past it would be nice if there _wasn't_ a mechanism that could support revoking distributed materials like that.
