### ISSUE TITLE
Cannot find sword 1.8.1, but I compiled and installed it

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#1029]
Here is annotated command list, running VM with Debian Buster

root@BusterExperimental:/home/spring/xiphos_download# cmake -S xiphos-4.2.1 -B build
-- Looking for glib-genmarshal
-- Looking for glib-genmarshal - found
-- Looking for xmllint
-- Looking for xmllint - found
-- Looking for xsltproc
-- Looking for xsltproc - found
-- Looking for dbus-binding-tool
-- Looking for dbus-binding-tool - found
-- Looking for itstool
-- Looking for itstool - found
-- Looking for desktop-file-validate
-- Looking for desktop-file-validate - found
-- Looking for appstream-util
-- Looking for appstream-util - found
-- Looking for yelp-build
-- Looking for yelp-build - found
-- Looking for uuidgen
-- Looking for uuidgen - found
-- Looking for zip
-- Looking for zip - found
-- Checking for module 'sword>=1.8.1'
--   **No package 'sword' found**<--------------------------
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  cmake/XiphosDependencies.cmake:55 (pkg_check_modules)
  CMakeLists.txt:88 (include)

-- Configuring incomplete, errors occurred!
root@BusterExperimental:/home/spring/xiphos_download# osis2mod  <------- This works, proves Sword present. I used source as shown on Crosswire home page, but substitute 1.8.1 for listed 1.8.0.
You are running osis2mod: $Rev: 3431 $
OSIS Bible/commentary module creation tool for The SWORD Project

I tried to find where is all that stuff it was looking for Sword or how, but came up empty. Sorry.

**Comment by alerque** [comment]
Does your system's pkgconfig find SWORD?

    pkg-config --cflags sword

**Comment by TomSullivanInUSA** [comment]
I did: (and see questions and further issues below)
root@BusterExperimental:/home/spring/xiphos_download# pkg-config --cflags sword
Package sword was not found in the pkg-config search path.
Perhaps you should add the directory containing `sword.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sword' found
root@BusterExperimental:/home/spring/xiphos_download# export PKG_CONFIG_PATH=/home/spring/SwordDownLoad/sword-1.8.1
root@BusterExperimental:/home/spring/xiphos_download# pkg-config --cflags sword
-I/usr/local/include/sword

It created the build after that. But there was a warning that:
Webkit2 and the WebKit2-editor were both selected ON, but integration of
  the Webkit2 editor is a work in progress.  This can lead to fatal errors
  and build failures.

But, I cannot find a package for webkitgtk-3.0 for Buster, only the previous Debian release, Jessie. and the alternatives:
--   No package 'gtkhtml-editor-4.0' found
--   No package 'libgtkhtml-4.0' found
Are not in my repository.

This is really getting out of hand. Any ideas?

**Comment by domcorbex** [comment]
On Tue, 12 May 2020 15:36:08 -0700
TomSullivanInUSA <notifications@github.com> wrote:

> This is really getting out of hand. Any ideas?


See: https://github.com/crosswire/xiphos/blob/master/INSTALL.md

Section:
Build Xiphos On Debian, Ubuntu, or Linux Mint

Dom
-- 
domcox <dominique@corbex.org>

**Comment by TomSullivanInUSA** [comment]
Nothing I tried is without errors. Instructions have errors. Some were obvious to me, others not.

I give up. Thanks all anyway.

**Comment by alerque** [comment]
We are working on fresh Sword / GtkHtml / Xiphos packages in a PPA so that installation on Debian based distros will be painless. Doing it manually is not the way to go ;-)
