### ISSUE TITLE
Very tight morphological label in OSHB

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#1033]
the picture will explain better than words:
![ohsm_morph](https://user-images.githubusercontent.com/19690477/82536424-bbdd1400-9b48-11ea-9eca-355145c3770a.png)

The other problem with the morph tag in OSHB is that they are not recognize when I click on. But this can be an issue of the module, I have no idea. The osis file is like this:
```
chapter osisID="Gen.1">
		<verse osisID="Gen.1.1"><w lemma="strong:H07225" morph="oshm:HR/Ncfsa" n="1.0"><seg>בְּ</seg><seg>רֵאשִׁ֖ית</seg></w> <w lemma="strong:H01254" morph="oshm:HVqp3ms">בָּרָ֣א</w> <w lemma="strong:H0430" morph="oshm:HNcmpa" n="1">אֱלֹהִ֑ים</w> <w lemma="strong:H0853" morph="oshm:HTo">אֵ֥ת</w> <w lemma="strong:H08064" morph="oshm:HTd/Ncmpa" n="0.0"><seg>הַ</seg><seg>שָּׁמַ֖יִם</seg></w> <w lemma="strong:H0853" morph="oshm:HC/To"><seg>וְ</seg><seg>אֵ֥ת</seg></w> 
```

OSHM is installed.

**Comment by karlkleinpaste** [comment]
this is webkit's choice and i don't try to understand it any more. it seems to have more trouble with spacing with RtoL languages than otherwise.  in some modules (greek, notably; example screenshot) it puts in generous inter-word spacing, in others (hebrew) it jams them together. all the code does is to paste the elements into the widget; why WK chooses to jam them together in some cases, i don't know.
![screenshot1](https://user-images.githubusercontent.com/7548920/82549057-5417d080-9b2a-11ea-90bd-ec488c727b30.png)

**Comment by LAfricain** [comment]
Then we just consider it's not working for hebrew?

**Comment by karlkleinpaste** [comment]
from the standpoint that i'm not aware of having any controls by which to change the behavior, yes. consider it a webkit bug. if someone can identify a way to modify how content is pasted into the html widget that improves this, i'm all ears.

the code requests filtered content from the engine, then copies that into the widget after wrapping strong's & morph in css controls for blocks. it has always worked fine for LtoR languages. the mechanism by which to extract strong's & morph for blocks doesn't change by direction of text, so there's no difference in morph handling for RtoL languages, yet WK won't put in separation the way it obviously does for LtoR.  compare with KJV strong's/morph display.

**Comment by LAfricain** [comment]
**Proposed workaround for Hebrew morphology display overlap**

As Karl noted, the root cause is WebKit's poor inter-word spacing handling for RTL languages, which is beyond our direct control. However, since the morph codes are already wrapped in CSS-controlled blocks, we can reduce the visual overlap by **truncating the displayed code after the main word segment**, keeping only the prefixes and the first meaningful part of speech segment (noun, verb, adjective, etc.) and dropping the pronominal suffixes from the inline display.

This is a content-side workaround rather than a true fix: it reduces the length of the displayed codes, which mechanically reduces overlap even when WebKit refuses to insert proper spacing. It could coexist with any future CSS/unicode-bidi fix targeting the spacing issue itself.

Example:
- Full code: `hr/ncbpdvqp3hnp`
- Displayed: `hr/ncbp`
- Suffix `dvqp3hnp` (pronominal) hidden inline, still fully visible on hover

Short codes (e.g. `HVqp3ms`) would be left untouched.

This would be conditioned on the Hebrew language prefix (`H`) so Greek and Aramaic morphology display remains unaffected.

The truncation logic would follow the [OSHB morphology code specification](https://hb.openscriptures.org/parsing/HebrewMorphologyCodes.html).

@karlkleinpaste do you agree?
