### ISSUE TITLE
Help Contents does nothing

### ISSUE THREAD

**Issue by timsoftgit** [crosswire/xiphos#1034]
help items tested..
help-"Mailing List" help-"Live Chat" help-"Report Bug" and help-"View xiphos Releases" open browser to relevant page/site as expected.
help-"About Translation" help-"About the SWORD Project" help-"About BibleSync" and help-"About Xiphos" open info/popup window as expected, but
help-"Contents" does nothing. no popup or browser, and no errors/warnings on command line if run from a konsole. xiphos is created by running cmake is with following options.

`cmake -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DMAN_INSTALL_DIR=/usr/man \
    -DHTMLHELP=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DDBUS=OFF -DSTRIP=ON -DPOSTINST=OFF -DGTKHTML=ON ..`
(before running make and make install DESTDIR=<package_dir> )
where package_dir is the location used by the os packager to create the package (in this case, slackware).

version of xiphos is 4.2.1 biblesync 2.0.1 sword 1.8.1 (with patch to fix pre-chapter text).

**Comment by domcorbex** [comment]
What's the result of:
`yelp  /usr/share/help/C/xiphos/index.page`

**Comment by timsoftgit** [comment]
unfortunately that file doesn't exist. the contents of /usr/share/help/C/xiphos is 22 files of the name format
xiphox-NN-desc.page where NN is a number and desc is the description.
eg. xiphos-01-introduction.page
....on lookin further..
woops, my bad, I just spotted I had installed yelp dependencies, but not yelp itself.
having fixed that snaafu and it works now as expected. sorry for the "noise"

**Comment by domcorbex** [comment]
On Fri, 29 May 2020 03:21:24 -0700
Tim <notifications@github.com> wrote:

> woops, my bad, I just spotted I had installed yelp dependencies, but not yelp itself.
> having fixed that snaafu and it works now as expected. sorry for the "noise"

You're welcome :)
dom
-- 
domcox <dominique@corbex.org>
