### ISSUE TITLE
Only the .tar.xz release file has cmake/source_version.txt

### ISSUE THREAD

**Issue by lsalvadore** [crosswire/xiphos#1037]
Only the .tar.xz release file has cmake/source_version.txt. As a consequence, the build fails with the .zip and .tar.gz files.

This concerns release 4.2.1.

**Comment by alerque** [comment]
This is as intended. The other files are just tar archives created by Github that snapshot the latest commit but do not include meta data about what version they actually are. You may provide that yourself to build from those files, but the two recommended ways are either to download the git repository _with history_ or to use the provided source package that is preconfigured and ready to build.

If you have a need for a source build in an archive format not supplied (i.e. a platform that cannot extract `.tar.xz` we could build source packages in other archive formats, but you do need to use actual source packages, not git archives.

**Comment by greg-hellings** [comment]
There are two GZ tarfiles in the release. The one auto created by Git Hub will not work, per Caleb's point. It is not intended to work. The one xiphos-4.2.1.tar.gz should work. If the file is missing from that tarball, then this issue needs addressing.

No zip file is provided except what Git Hub wraps up. That will not work and is not intended to ever work.
