### ISSUE TITLE
the bible text contains code that does not belong there.

### ISSUE THREAD

**Issue by S-A-TOP** [crosswire/xiphos#1045]
in revelations 22:21: 

De genade van onzen Heere Jezus Christus zij met u allen. Amen. #THE UNBOUND BIBLE (www.unboundbible.org) #name Estonian #filetype Unmapped-BCV #copyright #abbreviation #language est #note #columns orig_book_index orig_chapter orig_verse text   (Openbaring 22:21 [DutSVV])

this part should be removed: 

#THE UNBOUND BIBLE (www.unboundbible.org) #name Estonian #filetype Unmapped-BCV #copyright #abbreviation #language est #note #columns orig_book_index orig_chapter orig_verse text   

this part should stay:

De genade van onzen Heere Jezus Christus zij met u allen. Amen. (Openbaring 22:21 [DutSVV])

the same problem also exists in andbible.

**Comment by karlkleinpaste** [comment]
amazing that no one ever noticed that before. however, module errors are not within the purview of xiphos to fix. please report at http://jira.crosswire.org/secure/Dashboard.jspa .

**Comment by LAfricain** [comment]
Already reported, and correction done. We are waiting for an update of the module. An Andbible user reported this already.
See https://tracker.crosswire.org/browse/MOD-372
