### ISSUE TITLE
Xiphos 4.1.0 - Drop Down Menus Don't Scroll

### ISSUE THREAD

**Issue by rbeltz48** [crosswire/xiphos#1048]
I am using Debian 10.4 with the MATE desktop. I tried to file a Debian bug report on the package Xiphos 4.1.0 (gtk3 webkit1) but I don't think it went through.

The bug was reported here more than a year ago before Debian 10 was released:

http://forums.debian.net/viewtopic.php?f=30&t=141995&p=698478&hilit=Xiphos#p698478

It has also been reported at these links:
https://forum.manjaro.org/t/gtk3-combobox-list-doesnt-scroll-sometimes/77886

https://forum.manjaro.org/t/solved-xiph ... em/75704/4

http://forums.debian.net/viewtopic.php?f=10&t=146645

I originally noticed it in Linux Mint Debian Edition 4 and then in Debian 10. It appears to be a gtk3 problem. Linux Mint was of no help and Crosswire developers helped minimally and said it was not their problem but a gtk3 problem. The bug does not exist in Linux Mint main editions or Ubuntu based distros.

The drop down menus (book, chapter, verse) don't work the way they should with up and down pointer arrows (they are missing), making the application somewhat difficult to use, though usable with extra work. One can't page forward or backward but only pull up the books that are showing on the screen. Research reveals it is a gtk3 problem. A posting from Manjaro states that gtk 3.24.7 solves the issue.

Two attachments are included:

Debian 10      - The main screen with the up/down pointers missing
Linux Mint 18 - The main screen with the up/down pointers present

Other people are also having the same problem. Can anyone help me solve this issue? Thanks.

![Xiphos Screen - Debian 10](https://user-images.githubusercontent.com/17127007/86488821-4ad87100-bd30-11ea-8e7f-8022608da0e9.png)

![Xiphos Screen - Linux Mint 18](https://user-images.githubusercontent.com/17127007/86488834-5166e880-bd30-11ea-98cf-ad7e93bb69ba.png)

**Comment by greg-hellings** [comment]
> A posting from Manjaro states that gtk 3.24.7 solves the issue.

Sounds like it's solved. We get this report frequently, and the same answer every time: this is a GTK issue and there's nothing Xiphos can do to solve it for you. Upgrade or patch your GTK version.

**Comment by rbeltz48** [comment]
How do I "upgrade or
        patch your GTK version"?
        
        Rick Beltz
          
        
    On 07/03/2020 04:55 PM, Greg
        Hellings wrote:
      
    
      
      
        
        A posting from Manjaro states that gtk 3.24.7 solves the
            issue.
        
        
      
      
      Sounds like it's solved. We get this report frequently,
          and the same answer every time: this is a GTK issue and
          there's nothing Xiphos can do to solve it for you. Upgrade or
          patch your GTK version.
      
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or unsubscribe.
      [
{
"@context": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/1048#issuecomment-653675256">"https://github.com/crosswire/xiphos/issues/1048#issuecomment-653675256"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/1048#issuecomment-653675256">"https://github.com/crosswire/xiphos/issues/1048#issuecomment-653675256"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]

**Comment by greg-hellings** [comment]
You need to wait for Debian to package a version of GTK that includes the fixes in 3.24.7 (or earlier) that are noted by the Manjaro report of this.

It's possible that you can get it done, but it's Debian. I wouldn't hold my breath. So probably just wait for a new version of Debian to ship with the fixed version of GTK.

**Comment by rbeltz48** [comment]
Greg,
        
        I don't get it. Ubuntu and Linux Mint
          send out fixes all the time. This problem has existed in Debian
              based distros and other Arch
                and Fedora based distros since at least March 2019.
                  
                  Sad to say, I plan to scrap
                    Debian and go with
                      something else. I have already spent countless
                      hours trying to research this but to no avail.
                      Thanks for replying.
                      
                      Rick  Beltz
                        ____________________________________________________________
                      
    On 07/04/2020 01:29 PM, Greg
        Hellings wrote:
      
    
      
      You need to wait for Debian to package a version of GTK
          that includes the fixes in 3.24.7 (or earlier) that are noted
          by the Manjaro report of this.
      
      
      It's possible that you can get it done, but it's Debian. I
          wouldn't hold my breath. So probably just wait for a new
          version of Debian to ship with the fixed version of GTK.
      
      
      —
          You are receiving this because you authored the thread.
          Reply to this email directly, view
            it on GitHub, or unsubscribe.
      
        [
{
"@context": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/1048#issuecomment-653791844">"https://github.com/crosswire/xiphos/issues/1048#issuecomment-653791844"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/1048#issuecomment-653791844">"https://github.com/crosswire/xiphos/issues/1048#issuecomment-653791844"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]

**Comment by greg-hellings** [comment]
I'm not sure what you don't get. If you installed GTK from the Debian archives, you'll need them to fix their version and wait for that to make it into their update cycle. Debian, Ubuntu, Mint, etc are very difficult to get fixes that aren't pure bug-fix-only fixes into it.

As for Fedora, I'm sitting here on Fedora right now and the display works flawlessly with the oversized combo box. Fedora is much easier to get an update into and tends to be on top of releases much more quickly than Ubuntu or Debian as a result. Both of those focus on maximum stability for workstation and server loads whereas Fedora is more focused on being a desktop distribution and so is a bit more open to a rolling release window.

Either way, this isn't a Xiphos issue, and getting an updated toolchain into a particular Linux distro is DEFINITELY not something Xiphos is involved in.
