### ISSUE TITLE
xiphos 4.2.1 install windows XP

### ISSUE THREAD

**Issue by Fabio-LV** [crosswire/xiphos#1050]
After installing xiphos 4.2.1 in windows XP, trying to run it I get the message:
"Unable to access procedure entry-point AcquireSRWLockExclusive in dynamic library KERNEL32.dll"

File downloaded: xiphos-4.2.1-win32.exe

**Comment by karlkleinpaste** [comment]
regrets, but we're going to have to delete references to support for XP in our docs.  XP is just too old; the fact that it's missing this lock function is just one more indication of how old it is.  official support for windows (from microsoft itself) ended in 2014.
