### ISSUE TITLE
Error launching Xiphos 4.2.1 in Win XP

### ISSUE THREAD

**Issue by Fabio-LV** [crosswire/xiphos#1051]
After installing xiphos 4.2.1 in windows XP, trying to run it I get the message:
"Unable to access procedure entry-point AcquireSRWLockExclusive in dynamic library KERNEL32.dll"

File downloaded: xiphos-4.2.1-win32.exe

**Comment by alerque** [comment]
For the record (and in case the OP has this link and lost the other one) this is a duplicate of #1050.
