### ISSUE TITLE
Linux Mint 20 problem.

### ISSUE THREAD

**Issue by redwingskodi** [crosswire/xiphos#1052]
upon installation, I added my bibles, commentaries, etc. and then changed my background and text colors.  This is the same thing I have been doing for many years. However, now it does not save any settings and reverts back to the startup format every time it is opened.  I also noticed that it creates a 2nd icon next to the one pinned on the panel.  I tried reinstalling a few times after deleting and removing all associated files.  Same thing. Everything seems to work as should after I set it up, only problem is not saving your profile settings upon exit.

**Comment by LAfricain** [comment]
Which version of Xiphos do you use? The Ubuntu ppa?

**Comment by redwingskodi** [comment]
I'm leaving for work so cant look, but I installed directly from mint 20
software manager. I can check this evening when I get home from work

**Comment by LAfricain** [comment]
This is strange because Ubuntu 20.04 doens't have xiphos in the universe repository. Try with the crosswire ppa, with focal.

**Comment by redwingskodi** [comment]
Thanks, do you have a ppa tutorial link. I am fine either adding in the
additional ppa area of the update manager or via terminal. Tried last night
to add the ppa but believe i had an old tutorial as it did not install via
terminal. Driving me nuts because I have been using this software for about
10 years (by memory) as a minister.

**Comment by karlkleinpaste** [comment]
> now it does not save any settings and reverts back to the startup format

you've got a "flatpak" or "appimage" version of xiphos. we've seen it before; it's not ours, we didn't build it, and it's a nigthmare. delete it and use the ppa mentioned in the release page.
https://github.com/crosswire/xiphos/releases/tag/4.2.1

**Comment by redwingskodi** [comment]
Thank you for your help in this matter.

**Comment by LAfricain** [comment]
Just add this line to your sources.list:
deb http://ppa.launchpad.net/pkgcrosswire/ppa/ubuntu focal main 
or Follow the instruction in this page: https://launchpad.net/~pkgcrosswire/+archive/ubuntu/ppa

**Comment by redwingskodi** [comment]
Worked perfect after adding ppappa. Thank you so much!
