### ISSUE TITLE
Display/Resolution issue for a newbie

### ISSUE THREAD

**Issue by gmtodd** [crosswire/xiphos#1054]
![Screenshot from 2020-08-12 09-18-33](https://user-images.githubusercontent.com/69639785/90152540-8877e300-dd4d-11ea-8b64-8f4cfe70ea43.png)
Newbie here. Please notice the left side of the xiphos window. How can i center it correctly? (not sure on the specific terms needed) ive tried changing the resolution and making full screen. Nothing changes. running xiphos 4.2.0 and ubuntu 20.04.1 lts. Thank you for your help!

**Comment by LAfricain** [comment]
Yes your bug is relevant, I have the same during the first opening. Just move the right line and wide the window.

**Comment by karlkleinpaste** [comment]
on some systems, and it is inconsistent from what i've seen, initial window size is smaller or the panes are below standard size. i don't know of any way to handle this, but all that's needed is to grab the individual pane borders and move them. also, simply grow the whole window, where simple proportionality will make them wider.

**Comment by gmtodd** [comment]
Thank  you very much guys!
