### ISSUE TITLE
Raspberry Pi Side Margin Glitch

### ISSUE THREAD

**Issue by kantst0p** [crosswire/xiphos#1055]
It seems to only partially show the margin on the left so that you are not able to see/read all the options/notes. It seems to be a border problem for the window, maybe it is because I have a square screen resolution and not the more common rectangular screen resolution?

**Comment by kantst0p** [comment]
![2020-08-13-224825_1280x1024_scrot](https://user-images.githubusercontent.com/67029537/90212326-ab8bac80-ddb8-11ea-9f59-1b03746f0bfe.png)
![2020-08-13-225928_1280x1024_scrot](https://user-images.githubusercontent.com/67029537/90212333-af1f3380-ddb8-11ea-8e9a-8ccb2fb14309.png)

**Comment by karlkleinpaste** [comment]
as for yesterday's just-closed #1054, this is a problem on some systems whose default values (driven by their gtk lib) start xiphos wrong. grab the pane borders and move them; they will be remembered. we have no idea how to control this, as it seems each distribution's gtk lib has slightly different behavior -- on my fedora31 system, initial start as a new user shows all the content without a problem.
![image](https://user-images.githubusercontent.com/7548920/90236077-4358bd00-ddf0-11ea-820e-b749ff2ac407.png)
