### ISSUE TITLE
Left part of side-bar cropped off

### ISSUE THREAD

**Issue by cworkman74** [crosswire/xiphos#1058]
Left part of side-bar is cropped off in Xiphos 4.2.1.

Fedora 33 pre-release
Xiphos 4.2.1 (gtk3 webkit2)
Gnome 3.38.0, Wayland
![Screenshot from 2020-09-21 14-40-47](https://user-images.githubusercontent.com/6200598/93807340-7c1e5a00-fc18-11ea-8dc1-c68de37563fe.png)

**Comment by karlkleinpaste** [comment]
#1054 #1055
