### ISSUE TITLE
No window dressing on Ubuntu Budgie 20.04

### ISSUE THREAD

**Issue by lxs602** [crosswire/xiphos#1062]
Hi,

When I open Xiphos on Ubuntu Budgie, it opens maximised and without any window borders or titlebar.

Using alt-space to bring up the window menu has greyed out options for 'Move' and 'Resize', though 'Minimize' is available.

The same problem does not happen when using xfce4 or gnome desktop environments.

Interestingly, if I switch to gnome and open Xiphos, and then switch back to budgie, xiphos runs normally, at least until I maximise the window or open another Xiphos subwindow, e.g. Preferences. After doing that, on closing and reopening Xiphos, the error returns.

Additionally, the problem does not happen when starting Xiphos as root.

I would attach some terminal output, but there is none at all.  I can post some debug output if you say what flags to use.

Would you have any idea what is wrong?

Thanks,

Luke

**Comment by karlkleinpaste** [comment]
first question is, where did you get it?
if you installed a "flatpak" or "appimage," please throw it out and get the right thing. those are invariably cursed.
see the note at https://github.com/crosswire/xiphos/releases/tag/4.2.1 and use the PPA.
fwiw, i have never seen any such behavior, as long as the desktop's window manager is functional, anyway.

**Comment by lxs602** [comment]
Ah, I don't know how I managed to post an issue without stating the version. I am using 4.2.1, from the PPA. 

I wasn't at all sure whether to post here, or to investigate it as a problem with gnome. There are no other applications affected. I have also posted to one of the general Linux boards.

**Comment by karlkleinpaste** [comment]
all i can say is that i have used current xiphos under recent gnome without incident on fedora.

**Comment by lxs602** [comment]
I couldn't reproduce it on a Budgie Live CD, so I think I have messed up the gnome settings. Thank you for replying.
