### ISSUE TITLE
Pointers please!

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [crosswire/xiphos#1063]
Hey there,

I'm trying package xiphos in GNU Guix, the functional package manager, and I have specified all dependencies (to my knowledge), but yet I end up getting this error about `dbus/dbus-glib.h` not being found. I do have `pkg-config` in the build environment too, which, I think, should have taken care of this.

Any pointers please?

[s0g5qhxhxcn2kpcynshj42zxpkvrj2-xiphos-4.2.1.drv.log.gz](https://github.com/crosswire/xiphos/files/5486867/s0g5qhxhxcn2kpcynshj42zxpkvrj2-xiphos-4.2.1.drv.log.gz)

**Comment by karlkleinpaste** [comment]
xiphos requires package dbus-glib-devel (as seen in fedora/rhel/centos) in order to compile the xiphos-nav interface. that includes /usr/include/dbus/dbus-1.0.

**Comment by peanutbutterandcrackers** [comment]
I do have all the necessary packages in the build environment.

It seems to me that this is an issue of the build looking for `dbus/dbus-glib.h` inside of `$INCLUDE_PATH`, but not finding it. As far as I know it, `pkg-config` should have handled it. But it isn't.

I don't know.

Is there anything in the logs that seems a bit suspicious?

By the way, thank you for Xiphos. It seems that you are the Xiphos maintainer. Super awesome!

**Comment by karlkleinpaste** [comment]
fedora's /usr/lib64/pkgconfig/dbus-glib-1.pc:

```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: dbus-glib
Description: GLib integration for the free desktop message bus
Version: 0.110
Requires: dbus-1 glib-2.0 gobject-2.0
Libs: -L${libdir} -ldbus-glib-1
Cflags: -I${includedir}/dbus-1.0
```

$includedir + dbus-1.0 contains a subdir dbus in which dbus-glib.h is present.

there is nothing further we can offer to debug this. it's not a xiphos error, it's a local build problem, and somehow apparently different from all the other platforms for which we routinely build (ubuntu/mint, fedora, arch, win32). feel free to add a comment for posterity's sake after you figure it out.

**Comment by peanutbutterandcrackers** [comment]
Certainly! Thanks!
