### ISSUE TITLE
Doesn't save settings

### ISSUE THREAD

**Issue by nDR01d** [crosswire/xiphos#1064]
Every time I load Xiphos 4.1.0 (gtk3 webkit2), I have to change nearly everything on the screen, from bible last used, font sizes, general layout, like no commentaries or books and the left column is always off screen and I need to widen the panel to see the bibles, commentaries etc. This is super annoying and makes it almost impossible to use.
![Screenshot from 2020-11-21 18-52-38](https://user-images.githubusercontent.com/51686635/99870946-e2305900-2c2a-11eb-87e7-04a895a912d7.png)
![Screenshot from 2020-11-21 18-51-45](https://user-images.githubusercontent.com/51686635/99870952-f1170b80-2c2a-11eb-9e9d-447f565dbd86.png)

**Comment by LAfricain** [comment]
How did you install xiphos? Did you use the ubuntu ppa?

**Comment by karlkleinpaste** [comment]
there exist rogue builds of xiphos as flatpaks and appimages. they don't work.
for ubuntu, go to the releases page and see the reference for PPA use.
current is 4.2.1.

**Comment by nDR01d** [comment]
I used the Linux Mint 20.04 flatpak. I uninstalled the flatpak and installed the Ubuntu ppa version 4.2.0 and so far no problems. Sorry, I just assumed that the flatpak version from Mint would work out of the box. Thank you Karlkleinpaste and LAfricain.
