### ISSUE TITLE
New Unicode Library

### ISSUE THREAD

**Issue by kreismit** [crosswire/xiphos#1067]
I've been using Xiphos without issues for a long time and it's really blessed me. However, this new issue is puzzling.

## Platform

OS: Arch Linux
Kernel: x86_64 Linux 5.9.14-arch1-1
X.org with Xfce 4.14

Xiphos version: 4.2.1-2, installed from AUR
`libbiblesync.so` 2.0.1-64

## Expected behavior

Calling `xiphos` with no options starts the program.

## Experienced behavior

First, I tried to run Xiphos and it didn't start. Here is the command-line output:

    tim@ginger: ~ $ xiphos
    xiphos: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory

So, realizing the library had been updated from version 67 to version 68 with the newest Arch `icu` package, I tried a symlink:

    /usr/lib/libicui18n.so.67 -> /usr/lib/libicui18n.so.68

This didn't work either, since the new version of `icu` has changed some definitions:

    tim@ginger: ~$ xiphos
    xiphos: symbol lookup error: xiphos: undefined symbol: ucol_open_67

Tried uninstalling and reinstalling from [Caleb's AUR repo](https://github.com/alerque/aur). No change.

To save you a search, `icu` is Arch's International Components for Unicode library. Current version is 68.2-1.

The same error was thrown when I ran `xiphos --help` or `xiphos --version`.

Is work being planned to move to the newest Unicode library?
Thanks!

**Comment by karlkleinpaste** [comment]
any build of xiphos links against whatever version of ICU libs is present on the build host. they are version-agnostic, as indicated by the contents of /usr/lib64/pkgconfig/icu.* referencing e.g. "Libs: -L${libdir} -licuuc -licudata".

you have a build dependency failure, where xiphos was not necessarily rebuilt for Arch when its supporting libs changed underneath.

nothing to be done about it but contact the build maintainer for xiphos on Arch and tell him/her to kick off a rebuild. that is, this is an Arch bug, not a xiphos bug.

quite a few people see these bug reports: who knows where Arch's official xiphos builds are managed?

**Comment by alerque** [comment]
As Karl said, this is a function of needing a rebuild after a recent ICU bump. Arch Linux core repos recently pushed out new ICU versions (and a bunch of other stuff). If you installed from the AUR using `yay` or a similar tool then doing a reinstall with the `--rebuild` option should clear this up. Note than the SWORD library also needs rebuilding.

I'll rebuild the Xiphos & Sword packages in the repo I host now (give it a few minutes from this message). In the future if there are issues with either Arch Linux packaging related to Bible stuff or with the repo that I host, feel free to open issues [on this repository](github.com/alerque/aur/).
