### ISSUE TITLE
The UI is shifted - the leftmost part is not visible

### ISSUE THREAD

**Issue by dkuteynikov** [crosswire/xiphos#1069]
Built the latest Xiphos from git, master branch, commit ece84a44111b790f242ef3aedb520bebd9e977a9
Ubuntu 20.04.1 LTS
As you can see from the screenshot, the left side of the user interface is not fully visible. Scaling/maximizing the window does not help: with any window size it will keep the same positioning of the widgets.

![window](https://user-images.githubusercontent.com/63711427/104855770-5b8cb500-5917-11eb-8bfa-697bdd148268.png)

**Comment by karlkleinpaste** [comment]
we have difficulties with some distros' gtk. bottom line is that on common platforms like fedora, it provides default sizes and boundaries just fine. the internal arrangement is adjustable, just grab the pane borders with the mouse and move them.
