### ISSUE TITLE
Failed to start Xiphos 4.2.1 in Win XP 32 bit

### ISSUE THREAD

**Issue by oxidian24** [crosswire/xiphos#1071]
Xiphos 4.2.1\bin\xiphos.exe
Cannot run the program. I got error like
entry point of procedure AcquireSRWLockExclusive does not exist KERNEL32.dll
On Windowx XP

**Comment by karlkleinpaste** [comment]
we explicitly abandoned support for XP several years ago. it's just too old, for exactly reasons that the main support libraries are missing major features found only in vista and later. we will probably leave vista behind soon -- nobody is using it anyway.

**Comment by oxidian24** [comment]
If I cannot use your program, may I have a question? Is there way how to get a file list of strong numbers in whole bible (in "KJV verses" format) assigned with morphology or (possibly also) with transliteration? I mean 31102 lines of verses exactly, where on every line all words are represented by number, morphology code and possibly pronunciation. I am working on bible translation and such list would be very helpful to a program which I want to do locate some special words like verb in jusiv in hifil.. I could not find such list so I look for somebody who can help me...

**Comment by alerque** [comment]
You are free to use the program. You could run *old* releases of Xiphos to match your OS, or use some OS from the last decade or so. You don't even have to shell out money for Windows. Any PC capable of running Windows XP can also run one of several available LiveCD systems (also from USB sticks) that have various Linux distributions which can run Xiphos just fine. These are free and faster than Windows XP on the same hardware.

There are also plenty of Strongs database dumps available online with the data you are looking for in various formats, but it's out of scope of this issue tracker to do the programming work to convert the data to the exact format you want.

**Comment by oxidian24** [comment]
Thank you. I have already found the database with strongs and morphology here:
https://github.com/openscriptures/morphhb
I have run and obtained some interesting data...
