### ISSUE TITLE
Failing to install Commentaries

### ISSUE THREAD

**Issue by Alfred-Samanga** [crosswire/xiphos#1077]
I am failing to install commentaries. I have tried on Adam Clarke, KD, and MHC.
It seems to be downloading files and then fails with the message "Install Failed".
I have managed to install Bibles and Dictionaries though.

I am running on Fedora 33.

I am not sure if someone can assist me.

**Comment by LAfricain** [comment]
I had exactly the same problem as you when the internet connection was not good. The commentary modules are big try when you are sure to have a good connection. In Africa maybe the night.

**Comment by Alfred-Samanga** [comment]
> I had exactly the same problem as you when the internet connection was not good. The commentary modules are big try when you are sure to have a good connection. In Africa maybe the night.

![Screenshot from 2021-02-12 04-52-09](https://user-images.githubusercontent.com/19703025/107725196-61936d00-6cee-11eb-813b-a0d4d3539954.png)

The download runs fast though. Above is an image showing my internet speed. I have managed to install other modules like images which are also quite large.
Let me try to reinstall.

**Comment by LAfricain** [comment]
Ok your internet is good (as mine) but sometimes I have also this issue. You can also find the module [here](http://crosswire.org/sword/modules/ModDisp.jsp?modType=Commentaries) and install it manually.
I'm not sure this a xiphos issue, but a sword one.

**Comment by Alfred-Samanga** [comment]
@LAfricain , Thank you very much for your assistance. I have managed to install the module manually by following your link. It worked well.

**Comment by LAfricain** [comment]
You welcome!
I just copy the aswer of Troy about the timeout, maybe it can help:
`The latest version of SWORD accepts new timeout parameters for installmgr. Have a look in your ~/.sword/InstallMgr/ folder for the configuration file and see if upping the timeout values helps. A benefit of lower timeout values (which the latest version of SWORD ships with by default) is that it skips more quickly repositories which are down or not available in your region. E.g., from Italy, the Xiphos repo blocks access so installmgr previously waited for a really long time before giving up.`

**Comment by Alfred-Samanga** [comment]
Okay thank you, I will update the timeout and try again.
