### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by gmparsley** [crosswire/xiphos#1087]
I have downloaded the program but how do I get it to work?

**Comment by karlkleinpaste** [comment]
i can only assume that you're in windows.
download the installer, run it, and it will do the work and leave an icon on your desktop. once you start it from that icon, it will proceed. there is a longstanding problem with windows, virtually impossible for us to debug, where the first (only the first) run of xiphos under windows will seem to hang for a while, but it will eventually break free and open the initial windows that offer to download a bible and proceed from there.

**Comment by LAfricain** [comment]
> virtually impossible for us to debug

Hi Karl, why is this impossible? I happy to know that you know this problem (even if I'm Linux user).

**Comment by gmparsley** [comment]
Thanks for your response. I'm using Ubuntu which was just loaded yesterday
and windows has been removed. I have downloaded the program but it will not
install. I've been digging and found that a PPA is needed, if that be true,
how do I find the PPA and install it? I'm not that versed those things, if
it's beyond "download" and then open I'm in strange waters :)

Thanks,
George

**Comment by LAfricain** [comment]
If you know French: https://doc.ubuntu-fr.org/xiphos
Or https://launchpad.net/~pkgcrosswire/+archive/ubuntu/ppa

**Comment by gmparsley** [comment]
I think I came across a YouTube tutorial for it, but it was in French. I do
good with English at times

**Comment by LAfricain** [comment]
Can you share the link of the tutorial?

**Comment by gmparsley** [comment]
I'll see if I can find it again, just kinda stumbled upon it.

**Comment by gmparsley** [comment]
https://youtu.be/cqB7WbuxouE

**Comment by gmparsley** [comment]
I found a Bible app in the software store. Didn't understand  what that was
all about but figured it out.

Thanks.

**Comment by LAfricain** [comment]
> I found a Bible app

Probably bibletime, but it's not difficult to add a ppa to your system.
