### ISSUE TITLE
Fonts reset after you close

### ISSUE THREAD

**Issue by faithwarriorsg** [crosswire/xiphos#1095]
Hi!
Newbie here. So perhaps I am doing something wrong, but, after I set the size and style of my fonts, I use the program. I close the program and all that works fine. The next time I open the program up, it is back to default settings and I have to redo it all ovr again. Every single time, I thought once you set it, it's done. Please help a newbie out. Also I am new to the open community, Ijust installed Elementry 6 and love it so much, a top contender in my book!

**Comment by karlkleinpaste** [comment]
you're using a flatpak or snap build of xiphos.

we see this from time to time. we don't know who builds this version, but it's not us, and it's misbuilt from the standpoint that it does not have self-identified access privs to settings storage.

you need to uninstall the version you've got and install a real, normal build. if you're on ubuntu, please see our releases page where you will find a reference to the PPA that's needed for ubuntu.

**Comment by faithwarriorsg** [comment]
That makes sense, except I downloaded from app store. I think the issue is I'm using the beta of v6, not the real one. I've done all I know how to do concerning upvrading(overwriting] to the new which I purchased. Please help in this. I've tried usb, dvd mediums and nothing is working.
The prerelease is actually downloading updates and everything and I can Stull use it, but I want the real version though. Bad thing is I cannot swap had, because nobody has eMMC. So I have to work with what I have.
Thanks for anything you can give.
Scott

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LAfricain** [comment]
Try with the ppa: https://launchpad.net/~pkgcrosswire/+archive/ubuntu/ppa
But I update it only for 20.04.

**Comment by faithwarriorsg** [comment]
Thank you so much sir, will try tonite.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by faithwarriorsg** [comment]
ok, so here's the deal. I am obviously very new to Linux based OS, I am using elementary 6 early release preview. I tried to uninstall it by purchasing the real, for some reason it won't allow me to. So, as previous threads have gone, and thank you so much for those who responded, I had used the store built in for Elementry 6 and that's where I got Xiphos. I try to reinstall it and this is what I get: Aborted due to failure (While trying to checkout e3970b5f6baaad547f0b444584ad4df750616c824f0ddbe38be6e49d63fd8b35 into /home/faithwarriorsg/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/3.34/.e3970b5f6baaad547f0b444584ad4df750616c824f0ddbe38be6e49d63fd8b35-MD4NA1: Opening content object cff4fac8aefb9f7d05d9b56da7491bfdf0cd647edceb30dc90561978de79b765: Couldn't find file object 'cff4fac8aefb9f7d05d9b56da7491bfdf0cd647edceb30dc90561978de79b765')
Help!!! Please. I even went into terminal and it wasn't even in the list, even used the uninstall line,nothing found. I'm stuck. Thanks all for being awesome.

**Comment by LAfricain** [comment]
I don't know why your package manager tries to  install a flatpack, but you have to use the deb package in the debian repositories or from the ppa. Elementary OS 6 is ubuntu 20.04 based OS so use the ppa for FOCAL (20.04) please: https://launchpad.net/~pkgcrosswire/+archive/ubuntu/ppa

Try this for the removing of the xiphos flatpak: https://blog.softhints.com/how-to-completely-remove-flatpak-linux-mint/ or https://www.systutorials.com/docs/linux/man/1-flatpak-uninstall/

**Comment by faithwarriorsg** [comment]
Thank you so much. I will try and will let you know

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
