### ISSUE TITLE
Installation of commentaries fail

### ISSUE THREAD

**Issue by Teofilios** [crosswire/xiphos#1096]
Hello,

Installation of commentaries from Xiphos (such as John Gill's commentary or Chrystosome) fail using Xiphos or BibleTimes software.

Best regards,
Aleksandar

**Comment by Teofilios** [comment]
I forgot to mention that the Bible software I was using was Xiphos and BibleTimes for Linux Debian. Version of BibleTimes 3.0.2.

**Comment by LAfricain** [comment]
Sometimes if you have a slow internet connexion, it can prevent the installation. Is your connexion slow?

**Comment by Teofilios** [comment]
My connection is not slow. I have really fast net connection.

**Comment by Teofilios** [comment]
I have installed almost all modules of interest except those from Xiphos server. I have no trouble to download and install from Bible.org, CrossWire, Lockman Foundation and eBible.org. But modules from Xiphos always fail. It seems that it is something wrong with Xiphos.

**Comment by LAfricain** [comment]
Ok now it's most clear. Maybe the xiphos server is down. Which module are you looking for?

**Comment by Teofilios** [comment]
John Gill's Expository, Chrysostome and Vine's Expository Dictionary

**Comment by Teofilios** [comment]
Hello again,

I have managed at last to install the works in question! Now I am a very happy man! :-)

Thanks for follwoing up this issue.

Kind regards,
Aleksandar

**Comment by Teofilios** [comment]
Hello again,

There is still a problem to download/install modules from Xiphos. I have tried to install following modules without success: EarlyFathers (Books section), BibleArtBW, DoreWoodcuts and DoreWoodcutsCom (Maps and Images section). I had also problem with other modules but installed them after retrying the installation after three or four times.

Best regards,
Aleksandar
