### ISSUE TITLE
PorBiblia module irregularities

### ISSUE THREAD

**Issue by ldutra** [crosswire/xiphos#1100]
Sorry if this is not the right place to note this, but the PorBiblia module is highly irregular.  Its description refers to pages that do not exist anymore, to an association that as far as I could research never existed; it is actually under copyrights by the Imprensa bíblica brasileira, da Junta de educação religiosa e publicações da Convenção batista brasileira, under the name of Versão revisada de acordo com os melhores textos.  This same text has already been considered several times under several other false names, and rejected, by Crosswire.  This time it is worse, not only because the metadata is even more flagrantly wrong, but also because it is a very truncated text, with not only all diacritical signs (´, `, ~, ç, ^) missing, but also several letters, words, sentences and even several verses missing.  Please remove it.

**Comment by karlkleinpaste** [comment]
i looked into it briefly. i don't even know for sure where that module came from or what its provenance is. i've simply pulled it from distribution.

**Comment by ldutra** [comment]
Thanks a lot!

**Comment by LAfricain** [comment]
I think this issue can be closed.
