### ISSUE TITLE
PPA on Ubuntu is Offline

### ISSUE THREAD

**Issue by TomatDividedBy0** [crosswire/xiphos#1101]
It doesn't seem like maintenance of this is regular and it seems as per the documentation, there's some issues with Ubuntu and dependencies. I think it'll prove easier in the long-term to package it as an AppImage or a Flatpak so it'll work across distributions and versions of said distributions with minimal intervention. 

As it stands, currently the PPA is returning 404 errors, and even if it was online, it's not up to date for the proper Ubuntu versions.

**Comment by alerque** [comment]
AppImage and Flatback are both their own can of worms with upsides and downsides. They are not a cross-distribution panacea. If you have a case to make for them you can open that as a separate issue here, but I suggest not mixing that up with a friendly poke on the PPA issue.

I think the two semi-active PPA packages are myself and @LAfricain. I don't use Ubuntu at all except to help some people out with getting access to packages they can't reasonable compile themselves. I sometimes get around to going through and freshening up some Ubuntu stuff, sometimes (like now) I'm buried deep in other projects on distros I actually use. I believe @LAfricain actually *uses* Ubuntu and may be the best bet to give it a poke.

I doubt it is actually offline — that would mean probably only be true if every PPA hosted by Launchpad was offline. More likely you're just trying to fetch packages for a new distro release that doesn't have packages specifically posted for it yet.

**Comment by LAfricain** [comment]
Hello,

> As it stands, currently the PPA is returning 404 errors

What do you mean with offline? Wich version of Ubuntu are you using? The ppa is only for 20.04, for later version, the official ubuntu repo are enough for the xiphos package, and it is the last version.

**Comment by LAfricain** [comment]
This issue is unrelevant, it can be closed.
