### ISSUE TITLE
Module Manager - Load the Master Repositories List from CrossWire server?

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#1114]
The Xiphos **Module Manager** should include a button to load/reload the **Master Repositories List** from the CrossWire server.

I just installed Xiphos for Windows 64 on a new PC and there is no means to do this.

Isn't this what the **Load Standard** button was supposed to do?
NB. On the fresh install, there's no such button!

**Comment by DavidHaslam** [comment]
@LAfricain - is this the improvement you're after?

**Comment by DavidHaslam** [comment]
Ah - the **MRL** only appeared after I had installed a module!
The **Load Standard** button is now available.

**Comment by LAfricain** [comment]
Not exactly. With bibletime, you can select multiple repositories together, after that the list of module proposes all the module of all the repositories selected.
![repo](https://user-images.githubusercontent.com/19690477/181461996-86237444-7408-4d9f-ac66-82950c731842.png)
![list-of-languages](https://user-images.githubusercontent.com/19690477/181462356-8d56d77e-d195-4751-bfec-d55beb0426a7.png)
