### ISSUE TITLE
Xiphos 4.2.1.7 crashes whenever I open it 

### ISSUE THREAD

**Issue by chriswadams** [crosswire/xiphos#1117]
Every time I try to open Xiphos 4.2.1.7, on openSuSe Leap 15.4, it crashes with the following error message:

[CODE]BUG! Xiphos is about to crash due to a "STRDUP" error.
Please report this error to the Xiphos team with:

/home/abuild/BUILD/xiphos-4.2.1.7/src/main/display.cc:1067 "<b>%s %s</b><br/>
'[/CODE]

This appears to be the same problem as issue #523, closed Feb 29, 2016. In the thread for that issue, Karl Kleinpaste wrote: "the specific bug mentioned here was actually fixed long ago and that fix is already present in 4.0.0. but testing for your report uncovered another bug, a sort of ancillary bug, which has now also been fixed, and will be part of our next release."

I've tried updating both SuSe and Xiphos, but the crashes still happen. Karl also mentioned that there are builds for Ubuntu and Fedora, but nothing specifically for SuSe. I could try changing my OS to one of those two, if that's my only option, but I'd like to know if there are other possibilities before going down that road. Any help would be appreciated.

Thanks!
-chriswadams

**Comment by Crissium** [comment]
Actually I can recall that years ago when I was on Leap 15.2 (?), something similar happened to me.

I created a list of parallel modules, and when I restarted, I got the same error. Then I removed all xiphos config files (not necessarily deleted, just moved away) and it started up without error again.

Hope this can help you.

**Comment by chriswadams** [comment]
Success! Thank-you for the advice, Crissium!
