### ISSUE TITLE
How to add other books/sermons to it? 

### ISSUE THREAD

**Issue by passionate2023** [crosswire/xiphos#1121]
Hi,

How to add other books/sermons to it?

Thanks

**Comment by LAfricain** [comment]
What exactly do you want? You can add all modules (books, commentaries, dictionaries) with the module manager.
If you have other works you need to create a module.

**Comment by LAfricain** [comment]
It's not the place here, you can write me personally. I will help you.
But can you list the book and dictionary you want to use?
Very quickly, you have to convert your books to osis format, your dictionary to TEI format. Then use the sword tools to build the modules.
You can find documentation here: https://wiki.crosswire.org/Main_Page
and for books: https://wiki.crosswire.org/OSIS_Genbooks
For commentaries: https://wiki.crosswire.org/OSIS_Commentaries
For dictionaries: https://wiki.crosswire.org/TEI_Dictionaries

For commentaries, I prefer to work first with the [usfm](https://ubsicap.github.io/usfm/) format and then convert the files to osis with [u2o.py](https://github.com/adyeths/u2o).

**Comment by LAfricain** [comment]
Please write an email to sword module list: modules@crosswire.org I will answer you.

**Comment by LAfricain** [comment]
@karlkleinpaste this issue can be closed.
