### ISSUE TITLE
Left edge of Xiphos cut off, can't see first few letters at left side. ZorinOS 15

### ISSUE THREAD

**Issue by mrdovie47** [crosswire/xiphos#1126]
When doing a search the first two letters are cut off. The whole page is cut off on the left side.  Page is shifted past the border.
I will try another font size other than default.

**Comment by mrdovie47** [comment]
My column on the left was too compressed, cutting off the left side. Widened column and OK.

**Comment by LAfricain** [comment]
Please close the issue. Thank you.
