### ISSUE TITLE
Display error running on Debian 12 in the Gnome Desktop Enviorment

### ISSUE THREAD

**Issue by mttyhw** [crosswire/xiphos#1128]
![Exampleofbug](https://github.com/crosswire/xiphos/assets/142174462/39523319-0738-451d-8904-2017d72be8bb)

I am unable to see the full display of the sidebar.  Even if I downsize the window I am unable to see the entire sidebar.  I am running Debian 12 in the GNOME Desktop Enviorment.

**Comment by LAfricain** [comment]
See #1126
