### ISSUE TITLE
Can't build fast search index when using sword-text-kjv

### ISSUE THREAD

**Issue by toazd** [crosswire/xiphos#1135]
I installed xiphos with sword-text-kjv and festival and if I try to build the search index in maintenance it finishes with no error or warning. Then, if I go to do an advanced search I get the warning that no fast search index exists. I didn't have this problem when the sword text was installed to ~/.sword (ie. downloaded by xiphos or another app that supports the sword project).

Platform is kubuntu 22.04.3

```
$ dpkg -L sword-text-kjv
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/sword-text-kjv
/usr/share/doc/sword-text-kjv/changelog.Debian.gz
/usr/share/doc/sword-text-kjv/copyright
/usr/share/sword
/usr/share/sword/mods.d
/usr/share/sword/mods.d/engKJV2006eb.conf
/usr/share/sword/modules
/usr/share/sword/modules/texts
/usr/share/sword/modules/texts/ztext
/usr/share/sword/modules/texts/ztext/engKJV2006eb
/usr/share/sword/modules/texts/ztext/engKJV2006eb/nt.bzs
/usr/share/sword/modules/texts/ztext/engKJV2006eb/nt.bzv
/usr/share/sword/modules/texts/ztext/engKJV2006eb/nt.bzz
/usr/share/sword/modules/texts/ztext/engKJV2006eb/ot.bzs
/usr/share/sword/modules/texts/ztext/engKJV2006eb/ot.bzv
/usr/share/sword/modules/texts/ztext/engKJV2006eb/ot.bzz
```

**Comment by greg-hellings** [comment]
This is not a Xiphos bug. This is a bug in Kubuntu packaging. They should not ever package those resources and especially not for installation into a global location. You won't be able to create indexes except as super user. Please report this as a bug to (K)Ubuntu and ask them to remove that package. Installation using anything other than the module manager is not supported.

**Comment by LAfricain** [comment]
It's a debian bug, because the package comes from debian.
