### ISSUE TITLE
Xiphos STRING bug

### ISSUE THREAD

**Issue by HnkGitHub** [crosswire/xiphos#1146]
Having issues running Xiphos 4.2.1 on Windows 10 Pro.

Xiphos starts but reports an error message which I've taking a screenshot of and attached
![xiphosstringbug](https://github.com/crosswire/xiphos/assets/38794884/ca663231-1cd0-4922-a93c-1d33ffa0ef56)

**Comment by karlkleinpaste** [comment]
i've implemented a fix (workaround) which i will push when i again have a non-firewalled environment, in about 5 days -- i'm out of the country right now and my network access is restricted.
i hope to put out a new xiphos release relatively soon.

that said, i am thoroughly mystified as to how you managed to trip that particular instance -- those color selections are among the earliest items to be set during initialization. do you have an old ".xiphos" directory lying around, with a questionable or dodgy settings.xml?

**Comment by HnkGitHub** [comment]
It may have been a security update from Microsoft that triggered it. 

I set up a user to run without Administrator privileges. If I run Xiphos using Runas Administrator, the problem disappears. If I run Xiphos as a non Admin, it repeatedly causes the same error without fail.. 

Most Windows 10 users are running as Administrator. I don't. Microsoft says it's better to run as non Admin. Like Linux. Windows lets you run things but warns an Administrator when he is taking action that requires Administrative access.

**Comment by karlkleinpaste** [comment]
i suspect that what's happened to you is that settings.xml was detected but found unreadable because the non-admin user has inadequate privs.

if you nuke your old .xiphos directory and start again, or copy its content in a read/writable manner, or just alter its privileged access, i suspect it will work. that said, the workaround is suitable anyhow, and has just been pushed.

**Comment by HnkGitHub** [comment]
Why does the user have inadequate privileges?

Yes, it's true Windows requires Administrator privileges to install a program, but a non admin should be able to run the program without crashing.

The installer should give the User the option to install for all users as opposed to just one with an Administrator account.  I don't see that option being given the user on install—unless I've missed something.

That being said, the program appears to be running some code that an Administrator account user could handle, but not a non-Admin.  Typically, Microsoft recommends that when this is the case, the code should catch that situation and request an  Administrator sign in to execute that particular section of code.

I renamed the %APPDATA%\Sword folder to see if Xiphos could work around the bug, but that didn't help.


________________________________

**Comment by karlkleinpaste** [comment]
the Sword directory contains module content for any app, not xiphos' specific data, like settings.xml.

i had thought that, running with reduced privs as a non-admin, general (esp. write) access to files like .xiphos/settings.xml would be insufficient. perhaps not; i'm not a windows guy at all.

**Comment by HnkGitHub** [comment]
There are different application data folders. Some are used for all users. These, I think, would require Admin privileges to change. And then there is the User's application data folder.

I believe your module installer gives the option to install modules in the user's application data folder. And possibly the error comes from the program trying to read a file that does not exist since it was installed by a non admin user, using an Admin account permission to install Xiphos.

I'm not sure, but I think Xiphos is trying to read configuration files from an application data file that is not located in a personal application data file. All configuration files that are referenced should be from the current user's application data folder where he has read/write/change properties. And if the program saves configuration properties it should be in the User's application data folder, not in all users.

There's a bunch of what is called Special Folders that Microsoft has appointed for various purposes.
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://albao.wordpress.com/2011/02/22/constant-special-item-id-list-windows-special-folders/&ved=2ahUKEwiH_IvAxbGGAxW7PUQIHQYKAbYQFnoECCgQAQ&usg=AOvVaw2-YuQ7yduD6Pp00M4oER7f
________________________________
