### ISSUE TITLE
Please ask about the problem that Deepin Linux, Xiphos software cannot display the content of the scriptures

### ISSUE THREAD

**Issue by paloffice** [crosswire/xiphos#1148]
I use a linux version released in Chinese mainland, deepin linux V23RC, this version of the image source does not have xiphos software, but its earlier version of deepin linux 20.9 contains, I use deepin Linux20.9 version of the image source is normal to open the software and add the Bible module after installing xiphot, but when reading, the content of the scriptures cannot be displayed in the reading interface, and the reading box is blank. My English is not very good, I don't know if you can understand this, please give some tips for operation, thank you!

**Comment by karlkleinpaste** [comment]
there is a regression in recent WebKit, which is the toolkit that drives text display in widgets, that causes text display failure in nvidia GPU environments. for the time being, use
`export WEBKIT_DISABLE_COMPOSITING_MODE=1`
to avoid WK trying to do too much work.

there is a fix in place to set this internally within xiphos, and i hope to put out a release sometime soon.
