### ISSUE TITLE
Escape key doesn't properly close the Options dialog

### ISSUE THREAD

**Issue by nwalkewicz** [crosswire/xiphos#1154]
Pressing <kbd>Esc</kbd> while in the Options dialog closes it in the UI, but prevents the dialog from being opened again until Xiphos is reopened. When Xiphos is reopened after this point, the dialog is automatically opened again, as if it was only hidden initially instead of being fully closed.

**Comment by Phyrik** [comment]
I've proposed a fix in #1168
