### ISSUE TITLE
Text is not visible in view panels in Linux Mint LMDE 6

### ISSUE THREAD

**Issue by stanbray** [crosswire/xiphos#1158]
Text is only visible if you try to drag it and disappears when you drop it.  Text is visible in other apps such as BibleTime. Have tried various font settings to no avail.

**Comment by karlkleinpaste** [comment]
until we get the next release out, set env.var before starting xiphos as done in [this change](https://github.com/crosswire/xiphos/commit/144a34150ce203fbe0f04b0bdd655d8b81e5a751).

**Comment by stanbray** [comment]
Thank you so much, that worked! From the command line in bash I executed:
export WEBKIT_DISABLE_COMPOSITING_MODE=1
Then started xiphos from the command line.
