### ISSUE TITLE
eom or eog for displaying maps, photos and the like

### ISSUE THREAD

**Issue by OrionRandD** [crosswire/xiphos#1176]
How do I configure Xiphos to open my maps (png, or jpg) images with eom (eye-of-mate) or eog(eye-of-gnome).
By default, it opens using the command-line display from ImageMagick package. Display is a great program to edit images... But, I do not want to open maps or images to edit them, but to only see them.
In the help menu, it says:

-----------------------

OPTIONS
Help Options:
-h, --help
Show help options

--help-all
Show all help options

--help-gtk
Show GTK+ Options

Application Options:
--display=DISPLAY
X display to use

-----------------------

And I have tried to open Xiphos in a terminal like so:

xiphos --display=eom
xiphos --display=EOM
xiphos --display=eog
xiphos --display=EOG

But, none of them work here  :(

**Comment by karlkleinpaste** [comment]
`--display` would be to set an X display to use, not to select an image display utility.

The sequence through which Xiphos currently goes is to try `gvfs-open`, `gnome-open`, and lastly `display`. `gvfs-open` may no longer exist; this code is quite old, and an update may be needed there. But I would be surprised if `gnome-open` is not present on your system.

`gnome-open` operates by using the preferred image display app you've defined. For me, a MATE user, that's `eom`, as defined via panel menus System → Preferences → Personal → Preferred Applications.

**Comment by OrionRandD** [comment]
> `--display` would be to set an X display to use, not to select an image display utility.
> 
> The sequence through which Xiphos currently goes is to try `gvfs-open`, `gnome-open`, and lastly `display`. `gvfs-open` may no longer exist; this code is quite old, and an update may be needed there. But I would be surprised if `gnome-open` is not present on your system.
> 
> `gnome-open` operates by using the preferred image display app you've defined. For me, a MATE user, that's `eom`, as defined via panel menus System → Preferences → Personal → Preferred Applications.

I do not use gnome, but XFCE4 and StumpWM
But, I do have eom in my Debian System.
I think Xiphos should have an option (in preferences, perhaps) for users to choose the image viewer of their likes, since maps and other images are so essential to Bible teaching and such...
Xfc4 mime-types here and as a default for jpeg, jpg, png, motly use eom or eog when they are present, but I cannot figure why Xiphos is still picking up display as its primarily choice...

**Comment by karlkleinpaste** [comment]
It's not dependent on GNOME usage itself; rather, merely making a proper query for what image viewer has been established by the user through desktop-specific preferences setting. If XFCE is freedesktop-standard adherent, then `gnome-open` should in principle be able to find your viewer, the same way that it does for me as a MATE user, by making a standard `dconf` query for a preferred app.

The fact that Xiphos is spawning `display` for you suggests to me that `gnome-open` is not in fact present on your machine. It is part of package libgnome (on Fedora, anyway) -- do you have it present in the first place? If you simply run `gnome-open /some/random/image/file.jpg`, what happens? How about using `xdg-open /some/random/image/file.jpg`?

**Comment by OrionRandD** [comment]
> It's not dependent on GNOME usage itself; rather, merely making a proper query for what image viewer has been established by the user through desktop-specific preferences setting. If XFCE is freedesktop-standard adherent, then `gnome-open` should in principle be able to find your viewer, the same way that it does for me as a MATE user, by making a standard `dconf` query for a preferred app.
> 
> The fact that Xiphos is spawning `display` for you suggests to me that `gnome-open` is not in fact present on your machine. It is part of package libgnome (on Fedora, anyway) -- do you have it present in the first place? If you simply run `gnome-open /some/random/image/file.jpg`, what happens? How about using `xdg-open /some/random/image/file.jpg`?

My viewer is eog (eye-of-gnome).
xdg-open $file.jpg 
opens it...

**Comment by karlkleinpaste** [comment]
The whole point here is that xiphos should, in principle, be finding your preferred image viewer based on desktop preferences.

You didn't say whether `gnome-open` did anything for you.

**Comment by OrionRandD** [comment]
> The whole point here is that xiphos should, in principle, be finding your preferred image viewer based on desktop preferences.
> 
> You didn't say whether `gnome-open` did anything for you.

gnone-open solomons_temple.jpg
bash: gnone-open: command not found

**Comment by karlkleinpaste** [comment]
On Fedora:
```
rpm -qf /usr/bin/gnome-open
libgnome-2.32.1-28.fc39.x86_64
```
I don't know what the equivalent package is in Debian/Ubuntu, sorry.

I will be making a change to replace the (outdated) `gvfs-open` with `xdg-open`, which should solve the problem as well. But if you can find where Debian makes `gnome-open` available, your problem will be solved in the most general way.

Or, as an indecent temporary hack...
```
sudo ln /usr/bin/xdg-open /usr/bin/gvfs-open
```
That is, make the outdated name `gvfs-open` work using `xdg-open`.

**Comment by OrionRandD** [comment]
> On Fedora:
> 
> ```
> rpm -qf /usr/bin/gnome-open
> libgnome-2.32.1-28.fc39.x86_64
> ```
> 
> I don't know what the equivalent package is in Debian/Ubuntu, sorry.
> 
> I will be making a change to replace the (outdated) `gvfs-open` with `xdg-open`, which should solve the problem as well. But if you can find where Debian makes `gnome-open` available, your problem will be solved in the most general way.
> 
> Or, as an indecent temporary hack...
> 
> ```
> sudo ln /usr/bin/xdg-open /usr/bin/gvfs-open
> ```
> 
> That is, make the outdated name `gvfs-open` work using `xdg-open`.

Thx a lot for taking my issue into considereation...
I will wait for the changes, though...
since xdg-open works well here when opening eog or eom...
I prefer not to make the hardlink, since I also have a softlink from xdg-open to open
Looking forward to seeing if your changes will help me here...

**Comment by LAfricain** [comment]
I have the same problem with ubuntu unity, the images on xiphos open with imagemagick and with eom for the system.
