### ISSUE TITLE
text not displaying

### ISSUE THREAD

**Issue by mnymonyker** [crosswire/xiphos#1177]
I cannot get text to display (see attached pic), I had this issue on an installation of MX Linux 23.3, and duplicated the issue on a fresh install of Debian 12.7.  I'm certain the modules are downloaded and have been through preferences and menu options.
[https://i.ibb.co/z8HLSx9/xiphos-no-text.png](url)
![xiphos-no-text](https://github.com/user-attachments/assets/5a8096ff-42d1-4cfd-a9c3-f0295be57203)

**Comment by karlkleinpaste** [comment]
You have an nvidia-enabled machine.

It's a known regression in WebKit, which is our HTML rendering library. WK people seem not interested in fixing this. We can't say why.

Until the next release, which should be within a month or two (I firmly hope), do this...
`export WEBKIT_DISABLE_COMPOSITING_MODE=1`
...before starting Xiphos from the command line. See [this change](https://github.com/crosswire/xiphos/commit/144a34150ce203fbe0f04b0bdd655d8b81e5a751).
