### ISSUE TITLE
About Downloading/Installing Xiphos

### ISSUE THREAD

**Issue by johnhenryhalljr** [crosswire/xiphos#1180]
Background

After looking at the download options and considering my circumstances, I want to get your suggestion on what I should do.

Question

It is my wish to get easy simple guidance on how to properly download Bible time onto one of my two computer devices.

The first computer device is an iPad. I have version 16.6.1 and it's a 7th generation.

The second computing device is a college desktop computer that is running windows. The problem is I not have administrator privileges and this must be overcome to use this device.

I am wondering if you have a portable version of the app that I could run from a USB possibly?

I would prefer to be able to use my iPad though; if I am able to.

Thanks for your consideration and your time.

John

**Comment by karlkleinpaste** [comment]
This repo is for Xiphos, not BibleTime.
Please see [their web site](https://bibletime.info/).
