### ISSUE TITLE
About Downloading/Installing Xiphos…

### ISSUE THREAD

**Issue by johnhenryhalljr** [crosswire/xiphos#1181]
After looking at the download options and considering my circumstances, I want to get your suggestion on what I should do.

Question

It is my wish to get easy simple guidance on how to properly download Xiphos time onto one of my two computer devices.

The first computer device is an iPad. I have version 16.6.1 and it's a 7th generation.

The second computing device is a college desktop computer that is running windows. The problem is I not have administrator privileges and this must be overcome to use this device.

I am wondering if you have a portable version of the app that I could run from a USB possibly?

I would prefer to be able to use my iPad though; if I am able to.

Thanks for your consideration and your time.

John

**Comment by greg-hellings** [comment]
Xiphos does not produce a portable version of the software. Neither does it build an iOS version at all. There are mobile apps built off the same sword library. You'll need to search the app store for them.

**Comment by johnhenryhalljr** [comment]
Thank you for your response, I not have access to a cell phone. I am only using an iPad. Just to be clear, are you communicating that my only option is a cell phone and that there is no option at all for available for the iPad?

Thank you for your time and consideration... Smile.

**Comment by greg-hellings** [comment]
I said nothing about phones. I don't know about the state of iOS/iPadOS/macOS software for SWORD, but neither BibleTime nor Xiphos supports it. Check your app store.

**Comment by johnhenryhalljr** [comment]
Hi Greg Hellings

Thanks again for your response.

When you spoke of mobile device, I took this to mean a mobile phone. I am
new to comprehending these things, and I still am doing my best to learn
and grow. Do you have any suggestions on types of search word search terms
that may be helpful for me to use in the App Store?

Thank you for your consideration and for your time,

John

**Comment by karlkleinpaste** [comment]
`[Sword Project apps for mobile devices.](https://www.crosswire.org/applications/?section=Handhelds)`

Your best option is PocketSword.

**Comment by johnhenryhalljr** [comment]
11/10/24

Hi Karl,

It's my intention to look 👀 into Pocket Sword as you have suggested.

Peace... Smile,

John
