### ISSUE TITLE
Using Fonts Whose Title Ends in a Number

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#524]
I cannot use the font "Goudy Bookletter 1911" in Xiphos. I'm guessing that it's because it ends in a number. When I choose "Goudy Bookletter 1911", the font that it sets instead is "Goudy Bookletter". If I edit the "~/.xiphos/fonts.conf" file directly and change "Font=Goudy Bookletter" to "Font=Goudy Bookletter 1911", it still does not work.

Reported by: greenraccoon23

Original Ticket: [gnomesword/bugs/525](https://sourceforge.net/p/gnomesword/bugs/525)

**Comment by karlkleinpaste** [comment]
the erroneous removal of digits as part of the name is fixed.
however, as surmised previously, there seems to be a flaw in webkit whereby it is not handling this font right at all.  i can trace xiphos and see that the full name including "1911" is what's stuffed into the widget. but the widget is not respecting this.  sorry, i have done what i can.
