### ISSUE TITLE
Studypad Outline Mode List Styling broken

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#536]
Ubuntu 14.04LTS
4.0.4 (gtk3 webkit1)
When using outline mode list-styling often doesn't work properly:
1. The outline mode should use the sequence I. A. 1. a. i. but it frequently doesn't or it will use it and then revert to using just numbers.
2. Continued use of the reduce indentation icon causes unpredictable behavior in the outline. Added spaces, loss of hierarchical styiling of levels.

This is what is in the studypad  generated file which is in error:
</i></div><div><i><br></i></div><div><ol class="L1"><li>WHO WHAT WHERE WHEN WHY?</li>**<ol>**<li>WHO?</li><ol class="L3"><li>Jairus</li><ol class="L4"><li>Synagogue leader (not a Rabbi, Scribe and probably not a Pharisee)</li><li>belonged to a group of men who administered a synagogue (board member)</li><li>The name Jairus means: "One Giving Light" or ("Jehovah Enlightens")</li></ol><li>the large crowd</li><li>Jesus</li><li>of course the disciples</li></ol><li>WHAT?</li>**<ol>**<li><br></li></ol></ol></ol></div>

Reported by: kellner-top

Original Ticket: [gnomesword/bugs/537](https://sourceforge.net/p/gnomesword/bugs/537)

**Comment by karlkleinpaste** [comment]
regrets, but the control over section prefixes is an artifact of the editor, which xiphos uses blindly. if bugs can be fixed in it, they will be reflected in future versions of xiphos.
