### ISSUE TITLE
Shortcuts don't work with non-Latin keyboard layout

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#538]
When Xiphos window is focused, and keyboard shortcut is switched to a non-Latin layout (Cyrillic in my case), shortcuts don't work. I use 64-bit build on Debian GNU/Linux. Shortcuts work in other GTK2 and GTK3 apps (though there's a history of a similar bug in GTK projects, see, for instance https://bugs.launchpad.net/unity/+bug/1226962
https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1246583
https://bugzilla.mozilla.org/show_bug.cgi?id=791175
https://bugzilla.mozilla.org/show_bug.cgi?id=69230)

Reported by: kosivantsov

Original Ticket: [gnomesword/bugs/539](https://sourceforge.net/p/gnomesword/bugs/539)

**Comment by karlkleinpaste** [comment]
i'm going to have to punt this.
the referenced bug reports show dozens upon dozens of comments, seldom reaching resolution, most still showing the bug present.
frankly, i don't see how i'm supposed to know how to map shortcuts to every non-latin keyboard. if there's a general solution to this problem, i'm all ears, but at the moment, i have no idea how i could begin to deal with this.
if there's something new, please open a new report.
