### ISSUE TITLE
Allow moving to previous/next verse by 'j' and 'k' keys

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#627]
Hitting C-n and C-p to change verses is hard, and my crappy keyboard doesn't register the control key on occasion, bumping my place.

I propose adding bindings 'j' and 'k' to move to the next and previous verse, respectively. Attached is a patch to do this.

Reported by: koenigdmj

Original Ticket: "gnomesword/bugs/89":https://sourceforge.net/p/gnomesword/bugs/89

**Comment by xtbqimuxmvtx** [comment]
Can this be modified by a user? I use colemak and would love to swap the two, so J is up and K is down... :)

**Comment by karlkleinpaste** [comment]
no, j/k are not re-assignable.

no keyboard distinguishes upper/lowercase control characters. 'n' and 'p' as 'next' and 'previous' are very standard concepts, and their use as control, plain, and uppercase is indicative of the metaphorical size of moving forward or backward.
