### ISSUE TITLE
module sync feature

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#687]
Either through private FTP creds, published file storage (SkyDrive, GoogleDocs, http webhost), external drive or local network.
It would be wonderful to be able to offer this feature to enhance the portability of this application.

Reported by: jgmeidal

Original Ticket: [gnomesword/bugs/149](https://sourceforge.net/p/gnomesword/bugs/149)

**Comment by karlkleinpaste** [comment]
the intended generality is so wide that i don't think we can seriously contemplate this.  as noted, DropBox and others are suitable repositories for such things; you can either set SWORD_PATH to that directory, or you can symlink ~/.sword to wherever in your e.g. DropBox space you've put things.
i just can't conceive of trying to pick the *one* method out of the dozens now available, and then just wait for all the complaints to come in saying, "oh you did it for [that method], surely you can do it for [this method] too." and in a matter of weeks i'll have 8 different desires for this.
nope nope nope nope nope, my masochism has limits.
this is properly solved outside xiphos using your favorite sharing method and either SWORD_PATH or symlinks. it's insensible to try to solve it within xiphos.
