### ISSUE TITLE
Add HTTP proxy or TOR support

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#700]
Is it possible to add HTTP proxy or TOR support so that people in persecuted countries can download modules anonymously? 

Reported by: jrockdub

Original Ticket: [gnomesword/bugs/162](https://sourceforge.net/p/gnomesword/bugs/162)

**Comment by ldutra** [comment]
Why was this closed?  Xiphos still cannot use proxies.

**Comment by gabrielmoura** [comment]
Please, I ask you to pay special attention to this function.

**Comment by ldutra** [comment]
Why no word on this so many years after?

**Comment by LAfricain** [comment]
We have a crucial need for developers...

**Comment by greg-hellings** [comment]
There is [elsewhere](https://github.com/crosswire/xiphos/issues/720) a duplicate bug for this. That is why there is no word on this particular issue. See in that bug the explanation for why this feature is not likely to be implemented in Xiphos.
