### ISSUE TITLE
Make the previous / next chapter areas klickable

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#739]
Chapter navigation ...

When you are in a specific chapter you can scroll up and down in that chapter. 
If you want to go to the previous or next chapter you can use the tiny arrows in the top menu.
These tiny arrows are "hard to point at" with the mouse this makes the navigation less fluent... Also you can click the verse number but also these figures are hard to locate.

A improvement could be:
If the area in the top where you can see the last verse of the previous chapter and the area in the bottom where you see the next chapter as a clickable area the navigation will be much improved.

Reported by: *anonymous

Original Ticket: [gnomesword/bugs/202](https://sourceforge.net/p/gnomesword/bugs/202)

**Comment by karlkleinpaste** [comment]
now text of the verse before/after can be clicked to induce cross-chapter nav.
