### ISSUE TITLE
Automated scrolling feature w speed control 

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#742]
I'd like to make a feature request.  An automated scrolling feature/option for chapter & verse.  Like a karaoke machine that scrolls words across the screen. This feature would scroll chapter and verse, and have a speed control.  Useful someone whos is handicaped or someone who has their hands tied with something and can't use the mouse at the moment, but still wants to continuing reading. Also, if you really wanted to get fancy, you could give people the ability to add their own background music to it.  

Thanks for a wonderful program.  

Reported by: *anonymous

Original Ticket: [gnomesword/bugs/206](https://sourceforge.net/p/gnomesword/bugs/206)

**Comment by karlkleinpaste** [comment]
i've thought about this, but frankly the concept simply violates too many assumptions about how the text widgets work.  sorry.

**Comment by LAfricain** [comment]
And a simple scroll (not auto) between the chapter? Without clicking on something to change chapter only with the mouse? Could it be possible? It's already possible in Bibletime, and in Andbible.
