### ISSUE TITLE
Use OPML file format for studypad

### ISSUE THREAD

**Issue by xiphos-bug-inhaler** [crosswire/xiphos#748]
I started using StudyPad a lot. I work in outline mode a lot. I realize that Xiphos uses html markup behind the scenes for studypad. While it creates almost web ready output which is a big plus, moving thoughts around seems to cause it to lose it's mind sometimes. OPML and an outline editor functionality would be just the ticket to provide the ability to rearrange thoughts while studying. OPML isn't that hard to put into html format later as an output option. OPML would also allow easily cutting sections of one study and pasting them into another.

Reported by: *anonymous

Original Ticket: [gnomesword/bugs/212](https://sourceforge.net/p/gnomesword/bugs/212)

**Comment by karlkleinpaste** [comment]
we are constrained by what the editor itself is capable of, and that means html. regrets.
