### ISSUE TITLE
Bible History

### ISSUE THREAD

**Issue by jman223** [crosswire/xiphos#750]
Bug

History data is lost for Bibles when closing and reopening Xiphos, but this data is not lost for Books or Dictionaries.

**Comment by karlkleinpaste** [comment]
history is per-invocation of xiphos, much as a browser's page history is per-invocation of the window or tab.

that's not a history for books and dicts, it's the selection of "nearby" entries.

**Comment by ildar** [comment]
Sorry to intrude, but
modern browsers have persistent history of each tab etc.
It's maybe worth thinking of the same feature for Bible readers, i.e.
Xiphos (and some others)
