### ISSUE TITLE
Bible Tab Issue Associated with Opening Session Files

### ISSUE THREAD

**Issue by jman223** [crosswire/xiphos#751]
Bug

Opening a session file, via the File menu, causes the contents of the Bible tab (always the first tab) to be blank.  To make the contents appear, you must click on another tab then click back to the first tab and the contents will then appear.

**Comment by karlkleinpaste** [comment]
i've experimented with this extensively and i just can't make it fail.  1st tab bible pane is always immediately filled.  closing provisionally as unreproducible.
