### ISSUE TITLE
WebKit2GTK+ Does not display properly under GTK 3.18 and GTK 3.20

### ISSUE THREAD

**Issue by cjbayliss** [crosswire/xiphos#756]
I have been playing with this a little, and it seems that it is the GTK versions that cause the issue, and not a WebKit2GTK+ issue. I haven't tried under GTK 3.16

**Comment by cjbayliss** [comment]
I spent a some time on this today, and can confirm that the problem is not WebKit2GTK, it seems to be related to how we pack the GTK widgets, maybe the XML GtkBuilder files are too depreciated for GTK 3.20?

**Comment by cjbayliss** [comment]
![Screen Shot of the problem](http://i.imgur.com/dKIM81l.png)

**Comment by cjbayliss** [comment]
So the problem seems to be related to the notebook tabs.

I can't work on this issue for about a month because I have used most of my internet.

**Comment by greg-hellings** [comment]
That screenshot matches what I have in Fedora now. I was forced to switch to GTK3 builds for upcoming packaging changes, and your screenshot matches what I and other Fedora users are seeing.

**Comment by creffett** [comment]
@greg-hellings did you find any solution for that? I'm trying to switch Gentoo to GTK3/webkit2 as well.

**Comment by pacho2** [comment]
Please note Fedora already moved to webkitgtk4 for 4.0.5 to get rid of obsolete/vulnerable webkitgtk versions

**Comment by karlkleinpaste** [comment]
fixed merged from 811.
