### ISSUE TITLE
Use CMake

### ISSUE THREAD

**Issue by ghost** [crosswire/xiphos#758]
The version of `waf` we are using relies on Python 2. Ubuntu, Arch Linux, and I think Fedora don't come with Python 2 by default anymore.

We could just update `waf` to a version that supports Python 3, but I think that is not a great idea. What happens when Python 4 comes out? Or just different version of Python 3? The Python guys seem to think that changing parts of a programming language is trivial for the devs using python. (BTW, I love Python, I just can see it's faults.)

If we use something like `cmake` or `make`, different versions won't be as big a deal. (Or so I suppose.)

**Comment by cjbayliss** [comment]
I renamed this to 'Use CMake' because the work has begun on the [cmake](https://github.com/crosswire/xiphos/tree/cmake) branch

**Comment by karlkleinpaste** [comment]
i would dearly love to leave waf behind. could we get some action on this, from those who know how it works?
we still have to support gtk2 (yes, because gtk3 is a disaster in windows) but happily we've lost some complexity recently from not needing to detect umpteen versions of HAVE_GTK_xyz.

**Comment by mcepl** [comment]
> The Python guys seem to think that changing parts of a programming language is trivial for the devs using python.

I don't like ``waf`` and it should be replaced (BTW, this has duplicate in #809), but this is a slander: Guido stated couple of times that no such disaster as py2k->py3k is going to happen, and the biggest trouble of that transition (``str`` as mess -> distinction between ``bytes`` and ``str``) should not happen any more.

**Comment by yetist** [comment]
Cmake ready now? On my archlinux, waf can't work today, we need to use cmake or meson as soon as possible to compile.

**Comment by karlkleinpaste** [comment]
last i heard from @domcorbex, there was still a need to handle win32-isms.

**Comment by domcorbex** [comment]
On Thu, 03 May 2018 05:03:51 -0700
Wu Xiaotian <notifications@github.com> wrote:

> Cmake ready now? On my archlinux, waf can't work today, we need to use cmake or meson as soon as possible to compile

Hoping to have completed the CMake port before the end of the week.
I have just a few small things left to fix.

Dom
-- 
dominique@corbex.org <dominique@corbex.org>

**Comment by karlkleinpaste** [comment]
handled via commit ec38ee8329ddbce061607c7adca83009a72eed58
huge thanx to dom
