### ISSUE TITLE
Add libttspico-utils for tts (for french)

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#762]
It will be very nice to add the possibility to do text to speech with libttspico-utils ([svox-pico](https://doc.ubuntu-fr.org/svoxpico)), as it's already possible on Android with AndBible.
Because presently it's not possible to do text to speech in french language with Festival. :(

**Comment by karlkleinpaste** [comment]
i've poked around a bit, to learn that libttspico is part of the pico tts. but it does not seem to be available in fedora.  at the moment, it appears to be specific to android and (oddly) raspberry pi, though your link to svox-pico also mentions debian.

unless it becomes a standard, readily-available package in other environments (notably, fedora & mingw), we can't pursue it much.

**Comment by LAfricain** [comment]
Ok I understand, I found this way :
https://raw.githubusercontent.com/stevenmirabito/asterisk-picotts/master/picotts-install.sh
? Maybe it's not an easy way to use it...
An other possibility is to propose  espeak?


2016-08-25 2:27 UTC+01:00, karl kleinpaste <notifications@github.com>:

**Comment by karlkleinpaste** [comment]
above all, i need packages that are universally available and workable with our platforms. festival is available everywhere, including win32.  espeak is not available in win32 at all, and frankly its sound quality sounds like the bad computer voice in the movie _war games_.  have we not progressed in speech synthesis in 30+ years?  not having functional prospects outside espeak, i'm going to have to close this unless something else comes along.
