### ISSUE TITLE
Xiphos can not read notes and references (solved)

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#763]
When I try to read notes nothing appears. Just the hand with the finger.  (see picture 1) : ![1_note_example](https://cloud.githubusercontent.com/assets/19690477/15722074/c9287a3c-2833-11e6-8b95-fa580a210528.png)
This is the content of the note from the osis file `:<note osisRef="Matt.1.6" osisID="Matt.1.6!1" n="1">Mambu ya Tamar ... ye 12.24.</note><verse eID="Matt.1.6"/>`
Similar problem with references, when I click on references xiphos send me to a bad place, always to Apocalypse 1:1  (see picture 2) :
![2 reference_example](https://cloud.githubusercontent.com/assets/19690477/15722259/be718f74-2834-11e6-8651-90313a75d18a.png)
This is the content of on of the references from the osis file : `<title type="parallel"><reference type="parallel">(Lc 6.20-26)</reference></title>`
The module where I saw this issues is konnym. But other personnal modules have the same problem.
`On AndBible (Android) the notes and the references are very good read.

.

**Comment by LAfricain** [comment]
I found a solution !!!
For the notes the problem was from the conf file. In my module conf file, I add the lines : `GlobalOptionFilter=OSISHeadings

GlobalOptionFilter=OSISFootnotes

GlobalOptionFilter=OSISScripref` and I could read the notes.

For references if I write like that `<title type="parallel"><reference osisRef="Lk.6.29-30">(Lc 6, 29-30)</reference></title>` I can access well to the reference to the preview window.

**Comment by karlkleinpaste** [comment]
*.conf content is not within xiphos' purview. if there are configuration problems that need to be solved generally, please see the bug tracker at crosswire.org.
