### ISSUE TITLE
mod.mgr crashes when refreshing list for first time on GTK 3.20

### ISSUE THREAD

**Issue by cjbayliss** [crosswire/xiphos#764]
System: Fedora 24 Beta

Trying a second time results in a crash after clicking `Install/Update`.

**Comment by cjbayliss** [comment]
Built like so:

```
rm -rf build/; ./waf configure --prefix=~/.local --gtk=3 --enable-webkit2; ./waf build; ./waf install
```

**Comment by cjbayliss** [comment]
It happens for GTK 3.20 regardless of WebKit version.

**Comment by karlkleinpaste** [comment]
i have upgraded to f24 at long last, and i have 3.20.9.  it does not crash for me.  do you still have this problem, or has an update to 3.20 since f24 release taken care of this?
