### ISSUE TITLE
Traditional Chinese localization not completed

### ISSUE THREAD

**Issue by threelegcat2015** [crosswire/xiphos#766]
I'm looking for the improvement of the translation but it seems that there are a few years since the last update of the translation. Should I start the translation based on the original one or to consult anyone before starting?

**Comment by karlkleinpaste** [comment]
please feel free to work from the existing .po files to make updates.  we'll be happy to merge in all improvements. our *.po are habitually out of date; convincing people to stay current has been impossible.

**Comment by threelegcat2015** [comment]
I've found that there are translation problems with the existing Traditional Chinese locale so I created my own translations, started from scratch using the English pot file. Now this is my tentative translation file, with about 90% translation progress.

**Comment by threelegcat2015** [comment]
I've found that there are translation problems with the existing Traditional Chinese locale so I created my own translations, started from scratch using the English pot file. Now this is my tentative translation file, with about 90% translation progress. Where could I upload the .po file and ask about specific questions with the remaining strings regarding to the translation issue?

**Comment by threelegcat2015** [comment]
I've installed 4.0.5 but the update .po created based on 4.0.4 still works. It is not complete but would be much better than the original. Here I upload the .po last updated on 25 Jul 2016:
[xiphos_zh_TW_20160725.zip](https://github.com/crosswire/xiphos/files/980657/xiphos_zh_TW_20160725.zip)

**Comment by karlkleinpaste** [comment]
apologies for not getting to this before 4.0.6.
what we need for integration is an updated *.po file. the *.mo you provided is the post-processing result of building the application.  if you can get us the *.po, i will integrate it for 4.0.7.

**Comment by threelegcat2015** [comment]
Here it is the .mo file!
[xiphos_zh_TW_20170827.zip](https://github.com/crosswire/xiphos/files/1254200/xiphos_zh_TW_20170827.zip)

**Comment by karlkleinpaste** [comment]
no.
you already offered the .mo.
what we need is the .po, from which the .mo is generated.

**Comment by threelegcat2015** [comment]
Sent again! I'm sorry that I usually mixed up the two unconsciously! LOL
[xiphos_zh_TW_20170828.zip](https://github.com/crosswire/xiphos/files/1254646/xiphos_zh_TW_20170828.zip)
I'd double-checked this one.

**Comment by karlkleinpaste** [comment]
merged. thank you very much.
