### ISSUE TITLE
xiphos 64-bit installer 4.0.4 installs on amd vista 32-bit OS, fails to run

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#767]
xiphos 64-bit installer 4.0.4 installs on amd vista 32-bit OS, fails to run. the exe installer needs 64-bit windows detection. see installer's man pages/docs.

**Comment by karlkleinpaste** [comment]
we're constrained by what NSIS provides; i'm not aware that NSIS does this.
i figure it's pretty much a "level zero" kind of user error to use the wrong architecture's installer, so i'm not going to worry about this.
