### ISSUE TITLE
installer comes up with firewall dialog and modules installer dlg

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#768]
installer comes up with firewall dialog and modules installer dialog concurrently/simultaneously, with the result of no modules listed only thing you can do is cancel/close. then it rebukes (bad day at the office?) "Xiphos: There are no Bibles installed. Evidently, you declined to install any. Without any Bible modules to display, Xiphos cannot proceed, and will now exit. [OK]"
xiphos 4.0.4 x64 installed first, didn't start, so installed xiphos 4.0.4 x32.
vista x32 amd 64 live.
started again and modules installer now properly downloads list of modules, before it did not.

**Comment by jmichae3** [comment]
how much is NET? why are prices not displayed?

**Comment by DavidHaslam** [comment]
Surely this is the case for all front-ends?

The price for the NET module isn't displayed by PocketSword either. 
The installer displays the full text of the About line. 

This is therefore more of a module issue. 

In theory, it would be feasible for the purchase price to be shown in the conf file. However a difficulty that bible.org might face is to account for inflation and price rises over time, as well as exchange rates for currencies other than $, etc. 

Please report this problem to the CrossWire issues tracker for MOD. 

Kind Regards

David Haslam
CrossWire volunteer
(not part of Xiphos devel)

**Comment by jmichae3** [comment]
the problem does look like it got fixed, because I have not seen this problem in 4.0.4, so I think this bug can be closed. but yes, the pricing is not shown. but since pricing seems to be an upcoming issue, I can report this in MOD. is this response regarding Net RE: some other bug number?

**Comment by DavidHaslam** [comment]
Pricing of encrypted modules with premium content is not a front-end or
back-end issue.
e.g. For the NET Bible with full notes.
It's entirely the responsibility of the original publisher, and the
right place for it is on their website.

Prices may change over time, so it would not be sensible to include the
price in a module .conf file.
It is therefore not even a module issue.

cf.  CrossWire is a non-income organisation.

David

**Comment by karlkleinpaste** [comment]
sword apps are not even aware of pricing.  sale of locked modules happens outside sword apps.
