### ISSUE TITLE
Traditional Chinese localization not completed(Re-post)

### ISSUE THREAD

**Issue by threelegcat2015** [crosswire/xiphos#769]
Sorry for that I've mistakenly deleted the issue I've made. I have started my translation from scratch using the English pot file (for there are translation problems with the existing Traditional Chinese file.) and now have made my own .po file with about 90% translation progress. Where should I upload this file and ask about questions regarding translation issues for the remaining strings?

**Comment by karlkleinpaste** [comment]
dup #766.

**Comment by karlkleinpaste** [comment]
dup #766
