### ISSUE TITLE
Module manager unusable, making xiphos unusable.

### ISSUE THREAD

**Issue by charlieb000** [crosswire/xiphos#770]
possible gui issue (trisquel) rather than xiphos issue. it is Xiphos, after trying again after doing what i said below and re-running it appeared to work - however... (see last sentence).

cant see category titles, can select and open the category to see bible titles (see image). If i manage to find one that I am willing to install, pressing install causes open categories to close (i think. all dissappears, just as is seen before and after clicking refresh) I then click close and i got the message saying that nothing is installed (perhaps there is a verify or some custimisation menu that is supposed to appear). And with nothing installed it refuses to work.

However, after opening the categores it all disappeared again....

![screenshot from 2016-10-02 09 42 30](https://cloud.githubusercontent.com/assets/7907515/19017658/c390e890-8885-11e6-93ed-824965496256.png)

**Comment by karlkleinpaste** [comment]
come on, we need a real report. basics, please: xiphos version? platform (windows/linux, version)?

**Comment by charlieb000** [comment]
trisquel 32bit v7 2014, Xiphos 3.1.5+dfsg1build3

**Comment by karlkleinpaste** [comment]
3.1.5 is ~3 years old. v4 became reality over a year ago, and current release is 4.0.4.  3.1.5 had many problems with incomplete gtk3 support, long since resolved. you need to upgrade.

**Comment by charlieb000** [comment]
I actually had recently installed trisquel, and that is how i acquired it.
I will have to find another way of getting it then.

**Comment by anoxymoron** [comment]
If this is still a problem for anyone - I ran into potentially the same issue, mine was GUI related. The Module Manager default sizing seems to hide the "add" column for actually selecting modules to install. In the OP screenshot, you can see the green checkmark column next to the "Installed" column. Try expanding the window or going full screen to see the "+" column that is hiding between those columns.

![screenshot_xiphos](https://cloud.githubusercontent.com/assets/7819436/20452487/0b2f257e-adc8-11e6-8d09-78cc25484013.png)

**Comment by karlkleinpaste** [comment]
Unless this is 4.0.4, I don't care. That symptom directly suggests 3.1.5. Nothing pre-v4 is interesting.
