### ISSUE TITLE
4.0.4 win 32 despite my book list got strange list instead

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#772]
I don't understand what the installer is doing. I was thinking breton thinking it was english, but i didn't check any of the dictionaries or glossaries but I got DBD (is that a real book for sale?), Daily, SME, and 2 other devotionals, breton (br_en) which might not be english, .
ERen_he
ERen_el

oh... I see. I got all the books from the sword project 1.5.11 (ISO 06082008) with some inet updates I performed. I wondered why the thing took so long. so the books are joined now between xiphos and sword.

**Comment by karlkleinpaste** [comment]
the intent is that all sword project apps share a common set of modules.  the search path for modules is part of the underlying sword lib that drives all such apps, possibly modified by the environment variable SWORD_PATH..

if you're dealing with "the installer," as opposed to xiphos' own module manager, accessed via Edit -> Preferences or just F2, then you are dealing with something outside xiphos.
