### ISSUE TITLE
status bar shows Romans 8:36 while buttons show Romans 8:28

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#773]
4.0.4 win 32. this is confusing. what's the status bar doing? is this in the manual?

**Comment by karlkleinpaste** [comment]
generally, you could try looking in the manual yourself.  section 3, interface.

assuming you mean the location bar plus selector pulldowns, we are aware of no instance where these can get out of sync, other than when typing something new into the location bar and haven't yet hit <enter>.  location and pulldowns beside it are tracked together, obviously.  if there's something deeper going on, at the least a screenshot is needed.

**Comment by karlkleinpaste** [comment]
correction, because github abuses angle brackets as originally typed.

...and haven't yet hit [enter].

**Comment by karlkleinpaste** [comment]
no further input
