### ISSUE TITLE
feature request: allow someone to change books for dictionary

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#776]
feature request: add "Book List" link next to book name link in lower right side window/panel of xiphos 4.0.4 windows 32. this would allow someone to change books. it could be in the same style and format as the current book name.

**Comment by karlkleinpaste** [comment]
i'm sorry, i don't understand what the intent of this is.  a book list is already provided in the selectors beside the location bar.

**Comment by karlkleinpaste** [comment]
no further input, and book changing is easily done out of the module list in side panel.
