### ISSUE TITLE
\n used instead of terminal standard \r\n in verse list export, etc

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#777]
in windows, verse list export as text file should render something with windowsd-compatible line endings and thus work in Notepad. but it does not. try regex search for \bclean\b
for example.
the lone \n characters show up as square boxes and text flow is awful, straight across with no breaks.
windows line endings use the old terminal defacto standards \r\n and so does dos. linux/mac uses \n by error and whole OS and libs, compiler should be redone from scratch with simple global search and replace.
old macs use \r only by error same here, but there is no way to go back with those, you just need dostounix or utod and dtou. these do not come with windows.

**Comment by DavidHaslam** [comment]
Use Notepad++ instead!

You can easily convert the EOLs.

It's one of the best Unicode text editors for Windows. 

It can even be set to open in place of Notepad. 

David

**Comment by DavidHaslam** [comment]
Use Notepad++ instead. Available from https://notepad-plus-plus.org/

It's one of the best Unicode text editors for Windows. It can be used as
a Notepad replacement.

You can readily convert EOLs from one style to another with the Edit |
EOL Conversion menu options.

David

PS. It was not an "error" that Unix and Mac have different EOL style
than DOS/Windows.
It was just a conscious design choice by the OS developers. Most
programmers just live with the fact.

**Comment by karlkleinpaste** [comment]
as david says, this is no error. first, unix-style line ending (\n) pre-dates DOS and windows, so by reasoning of de facto standard, it is windows that is in error, for this as well as the incredibly stupid use of '\' as path component delimiter -- just alarming in its short-sightedness. second, the concept of a line ending is just that, a concept and not a concrete display demand, and unix' (now linux') conceptual choice is a valuable single-character marker that is up to the display hardware/software of the moment to interpret on the fly. frankly, making a 2-char delimiter for the trivial issue of marking a line end has caused endless, pointless pain for programmers for a generation. old mac's use of \r instead is just another indication of NIH and not worth giving any attention at all.

the delivery of content within sword apps is always always always platform non-specific -- what if the user happens to export while running in win32 xiphos within a VM that is inside a linux system, and he's dropping the file into the host filesystem for perusal there? -- and there exist trivially-available tools such as david mentions to convert \n line endings to windows' erroneous \r\n line endings.
