### ISSUE TITLE
ftp is down, site is down

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#779]
I found my check with has you address on it.

**Comment by greg-hellings** [comment]
Yes, the site is down as the server is physically being moved today. When
the server has been relocated, things will return to normal.

**Comment by jmichae3** [comment]
has the Society address changed?

**Comment by greg-hellings** [comment]
Only the server's physical location due to a change of hosting provider.

**Comment by jmichae3** [comment]
KJV disappeared on me too.

**Comment by jmichae3** [comment]
how do we pay for a module?

**Comment by DavidHaslam** [comment]
Most modules are free. Only a small number are encrypted (locked). 

Which one are you asking about?

CrossWire is a non-income organisation. 

For an encrypted module the key to unlock it must be obtained from the copyright owner. Details will be in the conf file for the module. 

The CrossWire server status notice is posted in our Facebook page. 

David
