### ISSUE TITLE
Add support for ancillary configuration files to unlock modules from STEP Bible

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#783]
If you have **STEP Bible** installed on the same machine as Xiphos, then the specially licensed modules distributed by [Tyndale STEP](https://www.stepbible.org/) could be also opened with Xiphos. However, these modules are generally locked, with the unlock key stored _separately_ from the **mods.d** folder.

Such an _ancillary conf_ file is stored under the SWORD path in the **.\step\jsword-mods.d** folder.

The special conf file contents would be:
```
[modulename]
CipherKey=<theunlockkeyobtainedforthelockedmodule>
STEPLocked=true
```

Of course, it's feasible to manually open this file, copy the key, and enter it into the Xiphos dialog when prompted, yet it would be neat if this could be done behind the scenes if the unlock key has already come with the module from STEP Bible.

**Comment by dmsmith** [comment]
FYI. The lock key is also encrypted using a method that's not part of JSword. 

Cent from my fone so theer mite be tipos. ;)

**Comment by DavidHaslam** [comment]
It seems I may have stumbled upon one module that had been inadvertently distributed with a single unlock key rather than one that would only work with STEP Bible. 

Am in touch with STEP developers.

**Comment by karlkleinpaste** [comment]
there's been no new info re: STEP developers in the 15 months since this item was generated. do we have any reason to believe that any future information will be forthcoming? if not, i intend to close.

**Comment by DavidHaslam** [comment]
I've not had any additional information. 

This issue may be closed.
