### ISSUE TITLE
Xiphos Read aloud still reads the verse number even when these are hidden

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#787]
With **Show verse numbers** unticked, the **Read aloud** feature still reads the hidden verse number.

IMHO, the verse number should **not** be passed to the TTS engine when they are not shown on screen.

**Comment by karlkleinpaste** [comment]
fixed

**Comment by DavidHaslam** [comment]
Afterthought: (from a privaste email)

> Note that I believe it is much preferred to have separate view/hide controls for text and speak/mute controls for audio out - which is how I use my diatheke based tools. I prefer to keep headings and line numbers in view but not listen to them while listening and reading along.

Any further thoughts?
