### ISSUE TITLE
No italian localiazation in the options

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#789]
Hi,
I don't found the italian localization int the Preferences -> Options -> Langue différente
I'm using Ubuntu 16.04 xiphos in the repositories.
![xiphos_italian](https://cloud.githubusercontent.com/assets/19690477/23120606/4cd21534-f75d-11e6-8792-85d954aa3a66.png)

**Comment by karlkleinpaste** [comment]
no one has ever offered to translate xiphos' interface to italian.

**Comment by LAfricain** [comment]
Ok but the problem is first that the list of books can be modified to 
italian in bibletime (for instance) and not in Xiphos.
Maybe I can help to translate it in italian? Almost the most important.

**Comment by karlkleinpaste** [comment]
Help -> About Translation, click the link, and see the 2 refs to translation in your browser.
showing books in another language is dependent on the rest of the interface being available in that language.
you will need a tool like poedit in order to contribute a translation.
the first time someone does a translation to another language, I have been told that the effort is on the order of perhaps 6 hours. thereafter, keeping up with incremental textual changes to keep the translation current, the ongoing effort is minimal.

**Comment by LAfricain** [comment]
Ok translation is available on launchpad, and it's already begun to italian...

**Comment by LAfricain** [comment]
Ok now the translation is to 25%. I download the mo file, and I Had not the possibility to change the name of the books... I think it's really a bug because I have the possibility to chose Latvian and Korean and the translation is not so far as italian...
I don't understand the link between the gui translation and displaying the language of the books, because this depend of sword??
If I my system is in french for instance, the gui of xiphos is directly in french, but I can change the language of the bible books in English for instance. The gui will stay in french... But I can do this with italian because the proposition doesn't appeared.
You can see it very well on the first screenshot.

**Comment by domcorbex** [comment]
Hi l'Africain!

The po/LINGUAS file contains the list of available translations in Xiphos.
You have to add 'it' into po/LINGUAS in order to enable the Italian translation.

Blessings,
-- 
Dom
<dominique@corbex.org>

**Comment by LAfricain** [comment]
Hi Dom,
Thanks for the solution.
I never modify a file on github... I edit the file and I propose de the new. Is it the good way?

**Comment by domcorbex** [comment]
On Mon, 06 Mar 2017 00:30:33 -0800
LAfricain <notifications@github.com> wrote:

> I never modify a file on github... I edit the file and I propose de the new. Is it the good way?

Unless you have a large commit to apply, I guess both ways are ok.
-- 
dom <dominique@corbex.org>

**Comment by karlkleinpaste** [comment]
just closing this now -- italian translation was added 3 months ago.
