### ISSUE TITLE
On Xiphos 3.2.2, Debian Jessie, Edit/Preferences does nothing

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#790]
On Xiphos 3.2.2, Debian Jessie, Edit/Preferences does nothing. There is no response whatever.

**Comment by karlkleinpaste** [comment]
fixed eons ago. upgrade to 4.0.4.

**Comment by TomSullivanInUSA** [comment]
Karl:

Sorry, I am rather new to Linux (running Debian Jessie), but not without 
IT experience, having started programming the IBM360 mainframe (big 
iron) in 1972. About a year and half ago, I finally had it with 
Microsoft and switched to Linux. I taught myself Python since C# is 
basically a Microsoft language (and they recently bought out Mono, not 
that it was all that good). I have used C off and on for years.

Since I need to keep my system operational, I use Jessie (stable). There 
is no package for 4.0.4 available for Jessie, nor one available from 
jessie-backports. I am unwilling to risk instability by playing games 
with cross-version, "unauthorized" packages.

I downloaded, per your instructions, the source from Github, and 
attempted to build. Log is attached. But basically, I cannot find how to 
get xml2po, Gtk+3.20 (safely in Jessie), and do not understand the 
message "Package gconf-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gconf-2.0.pc'
to the PKG_CONFIG_PATH environment variable" as it is empty and I have 
the gconf-2.0 package installed. Much searching seems to only reveal 
useless or wrong info.

I then downloaded the tarball from SourceForge, but there is a Debian 
directory and a readme therein which references Debian testing (Jessie 
is stable).

Am I shot down without using Stretch (testing)? If not, a little help 
might get me started here.

Thanks for your time.

Tom



Tom@SullivanInUSA.com
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by domcorbex** [comment]
Tom,

I suggest you to build new Debian packages instead, it's a very automated process and it will ease your next migration to the soon been released Debian Stretch version:

#1 Prepare your system:
Install the needed packaging utilities
`# apt-get install dpkg-dev devscripts`
Add repositories for Debian source files, in order to so, edit /etc/apt.sources.list and add these lines:
`deb-src http://ftp.debian.org/debian unstable main contrib non-free`
`deb-src http://ftp.debian.org/debian testing main contrib non-free`
Refresh the package list
 `# apt-get update`

#2 You need to package biblesync first
Get source
`# apt-get source biblesync/testing`
Install dependencies
`# apt-get build-dep biblesync`
Build all biblesync packages
`# cd biblesync-1.1.2`
`# dpkg-buildpackage -rfakeroot -us -uc`
Install the 2 resulting packages
`# cd ..`
`# dpkg -i libbiblesync*.deb`

#3 Same process for packaging Xiphos
`# apt-get source xiphos/testing`
`# apt-get build-dep xiphos`
`# cd xiphos-4.0.4+dfsg1`
`# dpkg-buildpackage -rfakeroot -us -uc`
Install the resulting xiphos-data and xiphos packages, you're done.

**Comment by TomSullivanInUSA** [comment]
Dominique:

Thank you for taking the time to give such a detailed reply. I will try 
it out in a day or two.

Thanks again!

Tom

Tom@SullivanInUSA.com
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by karlkleinpaste** [comment]
just as an fyi, i would expect that ubuntu packages would install on any debian without a problem.

**Comment by TomSullivanInUSA** [comment]
Dominique:

Thank you again for your very detailed help. I bricked my system due to 
a typo, but restored nicely and the second time was perfect.

Were it not for the soon deprecation of Jessie, I would offer to make a 
script. Can still do that if you think it helpful - you have already 
done most of the work.

Very many thanks again.

Tom

Tom@SullivanInUSA.com
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by TomSullivanInUSA** [comment]
Karl:

Thanks to you and Dominique, it is up and running.

Very many thanks again.

Tom

Tom@SullivanInUSA.com
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.
