### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by rdanner3a** [crosswire/xiphos#795]
With the tools available, it should be relatively easy (perhaps using the Linux codebase?) to make an Android app. Have used Xiphos for years now on Linux Mint (since v12, possibly earlier) and an Android app would be very useful, especially if it shares features of the Linux build.

I appreciate your consideration!

**Comment by g4jc** [comment]
And-Bible project is for that purpose, and also uses the SWORD repository.

http://crosswire.org/applications/ --> https://mjdenham.github.io/and-bible/

Since Xiphos is currently programmed with desktops in mind, I think that's probably the best solution.

**Comment by karlkleinpaste** [comment]
the idea of completely replacing the display toolkit as "relatively easy" is kind of a joke. just keeping up with the upgrade treadmill of gtk3 and webkit2 is a nightmare. but this is marked as enhancement possibility in the future.

**Comment by DavidHaslam** [comment]
The **AndBible** app is now maintained at https://github.com/AndBible/and-bible

**Comment by DavidHaslam** [comment]
This issue should be closed as **Won’t fix**.
