### ISSUE TITLE
preview text offset offscreen when in sidebar

### ISSUE THREAD

**Issue by timsoftgit** [crosswire/xiphos#796]
with webkitgtk3 both xiphos 4.0.4 and 4.0.5 the preview window text is offset to the left out of the window (ie. the left edge is not visible) when shown in the sidebar (default settings).

I also noticed that the widget adjusting icon is wrong (ie. when moving mouse onto the border between different views, the resize icon shows the wrong direction (a vertical resize icon for a vertical separator and a horizontal resize for a horizontal separator) see screenshot to illustrate both bugs.
![xiphosbug1](https://cloud.githubusercontent.com/assets/7967099/25843523/7dd98aca-349f-11e7-9252-03e4cc5ef0df.png)
.

**Comment by karlkleinpaste** [comment]
the sidebar is resizable. mouse-grab the border between it and the bible pane. in initial config, the sidebar is fully visible, including the module tree's expansion icons (which are also hidden in your screenshot).

adjustment icons when pulling inter-pane borders are gtk standard things, and are dependent on which theme you're using. as i see them, i get double-sided arrows, properly oriented. perhaps your theme needs to be fixed.
