### ISSUE TITLE
xiphos crashes on windows 10  32 & 64

### ISSUE THREAD

**Issue by pierredejager** [crosswire/xiphos#801]
Xiphos do install on Windows 10. When you click on the icon it opens. When you tried click on add, to add a language, the whole program crashes and close.

**Comment by karlkleinpaste** [comment]
come on, far more detail needed.

which "the icon" do you mean, in what context?  the only "add language" kind of button present in xiphos is in the installer itself, to select the dialog language for install, and i've had no problem using that on several win10 machines.

if not the installer, where else do you mean by "the icon" to "add language"?

**Comment by pierredejager** [comment]
I cannot add Bilbles then it crashes, any way don't bother, I will not
use your program on windows10, only on linux  fedora. I rest my case.
You can close this query have a good day.

**Comment by mikhayahu** [comment]
I think I have the same issue. I'm running 64-bit Windows 10 Home 1703 (Build 15063.332) on a Ryzen 5 1600 CPU. I have tried installing both the 32-bit and 64-bit versions of Xiphos 4.0.5 (20170423). On first run, the module manager opens by default. Every time I try to refresh the crosswire sources the app crashes with a Windows error message "xiphos.exe has stopped working."

Here is the output of Event Viewer. Please let me know what else I can send you to help understand the issue. Thanks!

Faulting application name: xiphos.exe, version: 0.0.0.0, time stamp: 0xa178a170
Faulting module name: xiphos.exe, version: 0.0.0.0, time stamp: 0xa178a170
Exception code: 0xc0000005
Fault offset: 0x0000000000037615
Faulting process id: 0x36c
Faulting application start time: 0x01d2e250d787cc79
Faulting application path: C:\Program Files (x86)\CrossWire\Xiphos\bin\xiphos.exe
Faulting module path: C:\Program Files (x86)\CrossWire\Xiphos\bin\xiphos.exe
Report Id: acb90372-132d-46ae-b5db-21a6a75b1255
Faulting package full name: 
Faulting package-relative application ID:

**Comment by pierredejager** [comment]
Hi 

Thank you for your reply. Your explanation explained what happened to
me too. I am using windows 10 pro. Every time I want to add a Bible it
crashes as you described. After all I came right to install the Bibles.
I only read the Authorised KJV. 

I mostly use Linux fedora 26 beta with my email.

Many Thanks again. Please explained it to your college who work with
you.

Regards

Pierre

**Comment by mikhayahu** [comment]
I have the same issue on my laptop too. Also running 64-bit Windows 10 Home (1703), just on an i5-6200U CPU. Same behavior I mentioned above. App crashes every time I try to refresh sources from Crosswire in the module manager.

**Comment by alacham** [comment]
it happens also on Windows 7 Pro 64bit

crashes for retrieving repodata for crosswire and xiphos repositories; 
bible.org, ebible.org and IBT repos are OK

so maybe some unexpected data in these repos? Any idea how to debug it? Is there a way I can help with tracking it down (I have no experience with any development on Windows, though)

(funny thing is, that while I can download the bible modules in my Fedora but can't then actually use Xiphos properly (some gtk problem probably), I can't download it in Windows but once I copy it there from my Fedora it works alright there)

**Comment by pierredejager** [comment]
Hi 


Thank you for your reply, but my problem is solved.

Many Thanks

Pierre

**Comment by karlkleinpaste** [comment]
mod.mgr crash (notably for 1st-time user) fixed in 4.0.6a.

**Comment by pierredejager** [comment]
You closed a thread which I sorted out on my own without your
assistance.
It was time wasted for me to contact you.

**Comment by karlkleinpaste** [comment]
since you are so ingracious as to be rude about a bug report that was closed, i can hope only that by reading the bible you may learn something of the nature of grace.

the report was open and needed not to be. in light of having released 4.0.6a yesterday, it was (over)due for closure.

perhaps your time will not be so "wasted" by use of our program.
