### ISSUE TITLE
Slow Graphics and scattered display

### ISSUE THREAD

**Issue by donjajo** [crosswire/xiphos#802]
After switching to Fedora 25 from Debian 9, KDE updated in the process. Everything stopped working, on changing verse, it takes like 15sec to take effect. And I can't scroll, can't select Bible versions and dictionaries. Everything is just stiff

**Comment by donjajo** [comment]
And on installation, it said this:

> 
> warning: %post(xiphos-4.0.5-1.fc25.x86_64) scriptlet failed, exit status 2
> Non-fatal POSTIN scriptlet failure in rpm package xiphos
> Non-fatal POSTIN scriptlet failure in rpm package xiphos

**Comment by ildar** [comment]
You seem to have system problems unrelated to Xiphos. Please ask
Fedora-related forums instead

**Comment by donjajo** [comment]
All other apps are working fine. Only this

**Comment by ildar** [comment]
Anyway you'd better ask in Fedora bug tracker first

**Comment by greg-hellings** [comment]
This is already tracked both here and in Fedora. This is a duplicate.

**Comment by donjajo** [comment]
Sorry, where is it tracked?

**Comment by mhjacks** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1448623

I think the post-un failure is related to removing the alternatives in the transition from 4.0.4 to 4.0.5.

**Comment by karlkleinpaste** [comment]
we believe problems with webkit2 build (now req'd for f25/26) have rectified by the merge of 811. 4.0.6 will be released soon.
