### ISSUE TITLE
Error in required packages listed in INSTALL.md

### ISSUE THREAD

**Issue by justanenduser** [crosswire/xiphos#803]
I'm building from GitHub source (obtained today 06/27/2017) on Fedora 26. 

From your INSTALL.md file -

Now to compile the GTK3 version of Xiphos you need to make sure you have these
packages installed:

    $ sudo dnf install gcc-c++ intltool gtk3-devel dbus-glib-devel gtkhtml3-devel webkitgtk4-devel libxml2-devel libgsf-devel gconfmm26-devel sword-devel libuuid-devel gnome-doc-utils rarian rarian-compat biblesync-devel

With this file installed -

dnf install webkitgtk4-devel	(ver 2.16.4-1.fc26)
/usr/include/webkitgtk-4.0/webkit2/webkit2.h

This compile error is produced -

In file included from ../src/xiphos_html/xiphos_html.h:29:0,
                 from ../src/main/display.cc:44:
../src/webkit/wk-html.h:30:10: fatal error: webkit/webkit.h: No such file or directory
 #include <webkit/webkit.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

With this file installed (instead of the one listed above)-

dnf install webkitgtk3-devel		(ver 2.4.11-5.fc26)
/usr/include/webkitgtk-3.0/webkit/webkit.h

The compile is successful.

**Comment by justanenduser** [comment]
Apparently the wscript check for WebKit isn't successful as it reports -

Checking for GtkHTML Editor 4.0          : ok 
Checking for WebKit                      : fail 
Checking for pkg-config version >= 0.9.0 : ok 

even when the webkitgtk4-devel package is successfully installed.

**Comment by justanenduser** [comment]
Sigh... Looks like it's my mistake...
./waf --help showed me I needed to enable webkit2
It compiles and installs just fine but it exhibits significant delays in updating it's tabs and refuses to respond to mouse clicks on modules.

It does work properly with webkitgtk3 however. I see the previous reporter has given this same info and has been referred to the OS distribution involved, 

Thank you and my humble apologies.

**Comment by karlkleinpaste** [comment]
i believe all this (notably the failure to display panes properly etc) has been fixed by 811.
