### ISSUE TITLE
Change mouse hover behavior or make it configurable

### ISSUE THREAD

**Issue by dschilling** [crosswire/xiphos#805]
After I do a search, the search results appear in the verse list.  Then, as I am investigating each search result, I accidentally pass my mouse cursor over a cross reference link for a moment - which causes the cross references to appear in the verse list instead, losing my search results.  So then I have to re-run the search to get those results back, and find my place in the list again.  This happens repeatedly for every search I do.  It's like the text is filled with these land-mines where I have to be careful not to move my mouse.

Can we change the cross-reference behavior, or make it configurable, so that you have to click on them to view their verse list, instead of just hovering over them?

**Comment by karlkleinpaste** [comment]
configurable: in preferences -> general -> options, turn off "cross-references in verse list," then xrefs will appear in the previewer instead of the verse list.  they're still clickable there.

**Comment by dschilling** [comment]
Awesome.  Thank you so much!  That does the trick.
