### ISSUE TITLE
crash on windows 7 when removing bible module

### ISSUE THREAD

**Issue by alacham** [crosswire/xiphos#807]
xiphos hangs and crashes when attempting to remove bible module, after starting Xiphos again it seems to be removed alright; this also causes crash when attempting to update module to last version

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	xiphos.exe
  Application Version:	0.0.0.0
  Application Timestamp:	a178a170
  Fault Module Name:	StackHash_5c60
  Fault Module Version:	6.1.7601.23796
  Fault Module Timestamp:	590296ce
  Exception Code:	c0000374
  Exception Offset:	00000000000bf3e2
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1029
  Additional Information 1:	5c60
  Additional Information 2:	5c60d5dc21a8d286954f5cd22e0e44dd
  Additional Information 3:	cf3b
  Additional Information 4:	cf3bfd97c59f13a5b0343733c26d1a5f

**Comment by karlkleinpaste** [comment]
please, always always always report app version as well as platform.

in my win7 machine, i have never seen this failure, nor in win10.  if you can offer any kind of  additional context for investigation, it would be appreciated.  i simply have no handle to grab from this minimal report. apparently c0000374 is a "heap corruption" indicator but i've never such a thing in current xiphos (and seldom enough in years past).

**Comment by karlkleinpaste** [comment]
experimented some more, using yesterday's 4.0.6a release, on fedora and win7. i can't get it to crash on module deletion. unless i can get some more info on how/why the situation is different, i'll close this in a day or two.

it is more than slightly possible that yesterday's windows fix (viz. compiler error) has taken care of this problem.

**Comment by alacham** [comment]
hello, sorry I wasn't responding
I use Win 7 Pro x64, Sevice Pack 1 (maybe that could be reason? work laptop though); current version of Xiphos

The problem stays in 4.0.6a release too, but when I checked, it seems to happen only in 64bit version of Xiphos - 32bit is alright, so that can be used as workaround (speaking of versions, I noticed that regardless of app version, it always installs by default to C:\Program Files (x86) (sorry for nitpicking) )

Since 32bit version is ok, I guess you can close this (unless you know how I could get you some better debug info)

**Comment by karlkleinpaste** [comment]
release notes mention that the installer wants to mis-install 64-bit in (x86), suggesting it be manually corrected before letting it proceed. i can't figure out why this happens in our NSIS control file.

i will close this for now. i am suspicious about the 64-bit mingw libs for reasons like this.  but i can't fully justify my paranoia in a concrete fashion.
