### ISSUE TITLE
Using meson to build xiphos

### ISSUE THREAD

**Issue by yetist** [crosswire/xiphos#809]
Meson is a very bright build system, GNOME is switching to it, can xiphos support meson ?

http://mesonbuild.com/

**Comment by greg-hellings** [comment]
What would Xiphos "supporting" this mean?

**Comment by domcorbex** [comment]
Hi,

Why not, but someone already started to work on switching from Waf to
CMake, see the CMake branch on GitHub.

FYI: Using waf as build system is discouraged by Debian.
https://wiki.debian.org/UpstreamGuide#waf

dominique,
__
dominique@corbex.org

**Comment by yetist** [comment]
I'm going to try using meson to build Xiphos.

**Comment by domcorbex** [comment]
I've started a port of Xiphos to CMake, building on Linux is ok, (tested on Debian+Fedora) but not on Windows actually.
See my Gitlab repo: https://gitlab.com/domcox/xiphos-cmake/tree/master/

**Comment by karlkleinpaste** [comment]
in consideration that domcorbex has cmake integration well underway, and that cmake appears to be much more common/standard than meson, i'm closing this in favor of #758 reaching conclusion (apparently it just needs to support the windows build).
