### ISSUE TITLE
Xiphos 4.05

### ISSUE THREAD

**Issue by jadesoye** [crosswire/xiphos#810]
The commentary and dictionary panes are not showing, they are showing under the Bible text pane. Can someone fix this problem? Thanks
![screenshot from 2017-07-16 13-26-07](https://user-images.githubusercontent.com/30211719/28247547-8eecef08-6a2a-11e7-9c55-6c36af92b522.png)

**Comment by yetist** [comment]
I think this problem may be related to WebKit2GTK(libwebkit2gtk-4.0). It seems that GtkPaned didn't get the width of this widget, it seems that its width has been 0. Maybe should check the code in the src/webkit directory.

**Comment by jadesoye** [comment]
I'm using Fedora 26. There is no libwebkit2gtk-4.0 package in fedora 26. I installed webkitgtk3 but still the same problem. Any help to solve the problem is welcome. Thanks!

**Comment by yetist** [comment]
Please test #811 

![2017-07-27 16-12-03](https://user-images.githubusercontent.com/665058/28661204-844234fc-72e8-11e7-934c-1e1920c1b7ea.png)

**Comment by karlkleinpaste** [comment]
apologies for delay in handling, but it's fixed from 811 merge now.
