### ISSUE TITLE
update location for slackware build info

### ISSUE THREAD

**Issue by timsoftgit** [crosswire/xiphos#819]
hi Karl, under https://github.com/crosswire/xiphos/releases you have the slackware build info as being at
http://slackbuilds.org/repository/14.1/academic/xiphos/ 
can you update it to 
http://slackbuilds.org/repository/14.2/academic/xiphos/
to reflect the latest version of slackware (14.2)
(I have just submitted the 4.0.6 version to slackbuilds.org , so it should appear soon, once it has been approved)
many thanks, Tim

**Comment by karlkleinpaste** [comment]
done.
use 4.0.6a if you can. it adds a needed compiler flag to stop a mis-optimization. this *should* affect all platforms, though it has been seen only in windows, but i'm a paranoid soul.
