### ISSUE TITLE
Missing Package Ubuntu 17.04

### ISSUE THREAD

**Issue by OrdoFlammae** [crosswire/xiphos#820]
I am using Ubuntu 17.04. The package repositories do not have the following repositories, and I cannot build Xiphos without them. I have tried to find replacements for them, but cannot find any packages for a version of Ubuntu later than 14.

libgtkhtml3.14-dev,
libgtkhtml-editor-dev,
libgtkhtml-4.0-dev,
libgtkhtml-editor-4.0-dev

**Comment by greg-hellings** [comment]
Firstly, I'm not sure what we are expected to do about Ubuntu missing packages.

Secondly, have you tried building with the various WebKit-related options that waf provides?

**Comment by OrdoFlammae** [comment]
I have gotten the configuration process to work, and have sent a pull request updating the INSTALL.md.
