### ISSUE TITLE
Flatpak available on Flathub

### ISSUE THREAD

**Issue by nedrichards** [crosswire/xiphos#823]
I made a [flatpak](http://flatpak.org/) package for Xiphos and made it [available on Flathub](https://github.com/flathub/org.xiphos.Xiphos) for x86, x86-64, arm and aarch64. The purpose of Flatpak and Flathub is to enable developers to quickly and easily get software directly to their users, configured the way they want it so if any of the Xiphos developers would like to be added to the github repo, or take the flatpak configuration into the main Xiphos tree I'd be delighted to try and help.

**Comment by karlkleinpaste** [comment]
we appreciate the thought but, after discussing it with several others, we don't want to add yet another config file that needs to be maintained. we're happy to have it out there for other flatpak users and endlessOS and whatnot, but not something we wish to incorporate directly.

**Comment by nedrichards** [comment]
OK! Fair enough.

**Comment by mfreeman72** [comment]
@nedrichards Do you have any suggestions on how to get the Flatpak version to save its settings? Every time I start the program, it acts as if it's the first time running it. Window positions, which translation/verse is shown at the start, all preferences, etc. are reset to defaults every time, no matter what I set them to before.
