### ISSUE TITLE
Setting language to ru_RU fails

### ISSUE THREAD

**Issue by ildar** [crosswire/xiphos#825]
4.0.6 is failing to set Russian in settings. Could please anyone check?

**Comment by karlkleinpaste** [comment]
it seems to work fine, both by setting LC_ALL=ru_RU and by choosing it inside xiphos itself at preferences -> options.

![screenshot2](https://user-images.githubusercontent.com/7548920/30599634-168fd258-9d2b-11e7-8566-5e2e174a9708.png)
![screenshot1](https://user-images.githubusercontent.com/7548920/30599633-168ae19e-9d2b-11e7-867e-352597391083.png)

**Comment by karlkleinpaste** [comment]
i notice that there's an untranslated string in there, "open in advanced search." but that just means that po/ru.po needs some attention.

**Comment by ildar** [comment]
Hm, ok, thanks. Will dig into it next days.

**Comment by karlkleinpaste** [comment]
no indication here of an actual problem, so closing.

**Comment by ildar** [comment]
![shot-2018-05-23_16-58-33](https://user-images.githubusercontent.com/517752/40420715-06502ffe-5eab-11e8-885d-18313479d089.jpg)
:)

**Comment by karlkleinpaste** [comment]
considering that ru_RU works in a general sense, including that your screenshot shows russian interface details, i believe what you are seeing is an error in installation of sword. it expects to find suitable locale descriptions (to translate booknames etc) in /usr/share/sword/locales.d.

**Comment by ildar** [comment]
that's right, the issue solved. The installation wasn't complete. After
installing /usr/share/sword/locales.d files everything's fine
