### ISSUE TITLE
Some places were not localized

### ISSUE THREAD

**Issue by threelegcat2015** [crosswire/xiphos#827]
Here in the Rename Commentary dialog, the field "Name:" was already translated in the zh_TW .PO but the interface remains untranslated. The same case occurs in the Bookmark editing dialog where the translations for "Bookmark", "Bookmark name:", "Verse:" and "Module:" remain not shown. While in several places the "Cancel" and "OK" buttons were not translated. While in other places like "Insert Emoji" and "Downloading (x of x):"(as in the Module Management pane) provide nowhere to translate.

![2017-10-08 18-18-38](https://user-images.githubusercontent.com/13062920/31315915-260558aa-ac55-11e7-884b-df7ad3c567c8.png)

![2017-10-08 18-32-28](https://user-images.githubusercontent.com/13062920/31316022-1ef8fd12-ac57-11e7-8eb9-a540222edfb9.png)

![2017-10-06 19-07-21](https://user-images.githubusercontent.com/13062920/31315982-48bd7bd8-ac56-11e7-93df-16c0e72b7b08.png)

**Comment by karlkleinpaste** [comment]
fixed by domcorbex (thanx) in a87a6f.
