### ISSUE TITLE
UI problem in Windows edition of Xiphos 4.0.6a

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#829]
The **navigation controls** appear to have duplicate upwards buttons.

![screenshot 2017-10-12 21 00 27](https://user-images.githubusercontent.com/16325414/31516612-0cb10ffe-af91-11e7-9844-98b81c3a75fd.png)

NB. I reverted from Xiphos 4.0.7 because of issue #826

**Comment by LAfricain** [comment]
Same problem on Ubuntu.

**Comment by Nutster67** [comment]
This is very similar to an issue I have in **Xiphos.exe 4.0.7 (gtk2 webkit1)**.  When the application starts up and shows the up-down arrows for each book, chapter and verse selector with both the hovered and unhovered images.  Just moving the mouse over each of the buttons in question resets the buttons to normal appearance, with only one image for each button and they appear to behave normally, moving up and down through the books, chapters or verses, respectively.

![image](https://user-images.githubusercontent.com/35860186/35468815-94362d68-02f4-11e8-8de2-02a5997c1e72.png)

The initial appearance should only show the unhovered image.  Change to the hovered message in the appropriate Mouse_Over event handler.

**Comment by fredex1** [comment]
FWIW, I did a build locally (CentOS 7.<latest>) using rpmbuild, which built both a gtk3 and a gtk2 binary. BOTH of them exhibit this issue (as does the build from epel, that I had been using).

In my case, unlike David Haslam's screenshot above, both the up- and down-pointing spinners are doubled, until one slides the mouse pointer over them, then each one reverts to a single spinner as the mouse goes over it.

before touching with mouse:
![screenshot at 2018-03-11 13-28-27 1](https://user-images.githubusercontent.com/12013064/37256405-9d09e61a-2530-11e8-9117-43d010ac9362.jpg)

after touching one with mouse:
![screenshot at 2018-03-11 13-34-06 1](https://user-images.githubusercontent.com/12013064/37256439-17402d68-2531-11e8-9d30-a71f447c2160.jpg)

**Comment by karlkleinpaste** [comment]
fixed by merge of #877 and follow-on commit.
