### ISSUE TITLE
How to build Xiphos on Debian sid

### ISSUE THREAD

**Issue by teusbenschop** [crosswire/xiphos#832]
I don't know how to build Xiphos on Debian sid using the packages available from Debian sid.

Here are the steps taken:

1. Configure the package:
```
teus@debian-sid-gui:~/xiphos-4.0.7$ ./waf configure --prefix=/usr --gtk=3 --enable-webkit2
Linux detected 
Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Check for program gcc or cc              : /usr/bin/gcc 
Check for program msgfmt                 : /usr/bin/msgfmt 
Check for program intltool-merge         : /usr/bin/intltool-merge 
Checking for header locale.h             : ok 
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : not found 
Check for program xsltproc               : not found 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for libgtkhtml4                 : fail 
Checking for GtkHTML Editor 4.0          : fail 
/home/teus/xiphos-4.0.7/wscript:350: error: the configuration failed (see '/home/teus/xiphos-4.0.7/build/config.log')
```
It fails to find libgtkhtml4 and the GtkHTML Editor 4.0.

2. Search for the missing packages.
```
teus@debian-sid-gui:~/xiphos-4.0.7$ apt search gtkhtml
Sorting... Done
Full Text Search... Done
```
Debian sid does not provide packages with "gtkhtml" in their name.

3. Display the configuration log file.
```
teus@debian-sid-gui:~/xiphos-4.0.7$ cat build/config.log 
...
----------------------------------------
Checking for libgtkhtml4
pkg-config --errors-to-stdout --print-errors --modversion libgtkhtml-4.0
Package libgtkhtml-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgtkhtml-4.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgtkhtml-4.0' found
fail

----------------------------------------
Checking for GtkHTML Editor 4.0
pkg-config --errors-to-stdout --print-errors --modversion gtkhtml-editor-4.0
Package gtkhtml-editor-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtkhtml-editor-4.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtkhtml-editor-4.0' found
fail

```

The issue is: How to build Xiphos on Debian sid, using the packages available from sid?

The reason for this question is that I am working on updating the Debian packages for Xiphos to include the latest upstream source. Once a Debian packages is in place, this package can be used in the Debian-derived Linux distributions too.

**Comment by greg-hellings** [comment]
Have you looked into building with the webkit editor?

**Comment by karlkleinpaste** [comment]
As well, check on what Ukikie (in IRC) does for official Ubuntu builds.

**Comment by greg-hellings** [comment]
I've just submitted #833 that adds Debian Sid to the list of environments Xiphos is test built against. If you follow the script logic, you'll see that I use the same builds as Ubuntu for that (GKT3, WebKit editor)

**Comment by karlkleinpaste** [comment]
closed on merge #833.

**Comment by refdoc** [comment]
On Thu, 2017-10-19 at 12:09 +0000, Teus Benschop wrote:
> I don't know how to build Xiphos on Debian sid using the packages
> available from Debian sid.
> 

./waf configure --enable-webkit-editor
./waf build

Peter

**Comment by teusbenschop** [comment]
Thank you all for the helpful information. I'm going to work on it.

**Comment by teusbenschop** [comment]
There is another open bug on Debian.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866657
The title of this bug is "xiphos: depends on libwebkitgtk-3.0-0 which is deprecated".
Indeed, when this package is not installed on Debian, this is how the package responds to it:

```
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : /usr/bin/xml2po 
Check for program xsltproc               : /usr/bin/xsltproc 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for pkg-config version >= 0.9.0 : ok 
Checking for GNOME related libs          : not found 
/<<BUILDDIR>>/xiphos-4.0.7+dfsg1/wscript:369: error: the configuration failed (see '/<<BUILDDIR>>/xiphos-4.0.7+dfsg1/build/config.log')
```
When installing package "libwebkitgtk-3.0-dev" in Debian, all goes fine.
My question to the developers is this:
How can I configure the package without it depending on "libwebkitgtk-3.0-dev" in Debian?
