### ISSUE TITLE
depends on libwebkitgtk-3.0-0 which is deprecated

### ISSUE THREAD

**Issue by teusbenschop** [crosswire/xiphos#834]
There is a bug report in Debian.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866657

The title of this bug is "xiphos: depends on libwebkitgtk-3.0-0 which is deprecated".

Indeed, when libwebkitgtk-3.0-0 is not installed on Debian, this is how configuring Xiphos responds:

```
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : /usr/bin/xml2po 
Check for program xsltproc               : /usr/bin/xsltproc 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for pkg-config version >= 0.9.0 : ok 
Checking for GNOME related libs          : not found 
/<<BUILDDIR>>/xiphos-4.0.7+dfsg1/wscript:369: error: the configuration failed (see '/<<BUILDDIR>>/xiphos-4.0.7+dfsg1/build/config.log')
```
After installing package "libwebkitgtk-3.0-dev" in Debian, all goes fine.

Currently Xiphos does not compile without the libwebkitgtk-3.0-dev package installed.

Once the packagers of libwebkitgtk-3.0-dev decide to remove this from Debian, Xiphos cannot be compiled anymore on Debian, and it would also be automatically removed from Debian.

May you please update the Xiphos source to no longer depend on libwebkitgtk-3.0-dev.

Or is there a way the package can be configured to not depend on this package?

**Comment by domcorbex** [comment]
Hi Teus,

Xiphos can be built with either WebKitGtk1 or WebKit2Gtk+GtkHTML-Editor, the Webkit2Gtk-editor is not implemented.
libgtkhtml-editor-4.0-0 is available in Sid, so I suggest you to try to build Xiphos with libwebkit2gtk-4.0 and libgtkhtml-editor-4.0-0.

Dom

**Comment by teusbenschop** [comment]
Hi Dom,

Thank you for the update.

I tried to configure Xiphos like this:

```
./waf configure --nocache --prefix=/usr --enable-webkit-editor --gtk=3 --enable-webkit2
```

The output will then be:

```
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : /usr/bin/xml2po 
Check for program xsltproc               : /usr/bin/xsltproc 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for pkg-config version >= 0.9.0 : ok 
Checking for GNOME related libs          : not found 
/home/teus/xiphos-4.0.7/wscript:369: error: the configuration failed (see '/home/teus/xiphos-4.0.7/build/config.log')
teus@sid:~/xiphos-4.0.7$ 
```

```
teus@sid:~/xiphos-4.0.7$ tail build/config.log
ok

----------------------------------------
Checking for GNOME related libs
pkg-config --errors-to-stdout --print-errors "gconf-2.0" "gmodule-2.0" "glib-2.0" "libgsf-1 >= 1.14" "libxml-2.0" --cflags --libs "gtk+-3.0"  "webkitgtk-3.0"  
Package webkitgtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkitgtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkitgtk-3.0' found
not found
teus@sid:~/xiphos-4.0.7$ 
```

The package "webkitgtk-3.0" that was not found is the one that is deprecated in Debian sid, and I removed it for this test. After installing libwebkitgtk-3.0-dev in Debian sid, Xiphos configures okay.

Xiphos can be configured to use webkit2, and this was done, yet it still looks for the webkit version one headers.

**Comment by domcorbex** [comment]
Hi,

On Tue, 31 Oct 2017 12:14:32 +0000 (UTC)
Teus Benschop <notifications@github.com> wrote:

> ./waf configure --nocache --prefix=/usr --enable-webkit-editor --gtk=3 --enable-webkit2

If you want to enable the GtkHTML editor, should be:
./waf configure --nocache --prefix=/usr --gtk=3 --enable-webkit2

-- 
domcox <dominique@corbex.org>

**Comment by greg-hellings** [comment]
I think the main issue is that WebKit2 API support does not have an
accompanying WebKit2 editor in Xiphos if memory serves correctly. So I
don't believe you can enable both WebKit2 AND the WebKit editor
simultaneously. Of course, it's possible I missed that being implemented
somewhere around here, but I seem to recall that being a complaint for a
while.

--Greg

**Comment by teusbenschop** [comment]
Thank you for the additional information. I have tried the new way of configuring Xiphos:

```
teus@sid:~/xiphos-4.0.7$ ./waf configure --nocache --prefix=/usr --gtk=3 --enable-webkit2
Linux detected 
Check for program g++ or c++             : /usr/bin/g++ 
Check for program cpp                    : /usr/bin/cpp 
Check for program ar                     : /usr/bin/ar 
Check for program ranlib                 : /usr/bin/ranlib 
Check for program gcc or cc              : /usr/bin/gcc 
Check for program msgfmt                 : /usr/bin/msgfmt 
Check for program intltool-merge         : /usr/bin/intltool-merge 
Checking for header locale.h             : ok 
Check for program glib-genmarshal        : /usr/bin/glib-genmarshal 
Check for program glib-mkenums           : /usr/bin/glib-mkenums 
Check for program dbus-binding-tool      : /usr/bin/dbus-binding-tool 
Check for program docbook2man            : not found 
Check for program xml2po                 : /usr/bin/xml2po 
Check for program xsltproc               : /usr/bin/xsltproc 
Check for program strip                  : /usr/bin/strip 
Checking for dbus-glib-1 >= 0.60         : ok 
Checking for libgtkhtml4                 : fail 
Checking for GtkHTML Editor 4.0          : fail 
/home/teus/xiphos-4.0.7/wscript:350: error: the configuration failed (see '/home/teus/xiphos-4.0.7/build/config.log')
teus@sid:~/xiphos-4.0.7$ 

teus@sid:~/xiphos-4.0.7$ cat build/config.log 

...
----------------------------------------
Checking for libgtkhtml4
pkg-config --errors-to-stdout --print-errors --modversion libgtkhtml-4.0
Package libgtkhtml-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgtkhtml-4.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgtkhtml-4.0' found
fail

----------------------------------------
Checking for GtkHTML Editor 4.0
pkg-config --errors-to-stdout --print-errors --modversion gtkhtml-editor-4.0
Package gtkhtml-editor-4.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtkhtml-editor-4.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtkhtml-editor-4.0' found
fail


teus@sid:~/xiphos-4.0.7$ apt search gtkhtml
Sorting... Done
Full Text Search... Done

```

The summary of the above is that it now looks for *gtkhtml* packages, and those packages cannot be found on Debian sid.

**Comment by domcorbex** [comment]
Hi Teus,

Without webkitgtk1 or webkit2gtk+libgtkhtml-editor, building Xiphos is not possible.
So, actually it is not possible to build Xiphos on Debian Sid.
(I'm really sorry, I didn't noticed that libgtkhtml-editor was only available on arm64)

Dom


On Thu, 02 Nov 2017 10:46:38 +0000 (UTC)
Teus Benschop <notifications@github.com> wrote:

> apt search gtkhtml
> Sorting... Done
> Full Text Search... Done
> 
> ```
> 
> The summary of the above is that it now looks for *gtkhtml* packages, and those packages cannot be found on Debian sid.

-- 
domcox <dominique@corbex.org>

**Comment by refdoc** [comment]
I am on Debian testing and build it frequently. PeterSent from my Huawei Mobile-------- Original Message --------Subject: Re: [crosswire/xiphos] depends on libwebkitgtk-3.0-0 which is deprecated (#834)From: Dominique Corbex To: crosswire/xiphos CC: Subscribed Hi Teus,

Without webkitgtk1 or webkit2gtk+libgtkhtml-editor, building Xiphos is not possible.
So, actually it is not possible to build Xiphos on Debian Sid.
(I'm really sorry, I didn't noticed that libgtkhtml-editor was only available on arm64)

Dom


On Thu, 02 Nov 2017 10:46:38 +0000 (UTC)
Teus Benschop <notifications@github.com> wrote:

> apt search gtkhtml
> Sorting... Done
> Full Text Search... Done
> 
> ```
> 
> The summary of the above is that it now looks for *gtkhtml* packages, and those packages cannot be found on Debian sid.

-- 
domcox <dominique@corbex.org>


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/crosswire/xiphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@domcorbex in #834: Hi Teus,\n\nWithout webkitgtk1 or webkit2gtk+libgtkhtml-editor, building Xiphos is not possible.\nSo, actually it is not possible to build Xiphos on Debian Sid.\n(I'm really sorry, I didn't noticed that libgtkhtml-editor was only available on arm64)\n\nDom\n\n\nOn Thu, 02 Nov 2017 10:46:38 +0000 (UTC)\nTeus Benschop \u003cnotifications@github.com\u003e wrote:\n\n\u003e apt search gtkhtml\n\u003e Sorting... Done\n\u003e Full Text Search... Done\n\u003e \n\u003e ```\n\u003e \n\u003e The summary of the above is that it now looks for *gtkhtml* packages, and those packages cannot be found on Debian sid.\n\n-- \ndomcox \u003cdominique@corbex.org\u003e\n"}],"action":{"name":"View Issue","url":"https://github.com/crosswire/xiphos/issues/834#issuecomment-341548877"}}}

**Comment by teusbenschop** [comment]
It does build on Debian sid, yes, but only with ```libwebkitgtk1```, and the package maintainers of ```libwebkitgtk1``` want to remove that first version, and move on to version 2. So I am trying to find a way to build Xiphos without the webkitgtk packages that the maintainers want to remove, and I am failing to build it right now...

**Comment by domcorbex** [comment]
I am also on Debian Testing and build Sword and Xiphos frequently.

But you can't do that anymore on Sid. WebKitGtk1 will be dropped for
security reasons:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866657

GtkHTML was tagged 'deprecated and should not be
used', then removed in 2015:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797429

Dom

On Thu, 02 Nov 2017 20:42:19 +0000 (UTC)
Peter von Kaehne <notifications@github.com> wrote:

> I am on Debian testing and build it frequently.

-- 
domcox <dominique@corbex.org>

**Comment by JJRcop** [comment]
Xiphos is blocked from migration into Debian Testing (buster) due to this issue https://qa.debian.org/excuses.php?package=xiphos

This issue is also being tracked in Launchpad https://bugs.launchpad.net/ubuntu/+source/xiphos/+bug/1588150

**Comment by teusbenschop** [comment]
There is a new bug in Debian, called "xiphos: Intent to remove from Debian".

Here is the link to the bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893864

The issue is that unless the Xiphos source code is upgraded to using webkit2gtk, it will be removed from Debian.

**Comment by karlkleinpaste** [comment]
we are aware, generally.
the specific issue here is dependency on webkitgtk-3, which is not precisely true any more, we build against webkitgtk-4 (WebKit2) fine, but using gtkhtml editor. yes, it needs to be fixed, and it will be. but this is no longer a report specific to that. closing for now. the work will be done elsewhere.

**Comment by jbicha** [comment]
@karlkleinpaste  I don't understand why you closed this bug. xiphos will likely be removed from Ubuntu 18.10 (development) and was already removed from Debian Buster (development) several months ago because of this issue.

[gtkhtml4.0](https://tracker.debian.org/pkg/gtkhtml4.0) was removed from Debian in 2015.

**Comment by JJRcop** [comment]
Is there any activity regarding this issue?

**Comment by teusbenschop** [comment]
Disclaimer: I am no part of this development team.

Looking at this comment:
> the specific issue here is dependency on webkitgtk-3, which is not precisely true any more, we build against webkitgtk-4 (WebKit2) fine, but using gtkhtml editor. yes, it needs to be fixed, and it will be. but this is no longer a report specific to that. closing for now. the work will be done elsewhere.

... I would say that it will be good to be pointed to an issue detailing the "work ... done elsewhere", or else someone open an issue related to the "gtkhtml editor", or else to be informed that it now builds fine :)
