### ISSUE TITLE
module manager cannot handle non-default cdrom drives or windows directories

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#835]
I have space in my case for 4 cdrom drives. and sometimes I have all 4 mounted. full tower cases can take up to 12. apparently the scsi interface xiphos are using only has 1 mount for /mnt/cdrom which I don't think accesses my cdroms properly. when I do select one, it comes out as E:\modules\ using the sword20080608.iso in the pub ftp area of crosswire.org  I downloaded long ago. the modules in that cdrom are broken up into multiple directories and might not be a good fit for xiphos. 

I had thought about listing the multiple directories like
DIR E:\modules E:\modules
DIR E:\mods.d E:\mods.d
DIR E:\locales.d E:\locales.d

but soon after I used it much, the install/update refresh button permanently disappeared, and a restart of the program did not fix this.

all ftp is currently broken in at least windows 7. no web site can be updated using windows and no windows machine can use ftp accessed modules in USA, and sword isos possibly cannot cannot be accessed even with a browser.

**Comment by refdoc** [comment]
I am not entirely sure I got fully what you said but:

1) You can add arbitrary local paths. 
2) the mods.d, modules, and locales.d directories have a function and they are not individual repositories. 
3) The path to a repository should end i the directory above where you see mods.d and modules etc. 

Re FTP - it works here and I would guess it is a local problem.

**Comment by karlkleinpaste** [comment]
one repository mount point necessarily contains at least mods.d and modules. the former contains config files for modules, the latter contains the module contents themselves. locales.d is optional.

**Comment by jmichae3** [comment]
nothing works wheninstall manager is cancelled first start. I cannot add new books like KJV.

**Comment by jmichae3** [comment]
I was able to install sword20080608.iso and this resulted in me having the KJV. settings are saved in keeping local vs remote hwich covers one bug report, and unfortunately, only butons available in module manager.imodules/install/update are View intro, Install, Close. there is no refresh.

**Comment by karlkleinpaste** [comment]
...sigh...

the purpose of Refresh is to obtain a remote repo's list of available modules -- the content is known, statically, simply by reading the mods.d directory. the concept of refresh simply doesn't apply to a local (e.g. cdrom/flash drive/network-mounted) repository.
