### ISSUE TITLE
replace lucene with soundex (patented)

### ISSUE THREAD

**Issue by jmichae3** [crosswire/xiphos#836]
instead of using lucene to do a job and making Christians and pastors wonder about who is really behind it, why not use 
- pcre 
- partial word searches, such as using std::string.find()!=std::string::npos in a word. break a word down.
- soundex http://www.highprogrammer.com/alan/numbers/soundex.html
patent is listed. a fuzzy search is not what you want, since it learns from previous efforts. try a modification of soundex based on the language instead. soundex is an old but familiar replacement for like-word search and it's fairly good.

and did you know you can access a list of strings faster using a reference than passing by value to a function? saves an full temporary copy of the whole thing. and if it's big, that can eliminate 5 minutes.

**Comment by refdoc** [comment]
It is the devil what is behind CLucene. We know.

**Comment by karlkleinpaste** [comment]
it is the underlying sword library that defines what optimized search facility is provided. as matters stand, sword itself can be built --with-cxx11regex and --with-xapian but neither is used in practice in packages as distributed. routinely, --with-icuregex is used, however. in any event, this isn't an issue controlled by xiphos, but by the packagers of the sword lib.

**Comment by karlkleinpaste** [comment]
how about we're not researchers in textual extraction.
how about we're not able to alter unilaterally how the sword lib does search.
what part of "this isn't an issue controlled by xiphos" did you fail to understand?
