### ISSUE TITLE
Xiphos hates superscripts

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#843]
Checked my OSIS XML and closing tags present for hi, type super. ({hi type="sub"{b{/hi} works, {hi type="super"}b{/hi} fails - using braces to avoid HTML problems with angle brackets) Am using superscripts in a Generic Book to point to adjacent entries, not as note markers or notes of any kind. Xiphos fails to close the superscript, with the result that the following text is also superscripted. When it hits the next superscript, it does the same thing, so the text gets smaller and smaller and smaller ... This is not an issue with a couple of other Bible programs tested. Thanks. Xiphos 4.0.4 (gtk3 webkit1) on Debian Stretch.

**Comment by karlkleinpaste** [comment]
not a xiphos bug. a sword lib bug, fixed 3 years ago. but we are still waiting on a new sword release. fortunately we finally seem to have serious prospects for that release to come out soon. your osis is fine, xiphos is fine, and sword (underlying xiphos) will be fine soon.
