### ISSUE TITLE
Add visual clue to typography for quotation tags

### ISSUE THREAD

**Issue by alerque** [crosswire/xiphos#846]
OSIS files that tag OT quotations in the NT should be rendered with a distinctive visual style by default.

See also #845 for a related rendering issue.

See also discussion on [this OSIS converter issue](https://github.com/adyeths/u2o/issues/17).

**Comment by DavidHaslam** [comment]
This prompts the question as to **which style** should be used?

- Some translations use italics.
- At least one uses oblique (subtly different to italics).
- The NASB uses small-caps.

How important might it be to approximate to how the printed editions look for copyrighted works?

Should this be implemented using an ancillary **style sheet** taylored to the module requirements?

**Comment by karlkleinpaste** [comment]
the problem is that, as for #845, we would depend on libsword to offer an OT quotation class that could be distinguished visually. until libsword does that, there's nothing we can do about it in xiphos.
