### ISSUE TITLE
Xiphos doesn't use non-break space

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#848]
In French we use non-break space between double punctuation (!?«»:;). But I see in Xiphos, if this punctuation end the line it will not stick the word. See the picture as example v 23 with the « at the end of the line and v 24 the ; at the beginning of the line. 

![nbsp](https://user-images.githubusercontent.com/19690477/32954563-bed9cc8c-cbb3-11e7-9c59-483b07d8989c.png)

This example is in Lingala but it is the same punctuation rules as in French.

**Comment by karlkleinpaste** [comment]
that's a matter of how the module author encoded the text. xiphos has no opinion about it. xiphos just asks for text and pastes it into the html widget. if that text contains ordinary spaces where you think there should be non-breaknig spaces, contact the module author about making an update.

**Comment by LAfricain** [comment]
>  contact the module author about making an update.

It's me the module author :) And I use non-break space, but for an unknown reason it seems to not "read" in Xiphos. The hexadecimal code is E2 80 AF, it is the code for non-break space, or maybe we need to use xc2\xa0? If I open the source file (usfm) with Libreoffice it read well the non-break space.

**Comment by LAfricain** [comment]
You are right! During conversion from usfm to osis, the non-break space are convert to E2 80 hexadecimal code!
