### ISSUE TITLE
copy/paste chapter bug in xiphos

### ISSUE THREAD

**Issue by dbecht** [crosswire/xiphos#851]
If you export a whole chapter with the option copy/export
passage > copy chapter, the verse counter does not work correctly in the following scenario.

In UGV Gen 8, the verses 6-7 have been combined. When I copy/export the whole chapter,
6-7 appears as 6, verse 8 as verse 7 and so forth. So you end up one verse short.

This does not happen if I export with the option copy/export passage >
copy verse range 1-22.

I'm using xiphos on linux manjaro.

**Comment by karlkleinpaste** [comment]
ok... it's a counting error. the text content is the same, but the numbering is off after v.6. it'll be a straightforward fix in the code, replacing simple counting through module movement with asking what verse  was arrived at with each movement. i should be able to get to it later this week when i will be addressing a number of xiphos reports in preparation for 4.0.8.
