### ISSUE TITLE
UI cut off on left side

### ISSUE THREAD

**Issue by dakrone** [crosswire/xiphos#854]
In Xiphos 4.0.7 on Fedora 27, the UI appears to be cut off on the left side:

![screenshot_2017-12-14_20-45-04](https://user-images.githubusercontent.com/19060/34025894-ae95d4bc-e10f-11e7-9223-e07b385d17f9.png)

The window is maximized

**Comment by karlkleinpaste** [comment]
the internal boundaries of the main window are not fixed. grab them with the mouse and move them.
in the initial, default window size (too small for most users, but xiphos starts pessimally small on purpose), all internal components including the sidebar are fully visible. under some window managers, the expansion on maximization induces internal boundaries to be shifted poorly. just resize.

**Comment by dakrone** [comment]
Ahh okay that fixed it. Thanks
