### ISSUE TITLE
Xiphos crashes at first start (with workaround)

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#855]
Using Debian 9 with XFCE, using Debian package Xiphox 4.04 GTK3 Webkit1.

3 bugs, 2 are mere anoyance, 1 could cause user to give up and abandon Xiphos, which would be a shame.

To reproduce:
Open a VM with above OS on which Xiphos has never been installed. (VM is not needed to crash, but it allows a perfectly clean system on the second try.)
Snapshot the VM to save.
Download Xiphos.
In the Module Manager, do sources, and refresh.
Xiphos Crashes.
Re-open Xiphos.
Click Install/Upgrade.
Crash.
Re-open Xiphos
Click Install/Upgrade
Crash ...

Work around - Bare VM again on which Xiphos has never been installed.
Download Xiphos.
In the Module Manager, do sources, and refresh.
Xiphos Crashes.
Re-open Xiphos.
Click Maintenance 
Do nothing in Maintenance
Click Install/Upgrade
Works. Able to download modules.
Close Module Manager.
Gives fake message that there are no modules.
Xiphos quits or crashes.
Re-open Xiphos
Probable long delay before main window opens, but eventually it dos and all is fine ever after.

**Comment by karlkleinpaste** [comment]
fixed almost a year ago. today's release is 4.0.7, and 4.0.8 will occur within a couple weeks.
