### ISSUE TITLE
Feature request: show the text of all the verses of a cross-reference not only one by one

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#857]
Currently, if you click on a cross-reference linked like that 30,1-14, all the 14 verses with appear in the sidebar. And all the verses will show just it's own text. I would be nice, when clicking on this kind of ref, to show all the text of the 14 verses.
![ref_link](https://user-images.githubusercontent.com/19690477/34913761-50ac0c36-f906-11e7-852d-751a6cc4e932.png)

**Comment by karlkleinpaste** [comment]
regrets, given the structure with which verse lists are represented (after passing them through verse normalization functions), it's unavoidable that they're separated. it's tightly analogous to a search which incidentally returns a series of consecutive verses; each result is distinct.
