### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by Yisrael8** [crosswire/xiphos#859]
my xiphos bible app doesn't open i reinstalled it and even went through the compatibility app which only goes to window 8 i have to use the compatibility function test to open it. once open it works but just not on it's own checked fire wall etc.

**Comment by karlkleinpaste** [comment]
i've attempted to reproduce this, but i can't. i have a couple win10 machines readily available, and i have no trouble starting xiphos on any of them.
did you have it working there previously? is there some circumstance to be distinguished besides simply "it's windows 10"?

**Comment by Yisrael8** [comment]
Thank you kindly for getting back yes it worked fine for months then suddenly it stopped working. I uninstalled it cleaned any left over files reinstalled several times. 
Sent from Yahoo Mail on Android 
 
  On Sat, Apr 7, 2018 at 5:10 PM, karl kleinpaste<notifications@github.com> wrote:   
i've attempted to reproduce this, but i can't. i have a couple win10 machines readily available, and i have no trouble starting xiphos on any of them.
did you have it working there previously? is there some circumstance to be distinguished besides simply "it's windows 10"?

**Comment by karlkleinpaste** [comment]
i've seen no similar reports from anyone else -- you're a singular case. unless something to discriminate how your system is different from others that we can analyze, i'm going to have to close this as unreproducible. open to suggestions, but have none of my own to offer right now.

**Comment by karlkleinpaste** [comment]
closed for now, until/unless some usefully discriminating configuration detail comes into play. re-open in the future if necessary.
