### ISSUE TITLE
Minor Font Name Issue

### ISSUE THREAD

**Issue by BobSongs** [crosswire/xiphos#860]
**O/S:** Linux System 4.13.0-32-generic
**Distribution:** Ubuntu Maté, 17.10
**Xiphos Release:** 4.0.4 (gtk3 webkit1)

**Issue:** Xiphos appears to have have an issue parsing Hebrew font names when adding them to the **fonts.conf** file. 
**Affected File:** ~/.xiphos/fonts.conf

**Example:**
- Hebrew text: WLC: Westminster Leningrad Codex.
- Right-click text, **Module Options** > **Font**.
- Current font: SBL Hebrew.
- New font selected: Taamey David CLM Medium.

**Result:** generic sans-serif font appears (possibly Arial) instead of selected font. 

**fonts.conf has this entry:**
```
[WLC]
Font=Taamey David CLM Medium
Fontsize=+1
```

**Solution:** A quick edit to remove the word **Medium** from the font name corrects the issue.

**fonts.conf edited:**
```
[WLC]
Font=Taamey David CLM
Fontsize=+1
```

Unsure where the issue resides: be it the O/S, font names or Xiphos. However, this issue appears to affect Hebrew texts only.

**Note:** Fonts are drawn from ~/.fonts folder.

**Comment by yetist** [comment]
Please this patch #876, is the font name saved ok?

**Comment by karlkleinpaste** [comment]
closing per #876 merge.
