### ISSUE TITLE
Need help compiling 4.0.7

### ISSUE THREAD

**Issue by BeForgiven-Info** [crosswire/xiphos#861]
Using Debian Stretch, XFCE, Sword 1.8.1.

When trying to compile xiphos-4.0.7, using the instructions in README.debian, I get:

debuild -us -uc
This package has a Debian revision number but there does not seem to be
an appropriate original tar file or .orig directory in the parent directory;
(expected one of xiphos_4.0.5+dfsg1.orig.tar.gz, xiphos_4.0.5+dfsg1.orig.tar.bz2,
xiphos_4.0.5+dfsg1.orig.tar.lzma,  xiphos_4.0.5+dfsg1.orig.tar.xz or xiphos-4.0.7.orig)
continue anyway? (y/n) n

And if I answer y, I get essentially the same message as error. This is true whether xiphos-4.0.7 is the current directory or xiphos-4.0.7/debian is the current directory.

I tried the git method also and got:
./waf configure --prefix=/usr --debug-level=optimized --enable-webkit-editor
....
Checking for header winsock.h            : not found

then the error messages below.

So far as I know, I have all dependencies. apt-get install does not return any package get errors.

Help would be appreciated. Many thanks.

 ./waf build
Waf: Entering directory `/home/spring/SwordHammer/SwordSources/xiphos/build'
[132/134] cxx_link: build/default/src/gnome2/locale_set_2.o build/default/src/gnome2/marshal_2.o build/default/src/gnome2/about_modules_2.o build/default/src/gnome2/about_sword_2.o build/default/src/gnome2/about_trans_2.o build/default/src/gnome2/about_xiphos_2.o build/default/src/gnome2/bibletext_2.o build/default/src/gnome2/bibletext_dialog_2.o build/default/src/gnome2/bookmark_dialog_2.o build/default/src/gnome2/bookmarks_menu_2.o build/default/src/gnome2/bookmarks_treeview_2.o build/default/src/gnome2/cipher_key_dialog_2.o build/default/src/gnome2/commentary_2.o build/default/src/gnome2/commentary_dialog_2.o build/default/src/gnome2/dialog_2.o build/default/src/gnome2/dictlex_2.o build/default/src/gnome2/dictlex_dialog_2.o build/default/src/gnome2/display_info_2.o build/default/src/gnome2/dummy_2.o build/default/src/gnome2/export_bookmarks_2.o build/default/src/gnome2/export_dialog_2.o build/default/src/gnome2/find_dialog_2.o build/default/src/gnome2/font_dialog_2.o build/default/src/gnome2/gbs_2.o build/default/src/gnome2/gbs_dialog_2.o build/default/src/gnome2/gui_2.o build/default/src/gnome2/ipc_2.o build/default/src/gnome2/main_menu_2.o build/default/src/gnome2/main_window_2.o build/default/src/gnome2/menu_popup_2.o build/default/src/gnome2/mod_mgr_2.o build/default/src/gnome2/navbar_book_2.o build/default/src/gnome2/navbar_book_dialog_2.o build/default/src/gnome2/navbar_versekey_2.o build/default/src/gnome2/navbar_versekey_dialog_2.o build/default/src/gnome2/navbar_versekey_editor_2.o build/default/src/gnome2/navbar_versekey_parallel_2.o build/default/src/gnome2/parallel_dialog_2.o build/default/src/gnome2/parallel_tab_2.o build/default/src/gnome2/parallel_view_2.o build/default/src/gnome2/preferences_dialog_2.o build/default/src/gnome2/search_dialog_2.o build/default/src/gnome2/search_sidebar_2.o build/default/src/gnome2/sidebar_2.o build/default/src/gnome2/sidebar_dialog_2.o build/default/src/gnome2/splash_2.o build/default/src/gnome2/tabbed_browser_2.o build/default/src/gnome2/treekey-editor_2.o build/default/src/gnome2/utilities_2.o build/default/src/gnome2/xiphos_2.o build/default/src/backend/gs_stringmgr_1.o build/default/src/backend/module_manager_1.o build/default/src/backend/sword_main_1.o build/default/src/editor/link_dialog_1.o build/default/src/editor/editor_1.o build/default/src/editor/webkit_editor_1.o build/default/src/main/biblesync_glue_1.o build/default/src/main/configs_1.o build/default/src/main/display_1.o build/default/src/main/export_passage_1.o build/default/src/main/global_ops_1.o build/default/src/main/lists_1.o build/default/src/main/main_1.o build/default/src/main/mod_mgr_1.o build/default/src/main/module_dialogs_1.o build/default/src/main/modulecache_1.o build/default/src/main/navbar_1.o build/default/src/main/navbar_book_1.o build/default/src/main/navbar_book_dialog_1.o build/default/src/main/navbar_versekey_1.o build/default/src/main/parallel_view_1.o build/default/src/main/prayerlists_1.o build/default/src/main/previewer_1.o build/default/src/main/search_dialog_1.o build/default/src/main/search_sidebar_1.o build/default/src/main/settings_1.o build/default/src/main/sidebar_1.o build/default/src/main/sword_1.o build/default/src/main/sword_treekey_1.o build/default/src/main/tab_history_1.o build/default/src/main/url_1.o build/default/src/main/xml_1.o build/default/src/xiphos_html/marshal_1.o build/default/src/xiphos_html/xiphos_html_1.o build/default/src/webkit/marshal_1.o build/default/src/webkit/wk-html_1.o -> build/default/src/gnome2/xiphos
default/src/main/display_1.o: In function `GTKPrintEntryDisp::display(sword::SWModule&)':
display.cc:(.text+0xadf): undefined reference to `sword::SWModule::renderText()'
default/src/main/display_1.o: In function `GTKPrintChapDisp::display(sword::SWModule&)':
display.cc:(.text+0x129c): undefined reference to `sword::SWModule::renderText(char const*, int, bool) const'
display.cc:(.text+0x1612): undefined reference to `sword::SWModule::renderText()'
display.cc:(.text+0x16be): undefined reference to `sword::SWModule::renderText()'
default/src/main/display_1.o: In function `CacheHeader(ModuleCache::CacheVerse&, sword::SWModule&, _global_ops*, BackEnd*)':
display.cc:(.text+0x31a7): undefined reference to `sword::SWModule::renderText(char const*, int, bool) const'
default/src/main/display_1.o: In function `GTKChapDisp::getVerseBefore(sword::SWModule&)':
display.cc:(.text+0x381e): undefined reference to `sword::SWModule::renderText()'
display.cc:(.text+0x3a4c): undefined reference to `sword::SWModule::renderText()'
display.cc:(.text+0x3daf): undefined reference to `sword::SWModule::renderText()'
display.cc:(.text+0x3e4a): undefined reference to `sword::SWModule::renderText()'
default/src/main/display_1.o: In function `GTKChapDisp::getVerseAfter(sword::SWModule&)':
display.cc:(.text+0x4341): undefined reference to `sword::SWModule::renderText()'
default/src/main/display_1.o:display.cc:(.text+0x4479): more undefined references to `sword::SWModule::renderText()' follow
default/src/backend/module_manager_1.o: In function `backend_module_mgr_list_local_sources':
module_manager.cc:(.text+0xa72): undefined reference to `sword::SWConfig::getSections()'
default/src/backend/module_manager_1.o: In function `backend_init_module_mgr_config':
module_manager.cc:(.text+0x2779): undefined reference to `sword::SWConfig::getSections()'
module_manager.cc:(.text+0x297a): undefined reference to `sword::SWConfig::getSections()'
module_manager.cc:(.text+0x2b0a): undefined reference to `sword::SWConfig::save() const'
module_manager.cc:(.text+0x2d8f): undefined reference to `sword::SWConfig::getSections()'
module_manager.cc:(.text+0x2f0b): undefined reference to `sword::SWConfig::save() const'
default/src/backend/module_manager_1.o: In function `backend_module_mgr_clear_config':
module_manager.cc:(.text+0x3922): undefined reference to `sword::SWConfig::getSections()'
module_manager.cc:(.text+0x3a58): undefined reference to `sword::SWConfig::save() const'
default/src/backend/module_manager_1.o: In function `backend_module_mgr_add_source':
module_manager.cc:(.text+0x4438): undefined reference to `sword::SWConfig::getSections()'
module_manager.cc:(.text+0x452c): undefined reference to `sword::SWConfig::save() const'
default/src/backend/sword_main_1.o: In function `BackEnd::render_this_text(char const*, char const*)':
sword_main.cc:(.text+0xb89): undefined reference to `sword::SWModule::renderText(char const*, int, bool) const'
default/src/backend/sword_main_1.o: In function `BackEnd::get_entry_attribute(char const*, char const*, char const*, bool)':
sword_main.cc:(.text+0x2815): undefined reference to `sword::SWModule::renderText()'
default/src/backend/sword_main_1.o: In function `BackEnd::get_render_text(char const*, char const*)':
sword_main.cc:(.text+0x3823): undefined reference to `sword::SWModule::renderText()'
default/src/backend/sword_main_1.o: In function `BackEnd::save_conf_file_item(char const*, char const*, char const*, char const*)':
sword_main.cc:(.text+0x4904): undefined reference to `sword::SWConfig::getSections()'
sword_main.cc:(.text+0x4a56): undefined reference to `sword::SWConfig::save() const'
default/src/backend/sword_main_1.o: In function `BackEnd::get_conf_file_item(char const*, char const*, char const*)':
sword_main.cc:(.text+0x4e4b): undefined reference to `sword::SWConfig::load()'
sword_main.cc:(.text+0x4f1a): undefined reference to `sword::SWConfig::getSections()'
default/src/main/export_passage_1.o: In function `_export_verse(_export_data, int) [clone .isra.34]':
export_passage.cc:(.text+0x884): undefined reference to `sword::SWModule::renderText()'
export_passage.cc:(.text+0x9ae): undefined reference to `sword::SWModule::renderText()'
default/src/main/export_passage_1.o: In function `main_export_content':
export_passage.cc:(.text+0x16a3): undefined reference to `sword::SWModule::renderText()'
export_passage.cc:(.text+0x17ac): undefined reference to `sword::SWModule::renderText()'
export_passage.cc:(.text+0x1938): undefined reference to `sword::SWModule::renderText()'
default/src/main/global_ops_1.o: In function `main_new_globals':
global_ops.cc:(.text+0x243): undefined reference to `sword::SWConfig::load()'
default/src/main/global_ops_1.o: In function `main_get_one_option':
global_ops.cc:(.text+0x1dd6): undefined reference to `sword::SWConfig::load()'
global_ops.cc:(.text+0x1ead): undefined reference to `sword::SWConfig::getSections()'
default/src/main/global_ops_1.o: In function `main_save_module_options':
global_ops.cc:(.text+0x22f8): undefined reference to `sword::SWConfig::load()'
global_ops.cc:(.text+0x23f0): undefined reference to `sword::SWConfig::getSections()'
global_ops.cc:(.text+0x2523): undefined reference to `sword::SWConfig::save() const'
default/src/main/module_dialogs_1.o: In function `main_dialogs_open':
module_dialogs.cc:(.text+0x26a1): undefined reference to `sword::SWMgr::getModules()'
module_dialogs.cc:(.text+0x2729): undefined reference to `sword::SWMgr::getModules()'
default/src/main/prayerlists_1.o: In function `prayerlist_construct(char*, char*)':
prayerlists.cc:(.text+0x100a): undefined reference to `sword::SWConfig::getSections()'
prayerlists.cc:(.text+0x161c): undefined reference to `sword::SWConfig::save() const'
default/src/main/search_dialog_1.o: In function `main_do_dialog_search':
search_dialog.cc:(.text+0x1eb2): undefined reference to `sword::SWMgr::getModules()'
search_dialog.cc:(.text+0x1f47): undefined reference to `sword::SWMgr::getModules()'
search_dialog.cc:(.text+0x217c): undefined reference to `sword::SWMgr::getModules()'
search_dialog.cc:(.text+0x2215): undefined reference to `sword::SWMgr::getModules()'
default/src/main/search_sidebar_1.o: In function `main_do_sidebar_search':
search_sidebar.cc:(.text+0x88a): undefined reference to `sword::SWMgr::getModules()'
default/src/main/search_sidebar_1.o:search_sidebar.cc:(.text+0x90f): more undefined references to `sword::SWMgr::getModules()' follow
default/src/main/sword_1.o: In function `main_get_mod_config_file':
sword.cc:(.text+0x43e9): undefined reference to `sword::SWConfig::getSections()'
collect2: error: ld returned 1 exit status
Waf: Leaving directory `/home/spring/SwordHammer/SwordSources/xiphos/build'
Build failed:  -> task failed (err #1): 
	{task: cxx_link locale_set_2.o,marshal_2.o,about_modules_2.o,about_sword_2.o,about_trans_2.o,about_xiphos_2.o,bibletext_2.o,bibletext_dialog_2.o,bookmark_dialog_2.o,bookmarks_menu_2.o,bookmarks_treeview_2.o,cipher_key_dialog_2.o,commentary_2.o,commentary_dialog_2.o,dialog_2.o,dictlex_2.o,dictlex_dialog_2.o,display_info_2.o,dummy_2.o,export_bookmarks_2.o,export_dialog_2.o,find_dialog_2.o,font_dialog_2.o,gbs_2.o,gbs_dialog_2.o,gui_2.o,ipc_2.o,main_menu_2.o,main_window_2.o,menu_popup_2.o,mod_mgr_2.o,navbar_book_2.o,navbar_book_dialog_2.o,navbar_versekey_2.o,navbar_versekey_dialog_2.o,navbar_versekey_editor_2.o,navbar_versekey_parallel_2.o,parallel_dialog_2.o,parallel_tab_2.o,parallel_view_2.o,preferences_dialog_2.o,search_dialog_2.o,search_sidebar_2.o,sidebar_2.o,sidebar_dialog_2.o,splash_2.o,tabbed_browser_2.o,treekey-editor_2.o,utilities_2.o,xiphos_2.o,gs_stringmgr_1.o,module_manager_1.o,sword_main_1.o,link_dialog_1.o,editor_1.o,webkit_editor_1.o,biblesync_glue_1.o,configs_1.o,display_1.o,export_passage_1.o,global_ops_1.o,lists_1.o,main_1.o,mod_mgr_1.o,module_dialogs_1.o,modulecache_1.o,navbar_1.o,navbar_book_1.o,navbar_book_dialog_1.o,navbar_versekey_1.o,parallel_view_1.o,prayerlists_1.o,previewer_1.o,search_dialog_1.o,search_sidebar_1.o,settings_1.o,sidebar_1.o,sword_1.o,sword_treekey_1.o,tab_history_1.o,url_1.o,xml_1.o,marshal_1.o,xiphos_html_1.o,marshal_1.o,wk-html_1.o -> xiphos}

**Comment by domcorbex** [comment]
BeForgiven-Info, what version of Sword are you running?

**Comment by BeForgiven-Info** [comment]
I am using Sword 1.8.1, latest version, so far as I know.

Tom Sullivan
info@BeForgiven.INFO
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by karlkleinpaste** [comment]
based on complaints such as
undefined reference to sword::SWConfig::getSections()
you are not in fact using sword 1.8.1. an educated guess says you have 2 versions of sword installed, under slightly different names in /usr/lib. check symlinks and version stamps. it is absolute certainty that getSections exists in sword/swconfig.h, and if your linkage against sword does not find this, then you are not using 1.8.1.

**Comment by karlkleinpaste** [comment]
closing this, since it's clear from linkage error that the underlying problem must be that 1.8.1 is not in use, as seen in e.g.

$ readelf -a -W /usr/lib64/libsword.so.1.8 | c++filt | grep getSections
00000000003aa078  0000067900000001 R_X86_64_64            000000000007fa00 sword::SWConfig::getSections() + 0
00000000003b4f00  0000067900000007 R_X86_64_JUMP_SLOT     000000000007fa00 sword::SWConfig::getSections() + 0
   555: 0000000000173840   567 FUNC    GLOBAL DEFAULT   12 org_crosswire_sword_SWConfig_getSections
  1657: 000000000007fa00     5 FUNC    GLOBAL DEFAULT   12 sword::SWConfig::getSections()

libsword.so is symlinked to libsword.so.1.8,
