### ISSUE TITLE
Cannot compile through AUR

### ISSUE THREAD

**Issue by ryanmusante** [crosswire/xiphos#864]
Xiphos will not install. Gtkhtml4 fails to compile because of enchant mismatch. I have tried to compile enchant separately, two different versions including enchant 1.6. 

Alternative gtkhtml4 package available on AUR however package is deprecated in repositories.

```
Edit: Friend at manjaro forums created git package to fix install. 
https://aur.archlinux.org/packages/gtkhtml4-git
```

**Comment by thevictoryiswon** [comment]
I am having the same problem! Installed Xiphos from flatpack as a workaround. I hope this is resolved soon.

**Comment by greg-hellings** [comment]
I'm not sure it's our responsibility to fix either AUR or gtkhtml4. If gtkhtml4 fails to compile out of AUR then why are you reporting the problem here? Report it to the gtkhtml4 maintainers.

**Comment by ryanmusante** [comment]
I understand, just pointing it out that for Arch users/Arch derivatives, they will have problems and that a workaround is gtkhtml4-git until the older package is ever updated.

**Comment by karlkleinpaste** [comment]
given that there is nothing for us in xiphos to do about this, i'm closing.

**Comment by alerque** [comment]
@ryanmusante and @thevictoryiswon You may want to give this another gander. The current AUR packages should be worked out to compile smoothly with the latest Xiphos release, and there are precompiled packages available too. See comments on the AUR page.
