### ISSUE TITLE
Advanced search crashes if using custom list for second/third/etc. time

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#869]
Xiphos goes away (crashes ?) if you do more than one, two, or 3 - 5 searches in a row when using a custom module list. The contents of the module list don't matter. Only work around is to close the advanced search window between advanced searches, the re-select your settings. Using Debian Stretch, XFCE 4.12.

**Comment by TomSullivanInUSA** [comment]
Addition: This is Xiphos 4.0.4. I cannot compile 4.0.7

**Comment by refdoc** [comment]
Git HEAD Debian Testing, Gnome 3.28, Wayland - not crashing with me, but behaving odd - seems to freeze for a long time and appears crashed, then recovers. Same search can take arbitrary lengths of time - seconds or deep freeze and then recovery. 

My sample module list is only the ESV. 

Here is the terminal output 

(xiphos:2582): Gtk-CRITICAL **: 16:24:03.442: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(xiphos:2582): Gtk-CRITICAL **: 16:24:03.450: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(xiphos:2582): Gtk-CRITICAL **: 16:24:03.456: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(xiphos:2582): Gtk-CRITICAL **: 16:24:03.462: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(xiphos:2582): Gtk-CRITICAL **: 16:24:03.467: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

**Comment by TomSullivanInUSA** [comment]
I got this if launched from terminal. By "crash," I mean that Xiphos 
exits abruptly without warning.
$ xiphos
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

(xiphos:6694): Gtk-CRITICAL **: gtk_box_pack: assertion 
'_gtk_widget_get_parent (child) == NULL' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is 
discouraged.

(xiphos:6694): GLib-GObject-WARNING **: invalid cast from 
'GtkScrolledWindow' to 'GtkBox'

(xiphos:6694): Gtk-CRITICAL **: gtk_box_pack: assertion 'GTK_IS_BOX 
(box)' failed
Segmentation fault

Hope this helps.

Tom

Tom@SullivanInUSA.com
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.
