### ISSUE TITLE
Bible showing weird characters (probably font/encoding issue)

### ISSUE THREAD

**Issue by vonpupp** [crosswire/xiphos#872]
Hello,

I am trying to use the [TS2009] on Xiphos. Unfortunately I had to convert it from a [mysword .bbl.mybible] module. To do so I used two programs on a **very old** Windows XP VM that I still have. The first tool used to convert it is called [Bible converter], which produced [this zip file] that should work directly on Xiphos. The second tool used is [Simple Bible reader], which produced [this other zip file]. The first program seems to be part of the second, I guess this is why both zip files are exactly equals in bytes size.

When I install [TS2009] on mysword it is recommended to also install the TS2009 fonts for accented Greek. There is a list with 9 fonts but I guess the important one is [Junicode]. I installed this font on Arch Linux using pacman however Xiphos doesn't seem to render the text properly.

I am not sure where the problem is, if it is either on the conversion, a font issue or Xiphos itself. Any idea?

Thank you very much.

[TS2009]: http://www.isr-messianic.org/downloads/free-scriptures-downloads.html
[mysword .bbl.mybible]: https://www.dropbox.com/s/g4k6551hhcb2zbo/TS2009.bbl.mybible?dl=0
[Bible converter]: http://www.bibleanalyzermodules.com/index.php/bible-analyzer-modules/download/9-utilities-misc/4-bible-converter
[this zip file]: https://www.dropbox.com/s/2u28j194x02khxg/TS2009.zip?dl=0
[Simple Bible reader]: http://www.churchsw.org/2013/02/simple-bible-reader-converter.html
[this other zip file]: https://www.dropbox.com/s/okjo3ekg8b3zulx/TS2009_2.zip?dl=0
[Junicode]: http://junicode.sourceforge.net/

**Comment by karlkleinpaste** [comment]
The 2 zip files have identical content.
No idea what this conversion process did, or how it's supposed to work. It's not a font issue; the content is screwed. At a guess, you've got compressed text instead of the real original, and no way for us to recover the original. Not a Xiphos or Sword problem.

**Comment by vonpupp** [comment]
Thanks for your answer @karlkleinpaste.

Do you know wo to convert a mysword .bbl.mybible module to a SWORD module?

Are there any tools? Preferably that runs on Linux and are open source?
