### ISSUE TITLE
Some items that could stand correction:

### ISSUE THREAD

**Issue by BeForgiven-Info** [crosswire/xiphos#890]
Hey all, great work. Xiphos is the best one out there for Linux in my opinion.

Using git pull of 4.1 as of 4/20/18 on Debian Stretch, XFCE 4.12:

Lists only support own markers and secondary levels have extra markers:
I would attach a screenshot, but github won't let me do it (.png). Here is what it looks like as displayed,
except that I cannot type some special characters:
. list item
.
  . list item next level
  . another list item in the next level
  .
    . third level item

Lists also ignore one's own markers, something allowed in the OSIS spec. If you try, you get something like:
. 1.one

(All of the periods above are symbols that show in Xiphos. This includes the extra ones.)

Understrike / underline not supported.

**Comment by karlkleinpaste** [comment]
i lack context for what you're describing. are you creating a module? editing a journal?

**Comment by BeForgiven-Info** [comment]
The example occurs in a general book.

Tom Sullivan
info@BeForgiven.INFO
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by karlkleinpaste** [comment]
don't make me guess. specify. exactly.

**Comment by BeForgiven-Info** [comment]
Karl:

See attached demo. Thanks for all your hard work and attention to user 
needs.

Thanks again.

Tom

Tom Sullivan
info@BeForgiven.INFO
FAX: 815-301-2835
---------------------
Great News!
God created you, owns you and gave you commands to obey.
You have disobeyed God - as your conscience very well attests to you.
God's holiness and justice compel Him to punish you in Hell.
Jesus Christ became Man, was crucified, buried and rose from the dead
as a substitute for all who trust in Him, redeeming them from Hell.
If you repent (turn from your sin) and believe (trust) in Jesus Christ,
you will go to Heaven. Otherwise you will go to Hell.
Warning! Good works are a result, not cause, of saving trust.
More info is at www.esig.beforgiven.info
Do you believe this? Copy this signature into your email program
and use the Internet to spread the Great News every time you email.

**Comment by karlkleinpaste** [comment]
email attachments don't survive into github bug reports. you'll have to attach via the web interface.

**Comment by BeForgiven-Info** [comment]
Here it is. Sorry.
[demo.tar.gz](https://github.com/crosswire/xiphos/files/1934817/demo.tar.gz)

**Comment by karlkleinpaste** [comment]
ok, i'm going to have to close this, as the mistaken artifacts you're seeing here aren't xiphos-oriented.

my oft-repeated response to display problems in xiphos is, "xiphos displays whatever the engine provides." all too often, what the engine provides is just plain wrong.

i ran xiphos under the debugger and trapped it as it was constructing the content for key /MyWSC/TheWestFake/ExtLinks, as seen in the output of "mod2imp MyWSC".

the module contains the correct content (interpolating angle brackets to square, to get past github's editor):

[p]Here is an external link: [/p] [p] [a href="https://beforgiven.info"]Link to NoWhere[/a]  The link above should go to https://beforgiven.info. [/p]

that [a]...[/a] looks perfectly fine. but here's what happens, when we peek inside with the debugger:

(gdb) p rework->str
$6 = (gchar *) 0x1a59720 "<br />\nHere is an external link: <br />\n Link to NoWhere  The link above should go to https://beforgiven.info. <br />\n"

that's the content returned from sword. note that the [a]...[/a] link around Link to NoWhere is ... just plain missing.

i haven't actually looked at your list display problems, to breakpoint again and see how the OSIS filters in sword may have mangled them, but i'm willing to bet that similar damage is being done. there has been discussion in the past about sword's inability to produce valid output for tables from OSIS docs, including someone who tried to find lowest common denominator best practices to satisfy both sword- and jsword-driven frontends, without success.

sorry. nothing i can do here. take the problem to those who can address it.

**Comment by karlkleinpaste** [comment]
the device has not been built that can express how much i hate github's editor.

the bug-ridden output should have been interpolated angle-to-square, too, to make it plain text and visible here. let's try that again:

$6 = (gchar *) 0x1a59720 "[br /]\nHere is an external link: [br /]\\n Link to NoWhere  The link above should go to https://beforgiven.info. [br /]\\n"

**Comment by karlkleinpaste** [comment]
future reference: test your OSIS-to-XHTML construct errors with diatheke directly, without wondering whether it's xiphos that's screwing up:

diatheke -b MyWSC -f xhtml -k /MyWSC/TheWestFake/ExtLinks

redirect diatheke's output to some file test.html, then invoke chrome on that file. same display issues.
