### ISSUE TITLE
Small capitals for divine name not displayed in parallel view

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#895]
Using 4.1.0 (gtk3 webkit1) on Debian 9, XFCE 4.12. Consider, for just one example Dt 26.17. The divine name is in small capitals in the standard view, but the same version, e.g., ESV2011, in parallel view does not display the divine name in small capitals. This is not version or module dependent. (My parallel view has 5 columns, and all 5 display the same problem.)

**Comment by karlkleinpaste** [comment]
well, that's interesting.

i know already exactly why that happens: the parallel displays do not obtain the preamble content normally retrieved for a single module's chapter display, which controls how various CSS classes appear. even better, it's not clear just this instant that such a preamble would be consistent from one module to another.

i'll have to give some thought to whether this is fixable in the current architecture for parallels.

**Comment by karlkleinpaste** [comment]
(yes i know it's been a long time.)
what this does:
xiphos will now obtain display controls from the 1st parallel module, applied to all modules.
typically, this will be the standard OSIS controls, which will provide for small caps "Lord" etc. but it's not guaranteed. in the parallel environment, variances between module schemes have to be resolved in favor of 1 module.
