### ISSUE TITLE
Version 4.1.0 won't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#896]
I compiled sword 1.8 biblesync, and after xiphos. All compiled without error, but if I want to run xiphos I have this error:
`xiphos: error while loading shared libraries: libsword-1.8.0.so: cannot open shared object file: No such file or directory`

**Comment by LAfricain** [comment]
Ok I found a workaround:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libsword.so /usr/lib/x86_64-linux-gnu/libsword-1.8.0.so`

**Comment by karlkleinpaste** [comment]
normal result of "make install" for sword is to have .so and -VERSION.so linked. something must have gone wrong in your installation process for sword.

**Comment by LAfricain** [comment]
Ok!
