### ISSUE TITLE
New xiphos compilation doesn't see the /usr/share/sword modules

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#900]
After a fresh compilation of Xiphos, it doesn't display the modules in /usr/share/sword. I can only read the local ($USER) modules. I need to move it to /usr/local/share/sword.

**Comment by karlkleinpaste** [comment]
if you don't change anything in xiphos, then nothing that xiphos does will change.
handling of discovery of module areas is generally part of sword itself.
xiphos concern is only with regard to module installation, where install destination is selected.
if you don't tell sword its normal prefix dir (/usr) when it's built, it will probably auto-select /usr/local.
therefore...

**Comment by LAfricain** [comment]
OK.
