### ISSUE TITLE
Changing Commentary

### ISSUE THREAD

**Issue by Shardle** [crosswire/xiphos#902]
If there is a shortcut for changing commentary I have not been able to find it. Changing commentary is, for me, a laborious process and a shortcut would be extremely welcome. In many ways Xiphos is better than e-Sword, but this is an exception.

**Comment by karlkleinpaste** [comment]
i guess i'm not seeing the problem. with the module list on the left side, you can leave commentaries open, and pick any at random that you wish at any time.

**Comment by Shardle** [comment]
Hi, K,

Thanks for your reply.
Yes you can leave commentaries open - but only until you restart Xiphos.
Also, that panel is used for the TSK commentary (the most useful one to me)  and also for changing versions and several other things. If you have a lot of modules downloaded and TSK showing in the panel, you need to click modules, then go down a long list to commentaries, open it up and then click on the one you want, and repeat to get back to TSK commentary . . . a bit too long winded and in practice I use e-Sword for other commentaries (where you can switch between commentaries and versions with a single click) and I just leave Xiphos at TSK ( and KJV) all the time.
I was hoping that there might be some built in shortcuts I was not aware of.

**Comment by karlkleinpaste** [comment]
i'm imagining that, in your situation, i would leave one tab set with TSK as its commentary. use another tab for random, more temproary commentary choices. when you want TSK, come back to the tab that has it.
alternatively, keep TSK open in a separate window entirely.

**Comment by Shardle** [comment]
Despite using Xiphos for years, I have never noticed that little + sign for tabs!
I've been using tabs on Xiphos today and it is a significant step in the right direction - a real help.
Thankyou very much for pointing it out.

**Comment by LAfricain** [comment]
Seems to be solved?
