### ISSUE TITLE
Faulty interaction between previewer pane view settings

### ISSUE THREAD

**Issue by alerque** [crosswire/xiphos#910]
Using the _View_ menu to turn on and off the preview pane works fine by itself, but there is a bad interaction with the _Show Previewer in Sidebar_ option. If the latter is enabled while the first is disabled, the preview pane is shown even though the option to show it is still off.

Setting the previewer to show in the sidebar should only change _where_ the preview is shown, not automatically show it if the respective preference for that is turned off.

Using [version](https://github.com/crosswire/xiphos/pull/909/commits/176a49b013ba3811c1b25b5114f7d3b13f57c864)  `4.1.0-38-gf965eaeb`.

**Comment by karlkleinpaste** [comment]
ok...i'm not seeing it.
initial state: preview enabled, show previewer in sidebar enabled.
change state: disable/uncheck preview.
result state: preview panel is gone.

what am i missing? what are you seeing that i'm not?

**Comment by alerque** [comment]
I just replicated this again using today's git build.

Initial state: "preview" *disabled*.

There should be no preview pane.

Now toggle the state of "show previewer in sidebar". The preview pane turns on even though the checkbox to enable it is still disabled. Note this works for both initial states of the location option.

Now to make it go away you have to first _check_ the "preview" box to enable it properly, then go back and uncheck it to disable it.

Toggling the option for _where_ the preview would show up should not toggle it actually showing up ... or at least if it did it needs to also enable the checkbox for the preview pane so the option and the actual state match.

**Comment by karlkleinpaste** [comment]
> toggle the state of "show previewer in sidebar". The preview pane turns on

oooh. ouchie. ok, i'm on it.
