### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by TomSullivanInUSA** [crosswire/xiphos#915]
Xiphos was fine. Then used paper Bible for 2 weeks, came back and got segfault on launch. No changes to Sword or Xiphos. BibleTime worked normally. Using Debian 9 with XFCE. Probably due to an update incompatibility, I suppose. Pulled from git, rebuilt, reinstalled, all seems well.

Just a note for anyone else getting this. May not even need to pull from git.

**Comment by karlkleinpaste** [comment]
not enough to go on, really. but keep us in mind if you see it again.

**Comment by alerque** [comment]
Actually this is plenty if information to guess what happened, and this is to be expected.

Xiphos builds are (as is the case for _most_ software) built against some system libraries and have links to those shared modules. If you update the system and any one of the libraries it uses are updated, Xiphos will need to be rebuilt. You don't need fresh sources (although that's not a bad idea) but you do have to rebuild against the libraries currently available on the system.

If you use installation packages built for your system the package manager usually takes care of this for you. For software you build and install yourself you're expected to have to take care of rebuilding when necessary.

Some software and languages do have build-time options for static linking to minimize instances of this, but that brings on other problems (such as massive binary sizes, increased runtime memory footprint, lingering security issues, etc.).
