### ISSUE TITLE
Debian will drop gconf2 - patch attached

### ISSUE THREAD

**Issue by teusbenschop** [crosswire/xiphos#918]
There was a bug report in Debian.
It is on the Xiphos package.

Here is the text of the bug report:

Your package depends and build-depends on gconf, but gconf will be
removed from Debian soon (most probably right after the Buster
release).

Furthermore, it seems that the dependency is completely unnecessary --
xiphos installs URL handlers but these keys are never read by GNOME as
this functionality has been deprecated long time ago.  The right way
to achieve this is through .desktop/mime/aplication-registry files;
that would make them work under any XDG-compliant environment.

Here is the link to the report:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912807

The bug report contains a partial patch.

**Comment by stefanhusmann** [comment]
Is there a patch to be appplied to the xiphos sources directly? The patch in the bu report is for the debian packagers merely.

**Comment by teusbenschop** [comment]
The patch that eventually made it into Debian will be the same that can be applied to the Xiphos sources directly.

There's two patches actually.

They are here in this folder:

https://salsa.debian.org/pkg-crosswire-team/xiphos/tree/master/debian/patches

It is the two patches numbered 0016... and 0017...

**Comment by alerque** [comment]
It isn't just Debian. Gconf is deprecated across most of the Linux ecosystem, including by the Gnome project where it was born. These patches should get applied it should be dropped as a dependency. Note patch 17 still does the job but with `cmake` in play 16  will need some adaption. I'm happy to submit a PR...
