### ISSUE TITLE
Shift + F10 in Bible window brings up a wrong menu

### ISSUE THREAD

**Issue by kosivantsov** [crosswire/xiphos#922]
Shift + F10 doesn't bring up the same menu as mouse right-click. The menu shown on Shift + F10 is not actually usable for anything pertaining to the Bible text/dictionary/book.

**Comment by karlkleinpaste** [comment]
um...that's very peculiar. something has overtaken the Sh/F10 binding. i will look into it, but oddly, it appears to be a window manager thing now. can't begin to explain that.

**Comment by LAfricain** [comment]
Seems to be solved in the last release.

**Comment by kosivantsov** [comment]
Sometimes it shows a menu with "Back|Forward|Stop|Reload" items, but now indeed in most cases you do get the regular right-click menu on Shift+F10. Thank you for fixing it, now Xiphos is much more usable without a mouse.
