### ISSUE TITLE
The ndebele and Shona and not listed in the module manager

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#923]
The ndebele and Shona language and not listed in the module manager. It is in Bibletime, but only with their iso code (nd and sh).

**Comment by karlkleinpaste** [comment]
nb is norwegian, per ISO lang codes doc used years ago to create the languages file.
we have multiple modules using it.

    $ pwd
    /home/karl/.sword/mods.d
    $ egrep Lang='(nb|sh)$' *
    norbroed.conf:Lang=nb
    norsk.conf:Lang=nb
    $ egrep '^(sh|nb) ' /usr/share/xiphos/languages 
    nb      Norsk Bokmål
    $ grep -i ndebele /usr/share/xiphos/languages 
    # Ndebele, North
    nd	Sindebele
    # Ndebele, South
    nbl	South Ndebele
    nde	North Ndebele

**Comment by LAfricain** [comment]
Yes sorry I edited the message nd is correct, but the problem is the same.

**Comment by karlkleinpaste** [comment]
language categories appear in module lists iff there are modules in that category. do you have nd and sh modules? i have one nd which appears correctly, but no sh modules.
![screenshot1](https://user-images.githubusercontent.com/7548920/50540304-56f0da80-0b5d-11e9-9300-b15faf4a88f8.png)

**Comment by LAfricain** [comment]
Yes when it's install, it's look ok, it's when you want to install it, in the module manager. But now I tried again, with removing it, and it appears!! I will test on an other computer if I have occasion. Maybe it's me who don't look well :(

**Comment by karlkleinpaste** [comment]
looks normal in mod.mgr to me. crosswire repo.
![screenshot1](https://user-images.githubusercontent.com/7548920/50540375-b1d70180-0b5e-11e9-9127-a26e0b2ccaee.png)

**Comment by LAfricain** [comment]
I tested on an other computer, I can found both! I think I was looking for Ndebele and not Sindebele, and Shona rather thanChishona
