### ISSUE TITLE
Windows build cannot find glib-genmarshal

### ISSUE THREAD

**Issue by TamaMcGlinn** [crosswire/xiphos#924]
I am trying to build Xiphos on windows. Install.md does not contain any instructions on how to do so, but I see that CMake is used, so I tried getting that to generate the files I need (into build-win/ since that is gitignored), but I received the following error indicating that glib-genmarshal is required.

```
The C compiler identification is MSVC 19.16.27025.1
... etc ...
Detecting CXX compile features - done
Looking for glib-genmarshal
CMake Error at cmake/XiphosBuildTools.cmake:29 (message):
  Cannot find glib-genmarshal, which is required to build xiphos
Call Stack (most recent call first):
  cmake/XiphosBuildTools.cmake:35 (xiphos_find_program)
  CMakeLists.txt:73 (include)
```

**Comment by karlkleinpaste** [comment]
i don't build for windows on windows directly; rather, via cross-compilation on fedora linux.
in my rpm-based linux land, "yum-builddep xiphos" installs all the required tools incl glib-genmarshal.

in the source, you'll find in subdir win32/ a script makeDistro.sh, taking a few parameters to describe the type of build you want (32 vs. 64, debug or not, gtk 2 or 3 [only 2 is supported right now]) using our older pre-cmake build system, and the script Just Does It.

**Comment by karlkleinpaste** [comment]
makeDistro is no longer applicable as it stands, because the waf build system is gone.
windows build will be reworked for cmake very soon.
