### ISSUE TITLE
Parallel Bible Tabs in Xiphos 4.0.7

### ISSUE THREAD

**Issue by rbeltz48** [crosswire/xiphos#926]
The parallel Bible tabs in Ver. 4.0.7 have alternating white and black tabs. The Bible version abbreviation at the top of each tab is black so the name of the version is not shown with black against a black background. The developers really should have checked this first before putting this version into production. Is there a fix for this?

**Comment by rbeltz48** [comment]
Hi Karl,
        
        Not confusing to me. If the
        default display colors are changed, then it creates a problem.
        In Ver. 3.1.5, which I have been using for years, I have changed
        the default display colors to:
        
        Foreground - Black
          Current Verse - Black
            Verse Number - Black
              
              When using the parallel tabs in
                3.1.5, the tabs are
                white and light gray. Not so in 4.0.7. They are white
                and black when default display colors are black as
                above.
                
                Also, when you remove a
                  version from parallel view in 4.0.7 it leaves a blank space and an error
                  occurs every time you open Xiphos.
                  
                  I have been using Linux
                    since 2006 and Xiphos and Bibletime for more than 10 years. The older versions are
                        clearly better. Thank you.
                
                Sincerely,
                Rick Beltz
                  Retired I.T.
                      Sr.
                        Programmer/Analyst-Sr. Consultant
                    ______________________________________
      
    On 01/24/2019 10:29 AM, karl
        kleinpaste wrote:
      
    
      your report is confusing for several reasons.
        first, the default display color of module names in display
        headings is blue, specifically "#0000CF," being borrowed from
        the verse number display color.
        second, the background of the module names is a fixed grey, not
        user-modifiable, which would make anything but an identical grey
        choice visible.
      screenshot of my currently running xiphos, opening parallel
        tab, shows blue module names on grey background, very visible.
        
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/crosswire/xiphos","title":"crosswire/xiphos","subtitle":"GitHub
repository","main_image_url":<a class="moz-txt-link-rfc2396E"
href="https://github.githubassets.com/images/email/message_cards/header.png">"https://github.githubassets.com/images/email/message_cards/header.png"</a>,"avatar_image_url":<a
class="moz-txt-link-rfc2396E"
href="https://github.githubassets.com/images/email/message_cards/avatar.png">"https://github.githubassets.com/images/email/message_cards/avatar.png"</a>,"action":{"name":"Open
in GitHub","url":<a class="moz-txt-link-rfc2396E"
href="https://github.com/crosswire/xiphos">"https://github.com/crosswire/xiphos"</a>}},"updates":{"snippets":[{"icon":"PERSON","message":"@karlkleinpaste
in #926: your report is confusing for several reasons.\r\nfirst, the
default display color of mo
dule names in display headings is blue, specifically \"#0000CF,\" being borrowed from the verse number display color.\r\nsecond, the background of the module names is a fixed grey, not user-modifiable, which would make anything but an identical grey choice visible.\r\n\r\nscreenshot of my currently running xiphos, opening parallel tab, shows blue module names on grey background, very visible.\r\n![screenshot1](<a class="moz-txt-link-freetext" href="https://user-images.githubusercontent.com/7548920/51688472-a1ca0a80-1fc2-11e9-8791-03f72ce9c2d0.png">https://user-images.githubusercontent.com/7548920/51688472-a1ca0a80-1fc2-11e9-8791-03f72ce9c2d0.png</a>)\r\n"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/926#issuecomment-457238240">"https://github.com/crosswire/xiphos/issues/926#issuecomment-457238240"</a>}}}
      [
{
"@context": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/926#issuecomment-457238240">"https://github.com/crosswire/xiphos/issues/926#issuecomment-457238240"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/crosswire/xiphos/issues/926#issuecomment-457238240">"https://github.com/crosswire/xiphos/issues/926#issuecomment-457238240"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]

**Comment by karlkleinpaste** [comment]
i've checked the code just now, which hasn't changed since at least 2015.
it uses a fixed color #c0c0c0 (light grey) as background for the module title bar, and overloads bible_verse_num_color for the module names in foreground. it can be unviewable only if you've matched bible_verse_num_color to #c0c0c0.
