### ISSUE TITLE
Ubuntu PPA not updated

### ISSUE THREAD

**Issue by sgadsby** [crosswire/xiphos#928]
Hi, 4.0.7 installed via PPA working fine on Ubuntu however 4.1.0 not available from launchpad. Do you plan on updating it, or is it fine to stay on 4.0.7?

When I try waf configure I get problems with dbus, ligtkhtml4, gtkhtml-editor... PPA is easier :-)

**Comment by davenorthcreek** [comment]
I got farther than you but not to the finish line.

Built biblesync from source and registered it with pkg_config, now I'm getting an error that matches something from 2013 builds on Fedora:
```
[ 43/134] xsltproc2po: help/xiphos.omf.in build/default/help/fa/xiphos.xml -> build/default/help/fa/xiphos-fa.omf
warning: failed to load external entity "/Templates/C/scrollkeeper_cl.xml"
db2omf: Invalid subject code "GNOME|Applications" in /data/applications/xiphos-4.1.0/help/xiphos.omf.in.
warning: failed to load external entity "/Templates/C/scrollkeeper_cl.xml"
db2omf: Invalid subject code "GNOME|Applications" in /data/applications/xiphos-4.1.0/help/xiphos.omf.in.
warning: failed to load external entity "/Templates/C/scrollkeeper_cl.xml"
db2omf: Invalid subject code "GNOME|Applications" in /data/applications/xiphos-4.1.0/help/xiphos.omf.in.
Waf: Leaving directory `/data/applications/xiphos-4.1.0/build'
Build failed:
 -> task failed (err #10): 
        {task: xsltproc2po xiphos.omf.in,xiphos.xml -> xiphos-fa.omf}
 -> task failed (err #10): 
        {task: xsltproc2po xiphos.omf.in,xiphos.xml -> xiphos-fr.omf}
 -> task failed (err #10): 
        {task: xsltproc2po xiphos.omf.in,xiphos.xml -> xiphos-C.omf}
```

**Comment by davenorthcreek** [comment]
went back and installed a few more dependencies and it built successfully!

**Comment by mfreeman72** [comment]
I've been trying to find an updated Ubuntu package for a long time now, as it looks like the PPA is gone and it seems Crosswire isn't doing Linux binary packages anymore. I'm terrible at compiling from source and am unable to get a usable binary that way, and I really don't want to have to mess with that at all, anyway. This is incredibly frustrating, as the available version has some annoying UI glitches that I'm hoping version 4.1.0 takes care of. Anyone have a solution?

**Comment by davenorthcreek** [comment]
I'll take a look tomorrow at what it would take to build again.  What linux are you using?

**Comment by davenorthcreek** [comment]
I just tried to rebuild from source, xiphos 4.1.0 needs sword 1.8 and the Ubuntu repo only has 1.7.3 (I think) so I'm rebuilding sword from source as well.  I don't have any experience building packages for linux repos so I don't think I can do more than prove that it can be done.

**Comment by davenorthcreek** [comment]
See the work by LAfricain referenced above - I'll try to build that and report back here.

**Comment by davenorthcreek** [comment]
This worked for me, no building from source required (I did a bunch of unsuccessful building, but then I tried @LAfricain's package for the second time and it worked.

sudo add-apt-repository ppa:lafricain79/lafricainenvrac
sudo apt update
sudo apt install libsword-1.8.1
sudo apt install libbiblesync1.1
sudo apt install xiphos

**Comment by LAfricain** [comment]
@karlkleinpaste this issue can be closed.
