### ISSUE TITLE
wrong JFB commentary link

### ISSUE THREAD

**Issue by jlong777** [crosswire/xiphos#929]
JFB commentary link on Rev 21:3 "having previously been in heaven: Re 11:19; 15:5" goes to Rev 11:5, instead of Re 11:19; 15:5.
xiphos
4.0.4 (gtk3 webkit1)

**Comment by karlkleinpaste** [comment]
module content errors aren't an area for xiphos bugfixes.
see bugs.crosswire.org, file a bug in modules.
