### ISSUE TITLE
Xiphos on Fedora 29 Gnome Wayland

### ISSUE THREAD

**Issue by jadesoye** [crosswire/xiphos#931]
The Bible books drop down incorrect on wayland in Fedora 29. Please see picture.
![image](https://user-images.githubusercontent.com/30211719/54070069-07f9ac80-4254-11e9-95e3-fdebe5f33c05.png)

**Comment by Bohooslav** [comment]
I was the same problem in fedora 29 but now in fedora 30 I have no this issue

**Comment by karlkleinpaste** [comment]
in general, please reproduce any visual problems seen in wayland under Xorg before reporting. wayland is (still) new and it continues to have visual glitches that are specific only to wayland, not seen under Xorg.
