### ISSUE TITLE
download manager doesn't load any bibles

### ISSUE THREAD

**Issue by Mark-MI** [crosswire/xiphos#933]
two weeks ago I installed into Zorin (Linux) OS with great results.  I re-installed Zorin for a more advanced copy (business version) and re-installed Xiphos, but the download manager comes up with no Bibles and Xiphos shuts down because there are no Bibles.  Is there a manual work-around?

**Comment by LAfricain** [comment]
You can download manually the modules from [Crosswire](http://crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles).

**Comment by karlkleinpaste** [comment]
this has to be a cockpit error. did you refresh the repo before attempting to install?
Refresh is a button at the bottom of both Module Sources -> Choose and Modules -> Install/Update.
