### ISSUE TITLE
Features request: When clicking right on a word opens a windows with all the word with the same Strong's number

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#939]
This features exist on Bibletime: When you click right on a selected greek word, a windows opens with all the places of the Strong number in the bible.
Look the capture:
![strong-search-windows](https://user-images.githubusercontent.com/19690477/55704558-b1ab9500-59dc-11e9-95be-bf0aa7153e65.png)

It would be interesting to have this feature also in Xiphos.

**Comment by karlkleinpaste** [comment]
i'm declining this. the reason is that we provide a similar facility via the dictionary pane: if a Heb/Grk dictionary is open there, it offers a sidebar search button in the right set of buttons, leftmost. so if you've clicked a strong's number to get the dictionary to react, then you can get a search there.

**Comment by LAfricain** [comment]
I'm not sure to understand well how to do... You speak about the advance search?

**Comment by karlkleinpaste** [comment]
no.
any time there is a Heb/Grk dictionary in the regular dictionary pane, there is an additional button displayed, leftmost of the set at the right, that is a sidebar search for the current strong's number.

so if you've got a Grk bible open, click a strong's annotation, dictionary navigates to that. then you can click that search button, and the sidebar search will reveal the verse list of all verses containing that entry.

**Comment by LAfricain** [comment]
Wow!!!!!
This is amazing!!! I never saw this button!!! This is exactly what I was expecting for. It would be very interesting to add some information in the help about this feature. A new page about strong search or something like this.
