### ISSUE TITLE
Not all dictionnaries shown in the Preference → Defaut dictionary

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#945]
If I'm in a bible text, I do a double click on a word, it opens the dictionary but not with the good word. I need to click again two times on the word. Ex: I double-click on θεὸς it opens the dic in ΚΑῚ (the last search), I double-click again on θεὸς it opens in the good place: ΘΕῸΣ.
An other problem, not all the dics appear in the list in the preferences windows.

**Comment by LAfricain** [comment]
Even the Strong numbers don't work for me. If I click on a strong number in a module text, nothing happens. And when the morph and strong options are selected it is impossible to copy/paste correctly. Most of one word is selected.

**Comment by LAfricain** [comment]
I think this seems to be solved. Only this is still relevant:
>not all the dics appear in the list in the preferences windows.

**Comment by karlkleinpaste** [comment]
that would be ... most odd.
the code simply loops through all available dictionaries and stuffs them into the pulldown.
for heb/grk dictionaries, it does a selection from all dictionaries of those with e.g. Feature=GreekDef.
i could use an example of such a failure in order to chase down where the qualifiers didn't get caught in the right module selector.

**Comment by LAfricain** [comment]
Look the picture, I install fredaw, but it's not in the list of the dic, I can't chose it:
![dic](https://user-images.githubusercontent.com/19690477/79494044-a7c26600-8022-11ea-8aa3-61945ebe2331.png)

**Comment by karlkleinpaste** [comment]
i need to see the .conf for the module you think is missing.

**Comment by LAfricain** [comment]
OK, look the fredaw conf and frebailly conf:
[Fredic.zip](https://github.com/crosswire/xiphos/files/4489205/Fredic.zip)

**Comment by LAfricain** [comment]
I have maybe a explanation. It's possible the dic not seen are the one installed in root. All the dic installed in $HOME seems to be seen.

**Comment by LAfricain** [comment]
I found the solution, two extra lines in the conf:
```
Feature=Images
Category=Lexicon/Dictionary
```
After I deleted it the module was present in the list.

**Comment by LAfricain** [comment]
I spoke with @domcorbex, and as he pointed out to me this two entries are documented on the [wiki](https://wiki.crosswire.org/DevTools:conf_Files). Then we have to consider this is a xiphos issue. For this I keep this issue open.

**Comment by LAfricain** [comment]
Solved with new fredaw update, the faulty line was "Category="
