### ISSUE TITLE
Remove Waf

### ISSUE THREAD

**Issue by domcorbex** [crosswire/xiphos#946]
The python based ./waf build system is being deprecated.
My proposal is to remove Waf from the source tree, and then use only CMake as our
based build system.

If there are no refusal to delete waf or raising concerns about the removal over the next couple of weeks, I'll delete Waf and all relevant files on May the 10th, namely:
- waf
- wscript
- */wscript_build
- waffles/
- debian/ (CMake builds debs)
- help/   (We have switched from docbook to mallard-project)

Dom

**Comment by greg-hellings** [comment]
:+1:

**Comment by domcorbex** [comment]
Closed by commit #3482fe6
