### ISSUE TITLE
Installing new versions of modules that already is installed, instead of upgrade old, call some errors

### ISSUE THREAD

**Issue by Bohooslav** [crosswire/xiphos#951]
When I jump to 7 - 15  verses, I got this error

![Screenshot from 2019-06-14 14-14-58](https://user-images.githubusercontent.com/35796539/59505709-d88bb900-8eae-11e9-92ff-02a137908f2f.png)

Also I have another errors by next reason. I install new versions of modules that already is installed on my laptop instead of upgrade old, and this rise the error, and some other errors.

**Comment by karlkleinpaste** [comment]
fixed per #958, identical bug.
