### ISSUE TITLE
Preferences Menu Comes Up When Starting Xiphos

### ISSUE THREAD

**Issue by rbeltz48** [crosswire/xiphos#952]
I am using MX Linux 18.3. When I start Xiphos 4.0.4 (gtk3 webkit1) the Preferences Menu sometimes comes up on the screen. Then, once I am using Xiphos and I try to open Preferences again, sometimes it will not open and other times it will open. It is a sporadic problem. I have tried reinstalling Xiphos to no avail. This has never happened before with any previous release of Xiphos. Please help. Thanks.

**Comment by Bohooslav** [comment]
I also have the problem, and I resolve it for me just pressing button "Close" instead of cross ( X ) in the top.

**Comment by karlkleinpaste** [comment]
saving open-or-not status of mod.mgr, prefs, and adv.search is a feature since 3.1.6 was released in early 2014. it's simply a state save: if these windows were open when xiphos exited, they are re-opened on next start. close it and it will stay gone.
