### ISSUE TITLE
drop down menus for Bible books and chapter not working correctly

### ISSUE THREAD

**Issue by gawako1953** [crosswire/xiphos#956]
The arrows that normally appear at the top and bottom of the  drop down menus for books of the Bible, chapters, and verses are missing leaving no way to scroll through the entire list of each menu.

I have attempted to report this via Debian bts but reportbug will not work with my ISP's email servers.  I am running Xiphos 4.1.0 on Debian testing with all software updates applied.  My DE is XFCE4,

**Comment by domcorbex** [comment]
Issue maybe specific to your DE or Wayland version, see:
#931 
#947
I suggest you to try another DE or switch to Xorg.

**Comment by gawako1953** [comment]
On Sat, 2019-08-03 at 06:05 -0700, Dominique Corbex wrote:
> Issue maybe specific to your DE or Wayland version, see:
> #931 
> #947
> I suggest you to try another DE or switch to Xorg.
> 

This issue was solved by moving to Debian sid.  What specific package
--there were more than 200 upgraded when I switched releases--fixed the
issue I don't know, but this is solved.
