### ISSUE TITLE
ESV bible is missing from all repositories

### ISSUE THREAD

**Issue by modderking** [crosswire/xiphos#960]
I just installed xiphos on a new pc and both ESV2001 and ESV2011 are gone from the Crosswire repository and no other repositories have it. I have xiphos on another computer and it has the ESV from when I installed it a while back; is there a way to transfer the ESV from my old computer to my new one? I would really appreciate an answer, as I have grown to rely on the ESV for all my studies. (I went to the module manager in my old pc and saw the ESV, but then I refreshed the Install/Update window and indeed it disappeared.) 

Thanks for any help!

**Comment by karlkleinpaste** [comment]
look in your Sword directory.
(linux: /home/YourName/.sword; windows: c:/Users/Yourname/ApplicationData/Local/Sword).
in mods.d, there are configurations for each module, e.g. mods.d/esv2011.conf.
in that file, there is a DataPath line:
DataPath=./modules/texts/ztext/esv2011/

take copies of the configuration file plus all files under the DataPath area.
