### ISSUE TITLE
Consider removing Rarian

### ISSUE THREAD

**Issue by greg-hellings** [crosswire/xiphos#964]
Debian and SuSE both build without Rarian support, because the software has been abandonware for a long time. Here is Debian's patch to make this happen. Perhaps it would be good to consider bringing this into master?

https://salsa.debian.org/pkg-crosswire-team/xiphos/blob/master/debian/patches/0002-build-without-scrollkeeper.patch

**Comment by domcorbex** [comment]
Since the switch to CMake, Xiphos is no longer built with Rarian in master.

**Comment by greg-hellings** [comment]
@domcorbex Have we had a release since then?
