### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by ArnoVersfeld** [crosswire/xiphos#976]
WEBME: John 15:20 *x1
WEBME: John18:9 *x1

Xiphos
Module error: Unusable xref encoding.
Please report this, with module & verse

**Comment by LAfricain** [comment]
Just install the same module with the ebible.org repository. This issue is not a Xiphos issue but a module issue.

**Comment by DavidHaslam** [comment]
Created https://tracker.crosswire.org/browse/MOD-362

The issue should be closed here.

In future, please do not use **Xiphos** issues to report module issues.

**Comment by DavidHaslam** [comment]
See also https://tracker.crosswire.org/browse/MOD-363
