### ISSUE TITLE
zh-CN Book hebrew wrong

### ISSUE THREAD

**Issue by easonyuexcellent** [crosswire/xiphos#977]
/usr/share/sword/locales.d/zh_CN-utf8.conf
one line using traditional charactor“來” insted of “来”should be "Hebrews=希伯来书" however it's "Hebrews=希伯來书"
Which causes problem of navigation using language of Chinese Simplified.

**Comment by LAfricain** [comment]
What's your OS? Linux or Windows? What's xiphos version?

**Comment by easonyuexcellent** [comment]
Linux. Xiphos is the latest one on ubuntu19.10.
I found another bug with a simplified chinese charactor also, It seems you are using tradditional chinese and transcript into simplified chinese. 

2020-01-02 

easonyu_excellent 



发件人：LAfricain <notifications@github.com>
发送时间：2019-12-31 18:01
主题：Re: [crosswire/xiphos] zh-CN Book hebrew wrong (#977)
收件人："crosswire/xiphos"<xiphos@noreply.github.com>
抄送："easonyuexcellent"<easonyu_excellent@163.com>,"Author"<author@noreply.github.com>

What's your OS? Linux or Windows? What's xiphos version?

**Comment by LAfricain** [comment]
> I found another bug with a simplified chinese charactor

Please just report it here, I already propose your correction in the right place (it's not here). But I can do the correction, and after you can close this bug report.

**Comment by LAfricain** [comment]
We have an issue with ISaiah, with Ezeckiel, and other I can Identify.

**Comment by LAfricain** [comment]
I did some correction in the zh_CN.conf and proposed it to the Crosswire team. In the next release it will be ok. If you want to use it use the attached file, and copy it in /usr/share/sword/locales.d/ with the root privileges:
[zh_CN-utf8.zip](https://github.com/crosswire/xiphos/files/4022300/zh_CN-utf8.zip)
This issue can be closed after.

**Comment by karlkleinpaste** [comment]
this is a sword issue, not a xiphos issue. closing.
