### ISSUE TITLE
New release expected for debian

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#980]
On the debian bug tracker:
This package (xiphos) Build-Depends on gnome-doc-utils. gnome-doc-utils is a
deprecated package of documentation utilities. Its most recent upstream
release was in 2012, with most changes in its git repository since then
being translation updates. The GNOME team do not consider gnome-doc-utils
to be suitable for release in Debian 11 'bullseye'.

The supported replacement is yelp.m4 in yelp-tools, as used
in many GNOME 3 packages. A porting guide is available:
https://wiki.gnome.org/Initiatives/GnomeGoals/NewDocumentationInfrastructure

gnome-doc-utils relies on Python 2 code that seems unlikely to be
converted to Python 3, so bug #936625 (part of the effort to remove
Python 2 from Debian for Debian 11 'bullseye') has its severity set to
serious. This means that this bug is highly likely to be elevated to
serious severity at some point in future.

Please convert this package to use yelp-tools, or if necessary remove
the documentation processing entirely.

**Comment by karlkleinpaste** [comment]
it appears that this already happened somewhere along the line. @greg-hellings's xiphos.spec references yelp-tools and does not mention gnome-doc-utils, and there is no mention of gnome-doc-utils anywhere under the cmake/ directory. closing as having evidently been done without anyone having noticed this report.

**Comment by LAfricain** [comment]
Do you know who maintain the deb package? Is this automatic? I think xiphos was already remove in testing...

**Comment by greg-hellings** [comment]
This is a change present in master, but still pending an official release. I believe it was done by the waf->cmake changes. So we'll still want a release soonish to satisfy Debian and Ubuntu packaging

**Comment by karlkleinpaste** [comment]
i intend that we make a 4.1.1 release within the week.

**Comment by LAfricain** [comment]
It's very sad, xiphos is not present in Ubuntu 20.04 LTS.
