### ISSUE TITLE
Arb, cmn and ktu are translated in English in the list of modules

### ISSUE THREAD

**Issue by LAfricain** [crosswire/xiphos#985]
Three iSO3 codes are not displayed in the original language in the module manager, but translated in English, it is Arb, translated by Standard Arabic, cmn translated by Mandarin Chinese.
Ktu also in translated by Democratic Republic of Congo, but it should be or in French or localized for translation, because the official language in DRC is French.

**Comment by DavidHaslam** [comment]
The **Unknown** language branch also includes Bible modules with the following ISO **lang codes** found in the **eBible.org** repo.
- dwy
- guj
- npi
- ntu
- ory
- wrk
- wro

NB. These codes are the first three letters of each module name, in accordance with the eBible module naming convention.

In addition, from the **IBT** repository, these **Bible modules** are in the **Unknown** language branch.
- BSK
- KKDC
- KKDL
- KOR
- LEZ
- TSK

NB. The modules would need to be installed to ascertain the lang code in each .conf file

**Comment by karlkleinpaste** [comment]
I'm totally fine with updates to the languages file. Find proper Arabic et al expressions of these language names and file a PR.

**Comment by LAfricain** [comment]
Solved with #992

**Comment by DavidHaslam** [comment]
@karlkleinpaste 
Were all the reported languages codes fixed in #992 or just those reported by @LAfricain ?

**Comment by karlkleinpaste** [comment]
just those he reported, i suppose. let those concerned with certain unknown codes put in the effort to arrange for their inclusion.

**Comment by LAfricain** [comment]
I checked all the missing codes, and I added all the missing. I did the same for sword (bishop) and I'm working for this in bibletime, but in BT it's not easy because it's "hard" coded, not only a file.
