### ISSUE TITLE
Suggestion: Change the Unknown language branch to ! Unknown

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#991]
If you inserted an exclamation mark in the **Unknown** languages branch label, it would then appear first at the top of the tree.

This would make it more likely that users would report any language codes that were not displayed as their own localized language name.

**Comment by LAfricain** [comment]
This is solved with this #992 pull request. I added the new locales.

**Comment by karlkleinpaste** [comment]
the addition in 992 is for specific locales; david is looking for a general catch-all for future modules that are not yet known to our languages file.

while i understand and appreciate the intent, the idea of fudging up the lists with a hectored element dominating the list top seems unwise. i'm declining to do this.
