### ISSUE TITLE
Dropdown Menu only Shows OT books on Complete Bible, NT Bibles left out.

### ISSUE THREAD

**Issue by HnkGitHub** [crosswire/xiphos#995]
Debian Buster AMD64
4.1.0 (gtk3 webkit2)

I was trying to get this  to work with the Debian packages. But when trying to access books in the New Testament with the KJV module, or  other modules with both testaments, only the Old Testament Books appear. Cannot continue to scroll to access the NT books.

Recompiled from source on Debian using the following  configuration:
 Xiphos version               4.1.0
--   Release date                 May 2019
--   Build type                   Release
--   Install prefix               /usr/local
--   Gtk version                  Gtk+-3.0
--   WebKitGTK                    WebKit2
--   Editor                       Gtkhtml
--   D-Bus                        ON

I had to compile some dependencies from source: Debian had no packages for some of the dependencies in Buster. This config is not the same as the Debian Package. But I had the same problem.

I'm guessing webkit2 is the problem. But what configuration is  known to work correctly? I don't like having to fight against Debian, dependencies, etc. I think, if I recall right, The buster package had webkit1? But I would really like to know which versions have been verified to work so at least I can compile from the proper sources to get this to work. 

Typing in manually the name of the book works fine. It's just the drop down for the names of Books not showing the NT Books. It seems that the Drop down menu does not detect the bottom of the screen, The selection stops at around Zephaniah with the mouse scroll button. I can use the keyboard scroll (down arrow key) and the selection disappears and a New Testament Book will popup. But the visual representation of the NT Books does not show

Thanks.

Henry

**Comment by alerque** [comment]
This is probably an iteration of the issue already reported in #947. Can you try the scrolling related things there to confirm?

Also note this sort of thing would be mitigated if #901 were implemented.

**Comment by HnkGitHub** [comment]
The Scroll arrow does not show. I tried switching to portrait view and the list shows up. Only cause there's more room. Apparently, the code for detecting the bottom of the screen is not picking up the bottom of the screen to show the scroll arrow. 

The code should find the screen size, calculate the length of the drop down within that size, and place--if necessary--a drop down scroll arrow to allow scrolling the books. This was the previous behavior. 
![scroll](https://user-images.githubusercontent.com/38794884/79326054-d849b900-7ed7-11ea-890e-6f8a9f0e68c0.png)

**Comment by karlkleinpaste** [comment]
the code for all dropdowns of this sort does not (has not ever) done any size calculation; the toolkit is responsible for handling lists taller than the screen on its own, and the scroll arrows are thus to be automatic. i don't know what to say about this behavior.

**Comment by karlkleinpaste** [comment]
because #947 and this are the same bug, i'm closing this one.
i'm liable to close it as well because this truly is a toolkit problem, but in any event, only 1 of these makes sense to leave open.

**Comment by greg-hellings** [comment]
What are you disagreeing with? This is the job of GTK, not Xiphos, to make that accessible.

**Comment by HnkGitHub** [comment]
It looks like a different tool on closer inspection. The one that works has 1 drop down arrow. The other that doesn't work has an up and a down arrow. It's that not big of a deal to me. I was just wondering if there were some code or parameters being passed to the tool. But apparently not. 

But I do appreciate your feedback and the work you're doing.
