### ISSUE TITLE
Localized language names not displayed (Unknown language branch in MM)

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#998]
The **Unknown** language branch also includes Bible modules with the following ISO **lang codes** found in the **eBible.org** repo.
- dwy
- guj
- npi
- ntu
- ory
- wrk
- wro

NB. These codes are the first three letters of each module name, in accordance with the eBible module naming convention.

In addition, from the **IBT** repository, these **Bible modules** are in the **Unknown** language branch.
- BSK
- CHE
- KKDC
- KKDL
- KOR
- LEZ
- TSK

NB. The modules would need to be installed to ascertain the precise lang code in each .conf file.

**Comment by DavidHaslam** [comment]
**Aside:** Might it be useful to include in the **Xiphos** module manager a new column that shows the **lang code** found in the .conf files?

This would make it easier to report Unknown languages as it would obviate needing to install the modules.

**Comment by karlkleinpaste** [comment]
mod.mgr is dangerously cluttered as it is. i will not be adding more elements to it.

you know the unknown codes. file an update.

**Comment by LAfricain** [comment]
I will take care of this, if I find unknown languages. You can close the issue.
