### ISSUE TITLE
Trailing zeroes in a module version number?

### ISSUE THREAD

**Issue by DavidHaslam** [crosswire/xiphos#999]
I just observed that Xiphos MM "thinks" that **eBible.org** module **ben2006eb** version **3.30** is an updated version of version **3.3**

Are trailing zeroes supposed to be significant in module versions?

This is in the **Bengali** language branch (with localized name).

**Comment by greg-hellings** [comment]
3 != 30. Xiphos is correct. 3.30 is an updated version of 3.3. It's 27 minor versions updated, in fact.

Now, in most version conventions, it would not be an updated version of 3.3.0, but 3.30 is not the same as 3.3.0 by a very wide margin.

**Comment by karlkleinpaste** [comment]
the version check is a simple lexicographic comparison. it's up to module producers to ensure that they make sense.
